-- Rails' `postgresql:` connection entries carry no credential at all
-- (vendor/rails/activerecord/test/config.example.yml:74-81) — `rake
-- db:postgresql:build` (Rakefile:258-262) creates no role at all, it just runs
-- createdb as the local user. This role is the container equivalent: a
-- passwordless `rails` role, reachable because the container runs with
-- POSTGRES_HOST_AUTH_METHOD=trust. PERMANENT DEVIATION: a passwordless role
-- cannot otherwise connect over TCP, and there is no "local user" inside a
-- service container to inherit.
--
-- CREATEDB: each vitest worker creates its own AR_DB_SLOT copy of the database
-- (activerecord_unittest_<token>_1, _2, …), which Rails' single-database run
-- never needs.
--
-- SUPERUSER: PERMANENT DEVIATION, and it cannot be dropped. Rails' local user
-- is a superuser by construction (it owns the cluster it initdb'd), and the
-- suite installs extensions that are *not* trusted, so database ownership plus
-- CREATEDB is not enough: postgres_fdw (adapters/postgresql/foreign-table.test.ts,
-- which also CREATE SERVERs) and pg_hint_plan
-- (adapters/postgresql/optimizer-hints.test.ts) both require superuser. Only
-- the trusted extensions (hstore, citext) would work under a plain owner.
CREATE ROLE rails LOGIN CREATEDB SUPERUSER;
ALTER DATABASE activerecord_unittest OWNER TO rails;
