import { RuleTester } from "eslint";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import rule from "./rails-deprecated-jsdoc.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const MANIFEST_PATH = path.join(__dirname, "rails-deprecated-methods.json");

// The manifest is regenerated by `pnpm prelint`. Make this test hermetic by
// writing a minimal fixture and restoring whatever was there on exit, so it
// passes on a clean checkout regardless of whether prelint has run.
const hadExisting = fs.existsSync(MANIFEST_PATH);
const original = hadExisting ? fs.readFileSync(MANIFEST_PATH, "utf8") : null;
const fixture = {
  files: {
    "packages/activerecord/src/connection-handling.ts": ["connection"],
  },
};
fs.writeFileSync(MANIFEST_PATH, JSON.stringify(fixture, null, 2));
process.on("exit", () => {
  if (hadExisting) fs.writeFileSync(MANIFEST_PATH, original);
  else fs.rmSync(MANIFEST_PATH, { force: true });
});

const connFile = path.join(REPO_ROOT, "packages/activerecord/src/connection-handling.ts");

const tester = new RuleTester({
  languageOptions: {
    ecmaVersion: 2022,
    sourceType: "module",
    parser: (await import("typescript-eslint")).parser,
  },
});

tester.run("rails-deprecated-jsdoc", rule, {
  valid: [
    // Already tagged.
    {
      filename: connFile,
      code: `/** @deprecated */\nexport function connection() {}\n`,
    },
    // Name not in manifest.
    {
      filename: connFile,
      code: `export function notADeprecatedName() {}\n`,
    },
    // Already tagged inside multi-line JSDoc.
    {
      filename: connFile,
      code: `/**\n * Doc.\n * @deprecated\n */\nexport function connection() {}\n`,
    },
    // Interface method (TSMethodSignature) already tagged.
    {
      filename: connFile,
      code: `interface Adapters {\n  /** @deprecated */\n  connection(): unknown;\n}\n`,
    },
  ],
  invalid: [
    // Missing tag, no JSDoc — insert a fresh block.
    {
      filename: connFile,
      code: `export function connection() {}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `/** @deprecated */\nexport function connection() {}\n`,
    },
    // Missing tag, existing JSDoc — append @deprecated.
    {
      filename: connFile,
      code: `/**\n * Does a thing.\n */\nexport function connection() {}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `/**\n * Does a thing.\n *\n * @deprecated\n */\nexport function connection() {}\n`,
    },
    // Class method with no JSDoc.
    {
      filename: connFile,
      code: `class Base {\n  connection() {}\n}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `class Base {\n  /** @deprecated */\n  connection() {}\n}\n`,
    },
    // Single-line JSDoc must be expanded into a multi-line block, not
    // mangled into `/** Foo *\n * @deprecated\n */`.
    {
      filename: connFile,
      code: `/** Returns the adapter. */\nexport function connection() {}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `/**\n * Returns the adapter.\n *\n * @deprecated\n */\nexport function connection() {}\n`,
    },
    // A non-adjacent file header must NOT be treated as the node's JSDoc —
    // autofix should add a fresh block, not splice into the header.
    {
      filename: connFile,
      code: `/** File header. */\n\nexport function connection() {}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `/** File header. */\n\n/** @deprecated */\nexport function connection() {}\n`,
    },
    // Interface method (TSMethodSignature) with no JSDoc — this is the
    // branch that tags `unsignedFloat`/`unsignedDecimal` on the
    // `ColumnMethods` interface in mysql/schema-definitions.ts.
    {
      filename: connFile,
      code: `interface Adapters {\n  connection(): unknown;\n}\n`,
      errors: [{ messageId: "missingDeprecated" }],
      output: `interface Adapters {\n  /** @deprecated */\n  connection(): unknown;\n}\n`,
    },
  ],
});

console.log("rails-deprecated-jsdoc: ok");
