import { RuleTester } from "eslint";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import rule from "./rails-private-jsdoc.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const MANIFEST_PATH = path.join(__dirname, "rails-private-methods.json");

// The manifest is gitignored and regenerated by `pnpm rails-privates:manifest`.
// Make this test hermetic by writing a minimal fixture and restoring whatever
// was there (if anything) on exit, so the test passes on a clean checkout
// regardless of whether the user has run the full extract step.
const hadExisting = fs.existsSync(MANIFEST_PATH);
const original = hadExisting ? fs.readFileSync(MANIFEST_PATH, "utf8") : null;
const fixture = {
  files: {
    "packages/activerecord/src/inheritance.ts": ["computeType"],
  },
  packageGlobals: {
    activerecord: ["computeType"],
  },
};
fs.writeFileSync(MANIFEST_PATH, JSON.stringify(fixture, null, 2));
process.on("exit", () => {
  if (hadExisting) fs.writeFileSync(MANIFEST_PATH, original);
  else fs.rmSync(MANIFEST_PATH, { force: true });
});

const inheritanceFile = path.join(REPO_ROOT, "packages/activerecord/src/inheritance.ts");
const baseFile = path.join(REPO_ROOT, "packages/activerecord/src/base.ts");

const tester = new RuleTester({
  languageOptions: {
    ecmaVersion: 2022,
    sourceType: "module",
    parser: (await import("typescript-eslint")).parser,
  },
});

tester.run("rails-private-jsdoc", rule, {
  valid: [
    // Already tagged.
    {
      filename: inheritanceFile,
      code: `/** @internal */\nexport function computeType() {}\n`,
    },
    // Name not in manifest.
    {
      filename: inheritanceFile,
      code: `export function notARailsName() {}\n`,
    },
    // Already tagged inside multi-line JSDoc.
    {
      filename: inheritanceFile,
      code: `/**\n * Doc.\n * @internal\n */\nexport function computeType() {}\n`,
    },
    // Class method that's already tagged.
    {
      filename: baseFile,
      code: `class Base {\n  /** @internal */\n  static computeType() {}\n}\n`,
    },
  ],
  invalid: [
    // File-scoped match: function with no JSDoc.
    {
      filename: inheritanceFile,
      code: `export function computeType() {}\n`,
      errors: [{ messageId: "missingInternal" }],
      output: `/** @internal */\nexport function computeType() {}\n`,
    },
    // File-scoped match: function with existing JSDoc — append @internal.
    {
      filename: inheritanceFile,
      code: `/**\n * Does a thing.\n */\nexport function computeType() {}\n`,
      errors: [{ messageId: "missingInternal" }],
      output: `/**\n * Does a thing.\n *\n * @internal\n */\nexport function computeType() {}\n`,
    },
    // Package-global match: static method on a class in base.ts (whose
    // host file isn't the Ruby source of `compute_type`).
    {
      filename: baseFile,
      code: `class Base {\n  static computeType() {}\n}\n`,
      errors: [{ messageId: "missingInternal" }],
      output: `class Base {\n  /** @internal */\n  static computeType() {}\n}\n`,
    },
    // Single-line JSDoc must be expanded into a multi-line block, not
    // mangled into `/** Foo *\n * @internal\n */`.
    {
      filename: inheritanceFile,
      code: `/** Resolve a name. */\nexport function computeType() {}\n`,
      errors: [{ messageId: "missingInternal" }],
      output: `/**\n * Resolve a name.\n *\n * @internal\n */\nexport function computeType() {}\n`,
    },
    // A non-adjacent file header must NOT be treated as the node's
    // JSDoc — autofix should add a fresh `/** @internal */` instead of
    // splicing into the header.
    {
      filename: inheritanceFile,
      code: `/** File header. */\n\nexport function computeType() {}\n`,
      errors: [{ messageId: "missingInternal" }],
      output: `/** File header. */\n\n/** @internal */\nexport function computeType() {}\n`,
    },
  ],
});

console.log("rails-private-jsdoc: ok");
