import { describe, it } from "vitest";

describe("TimeExtCalculationsTest", () => {
  it.skip("seconds since midnight at daylight savings time start");
  it.skip("seconds since midnight at daylight savings time end");
  it.skip("seconds until end of day at daylight savings time start");
  it.skip("seconds until end of day at daylight savings time end");
  it.skip("sec fraction");
  it.skip("floor");
  it.skip("ceil");
  it.skip("daylight savings time crossings backward start");
  it.skip("daylight savings time crossings backward end");
  it.skip("daylight savings time crossings backward start 1day");
  it.skip("daylight savings time crossings backward end 1day");
  it.skip("since with instance of time deprecated");
  it.skip("daylight savings time crossings forward start");
  it.skip("daylight savings time crossings forward start 1day");
  it.skip("daylight savings time crossings forward start tomorrow");
  it.skip("daylight savings time crossings backward start yesterday");
  it.skip("daylight savings time crossings forward end");
  it.skip("daylight savings time crossings forward end 1day");
  it.skip("daylight savings time crossings forward end tomorrow");
  it.skip("daylight savings time crossings backward end yesterday");
  it.skip("change");
  it.skip("utc change");
  it.skip("offset change");
  it.skip("change offset");
  it.skip("change preserves offset for local times around end of dst");
  it.skip("change preserves offset for zoned times around end of dst");
  it.skip("change preserves fractional seconds on zoned time");
  it.skip("change preserves fractional hour offset for local times around end of dst");
  it.skip("change preserves fractional hour offset for zoned times around end of dst");
  it.skip("utc advance");
  it.skip("offset advance");
  it.skip("advance with nsec");
  it.skip("advance gregorian proleptic");
  it.skip("advance preserves offset for local times around end of dst");
  it.skip("advance preserves offset for zoned times around end of dst");
  it.skip("advance preserves fractional hour offset for local times around end of dst");
  it.skip("advance preserves fractional hour offset for zoned times around end of dst");
  it.skip("last week");
  it.skip("next week near daylight start");
  it.skip("next week near daylight end");
  it.skip("to fs");
  it.skip("to fs custom date format");
  it.skip("rfc3339 with fractional seconds");
  it.skip("to date");
  it.skip("to datetime");
  it.skip("to time");
  it.skip("fp inaccuracy ticket 1836");
  it.skip("days in month with year");
  it.skip("days in month feb in common year without year arg");
  it.skip("days in month feb in leap year without year arg");
  it.skip("days in year with year");
  it.skip("days in year in common year without year arg");
  it.skip("days in year in leap year without year arg");
  it.skip("xmlschema is available");
  it.skip("today with time local");
  it.skip("today with time utc");
  it.skip("yesterday with time local");
  it.skip("yesterday with time utc");
  it.skip("prev day with time utc");
  it.skip("tomorrow with time local");
  it.skip("tomorrow with time utc");
  it.skip("next day with time utc");
  it.skip("past with time current as time local");
  it.skip("past with time current as time with zone");
  it.skip("future with time current as time local");
  it.skip("future with time current as time with zone");
  it.skip("acts like time");
  it.skip("formatted offset with utc");
  it.skip("formatted offset with local");
  it.skip("compare with time");
  it.skip("compare with datetime");
  it.skip("compare with time with zone");
  it.skip("compare with string");
  it.skip("at with datetime");
  it.skip("at with datetime returns local time");
  it.skip("at with time with zone");
  it.skip("at with in option");
  it.skip("at with time with zone returns local time");
  it.skip("at with time microsecond precision");
  it.skip("at with utc time");
  it.skip("at with local time");
  it.skip("eql?");
  it.skip("minus with time with zone");
  it.skip("minus with datetime");
  it.skip("time created with local constructor cannot represent times during hour skipped by dst");
  it.skip("case equality");
  it.skip("all day with timezone");
  it.skip("rfc3339 parse");
});
