import { describe, it } from "vitest";

describe("ACLogSubscriberTest", () => {
  it.skip("start processing", () => {});
  it.skip("start processing as json", () => {});
  it.skip("start processing as non exten", () => {});
  it.skip("halted callback", () => {});
  it.skip("process action", () => {});
  it.skip("process action without parameters", () => {});
  it.skip("process action with parameters", () => {});
  it.skip("multiple process with parameters", () => {});
  it.skip("process action with wrapped parameters", () => {});
  it.skip("process action with view runtime", () => {});
  it.skip("process action with path", () => {});
  it.skip("process action with throw", () => {});
  it.skip("append info to payload is called even with exception", () => {});
  it.skip("process action headers", () => {});
  it.skip("process action with filter parameters", () => {});
  it.skip("redirect to", () => {});
  it.skip("filter redirect url by string", () => {});
  it.skip("filter redirect url by regexp", () => {});
  it.skip("does not filter redirect params by default", () => {});
  it.skip("filter redirect params by string", () => {});
  it.skip("filter redirect params by regexp", () => {});
  it.skip("filter redirect bad uri", () => {});
  it.skip("send data", () => {});
  it.skip("send file", () => {});
  it.skip("with fragment cache", () => {});
  it.skip("with fragment cache when log disabled", () => {});
  it.skip("with fragment cache if with true", () => {});
  it.skip("with fragment cache if with false", () => {});
  it.skip("with fragment cache unless with true", () => {});
  it.skip("with fragment cache unless with false", () => {});
  it.skip("with fragment cache and percent in key", () => {});
  it.skip("process action with exception includes http status code", () => {});
  it.skip("process action with rescued exception includes http status code", () => {});
  it.skip("process action with with action not found logs 404", () => {});
});
