/**
 * ActionDispatch::Routing::UrlFor
 *
 * Mirrors `action_dispatch/routing/url_for.rb`. Provides the `urlFor` /
 * `fullUrlFor` / `routeFor` instance methods that hosts (controllers,
 * mailers, `Rails.application.routes.urlHelpers`) mix in via the
 * `this`-typed function pattern.
 *
 * @see https://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html
 */

import { NO_ROUTES_MESSAGE } from "../../abstract-controller/url-for.js";

/**
 * The minimal RouteSet surface UrlFor calls into. Matches Rails'
 * `_routes.url_for(options, route_name)` shape so future work can wire
 * `RouteSet` to it without changing this module.
 */
export interface UrlForRoutes {
  urlFor(options: Record<string, unknown>, routeName?: string | null): string;
  optimizeRoutesGeneration?(): boolean;
}

export interface UrlForHost {
  /** @internal Rails: `@_routes` */
  _routes: UrlForRoutes | null;
  defaultUrlOptions: Record<string, unknown>;
  urlOptions(): Record<string, unknown>;
  /**
   * Provided by `PolymorphicRoutes`, which Rails' `UrlFor` includes. Hosts
   * that include the polymorphic mixin must implement this; the array
   * branch of `fullUrlFor` delegates here.
   */
  polymorphicUrl?(record: unknown, options: Record<string, unknown>): string;
}

/**
 * Rails: `def initialize(...); @_routes = nil; super; end`.
 * Call this from a host constructor to mirror that hook.
 */
export function initialize(this: UrlForHost): void {
  this._routes = null;
}

/**
 * Hook overridden in controllers to add request information. Application
 * logic should not go into urlOptions.
 */
export function urlOptions(this: UrlForHost): Record<string, unknown> {
  return this.defaultUrlOptions;
}

/**
 * Generate a URL based on the options provided, `defaultUrlOptions`, and
 * the routes defined in `config/routes.rb`. Delegates to `fullUrlFor`.
 */
export function urlFor(this: UrlForHost, options?: UrlForOptions): string {
  return fullUrlFor.call(this, options);
}

export type UrlForOptions =
  | null
  | undefined
  | string
  | symbol
  | unknown[]
  | Record<string, unknown>
  | (new (...args: never[]) => unknown);

/** @internal */
export function fullUrlFor(this: UrlForHost, options?: UrlForOptions): string {
  if (options == null) {
    return requireRoutes(this).urlFor({ ...this.urlOptions() });
  }
  if (typeof options === "string") {
    return options;
  }
  if (Array.isArray(options)) {
    const components = [...options];
    const opts = extractOptions(components);
    if (typeof this.polymorphicUrl !== "function") {
      throw new Error("urlFor(Array) requires PolymorphicRoutes#polymorphicUrl on the host.");
    }
    return this.polymorphicUrl(components, opts);
  }
  if (isPlainObject(options)) {
    const hash = { ...(options as Record<string, unknown>) };
    const routeName = hash["use_route"];
    delete hash["use_route"];
    const merged = { ...this.urlOptions(), ...hash };
    return requireRoutes(this).urlFor(merged, routeName == null ? null : String(routeName));
  }
  // Symbol / Function / model — Rails delegates to HelperMethodBuilder.url
  // (in route_set.rb), which is not yet ported. Mirror the dispatch shape
  // so callers see the right surface area.
  throw new Error(
    `urlFor(${typeof options}) requires HelperMethodBuilder (not yet ported from route_set.rb)`,
  );
}

/**
 * Allows calling direct or regular named route.
 *
 *     threadablePath(threadable)  // => "/buckets/1"
 *     threadableUrl(threadable)   // => "http://example.com/buckets/1"
 */
export function routeFor(this: UrlForHost, name: string, ...args: unknown[]): string {
  // Rails: `public_send(:"#{name}_url", *args)`. Helper names generated by
  // `generateRouteHelpers` are snake_case `${name}_url`.
  const helper = `${name}_url`;
  const fn = (this as unknown as Record<string, unknown>)[helper];
  if (typeof fn !== "function") {
    throw new Error(`No url helper "${helper}" defined`);
  }
  return (fn as (...a: unknown[]) => string).apply(this, args);
}

/** @internal Rails: `protected def optimize_routes_generation?` */
export function optimizeRoutesGeneration(this: UrlForHost): boolean {
  const routes = requireRoutes(this);
  return (
    (routes.optimizeRoutesGeneration?.() ?? true) &&
    Object.keys(this.defaultUrlOptions).length === 0
  );
}

/** @internal Rails: `private def _with_routes(routes)` */
export function _withRoutes<T>(this: UrlForHost, routes: UrlForRoutes, block: () => T): T {
  const old = this._routes;
  this._routes = routes;
  try {
    return block();
  } finally {
    this._routes = old;
  }
}

/** @internal Rails: `private def _routes_context` */
export function _routesContext(this: UrlForHost): UrlForHost {
  return this;
}

/** @internal */
function requireRoutes(host: UrlForHost): UrlForRoutes {
  if (!host._routes) {
    throw new Error(NO_ROUTES_MESSAGE);
  }
  return host._routes;
}

/** @internal Rails: `case ... when Hash, ActionController::Parameters` — strict plain-object match. */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value == null || typeof value !== "object") return false;
  const proto = Object.getPrototypeOf(value);
  return proto === null || proto === Object.prototype;
}

/** @internal Rails: `Array#extract_options!` — pops a trailing options hash. */
function extractOptions(arr: unknown[]): Record<string, unknown> {
  const last = arr[arr.length - 1];
  if (isPlainObject(last)) {
    arr.pop();
    return last;
  }
  return {};
}
