import { describe, it } from "vitest";

// TimeWithZoneTest and TimeZoneTest require ActiveSupport::TimeZone infrastructure
// which depends on a full timezone database (TZInfo) not available in plain JS/TS.
// All tests are skipped pending timezone support implementation.

describe("TimeWithZoneTest", () => {
  it.skip("utc");
  it.skip("time");
  it.skip("time zone");
  it.skip("in time zone");
  it.skip("in time zone with argument");
  it.skip("in time zone with new zone equal to old zone does not create new object");
  it.skip("in time zone with bad argument");
  it.skip("in time zone with ambiguous time");
  it.skip("localtime");
  it.skip("utc?");
  it.skip("formatted offset");
  it.skip("dst?");
  it.skip("zone");
  it.skip("nsec");
  it.skip("strftime");
  it.skip("strftime with escaping");
  it.skip("inspect");
  it.skip("to s");
  it.skip("to fs");
  it.skip("to fs db");
  it.skip("to fs inspect");
  it.skip("to fs not existent");
  it.skip("xmlschema");
  it.skip("xmlschema with fractional seconds");
  it.skip("xmlschema with fractional seconds lower than hundred thousand");
  it.skip("xmlschema with nil fractional seconds");
  it.skip("iso8601 with fractional seconds");
  it.skip("rfc3339 with fractional seconds");
  it.skip("to yaml");
  it.skip("ruby to yaml");
  it.skip("yaml load");
  it.skip("ruby yaml load");
  it.skip("httpdate");
  it.skip("rfc2822");
  it.skip("compare with time");
  it.skip("compare with datetime");
  it.skip("compare with time with zone");
  it.skip("between?");
  it.skip("today");
  it.skip("yesterday?");
  it.skip("prev day?");
  it.skip("tomorrow?");
  it.skip("next day?");
  it.skip("past with time current as time local");
  it.skip("past with time current as time with zone");
  it.skip("future with time current as time local");
  it.skip("future with time current as time with zone");
  it.skip("before");
  it.skip("after");
  it.skip("eql?");
});

describe("TimeZoneTest", () => {
  it.skip("utc_to_local");
  it.skip("local_to_utc");
  it.skip("period_for_utc");
  it.skip("period_for_local");
  it.skip("local_to_utc_enforces_spring_dst_rules");
  it.skip("local_to_utc_enforces_fall_dst_rules");
  it.skip("name");
  it.skip("formatted_offset_with_utc");
  it.skip("formatted_offset_with_local");
  it.skip("abbreviation");
  it.skip("now");
  it.skip("today");
  it.skip("yesterday");
  it.skip("tomorrow");
  it.skip("parse");
  it.skip("parse without utc offset");
  it.skip("parse with incomplete date");
  it.skip("strptime");
  it.skip("strptime with incomplete date");
  it.skip("local");
  it.skip("at");
  it.skip("at with time with zone");
  it.skip("all");
  it.skip("all utc aliases");
  it.skip("new");
  it.skip("us zones");
  it.skip("country zones");
  it.skip("country zones with mappings");
  it.skip("find by tzinfo with valid key");
  it.skip("find by tzinfo with invalid key");
  it.skip("raise on unknown zone");
  it.skip("find by country code");
  it.skip("zones with dst");
  it.skip("zones without dst");
  it.skip("to r");
  it.skip("seconds to utc offset");
  it.skip("formatted offset with given offset in seconds");
  it.skip("formatted offset with given offset in seconds and separator");
});
