import { loadPrism } from "@ruby/prism";
import ts from "typescript";
import { Codegen } from "./codegen.js";
import { defaultRegistry } from "./handlers/index.js";
import type { Coverage, PrismNode } from "./types.js";
let parsePromise:
  | Promise<
      (src: string) => {
        value: unknown;
      }
    >
  | undefined;
async function getParser() {
  if (!parsePromise) parsePromise = loadPrism();
  return parsePromise;
}
export interface GenResult {
  code: string;
  coverage: Coverage;
  perDef: Map<
    string,
    {
      total: number;
      passthrough: number;
    }
  >;
  parseErrorCount: number;
}
const HEADER =
  "// GENERATED by scripts/prism-codegen (deterministic spike). Not compiled or tested,\n" +
  "// but parse-clean by construction (emitted via the TypeScript AST factory).\n" +
  "// Regenerate with `pnpm codegen:generate`. Do not edit by hand.\n\n";
export async function generateFromSource(
  rubySource: string,
  asyncMethods: ReadonlySet<string> = new Set(),
): Promise<GenResult> {
  const parse = await getParser();
  const result = parse(rubySource);
  const gen = new Codegen(defaultRegistry(), asyncMethods);
  const statements = gen.stmt(result.value as PrismNode, false);
  const sourceFile = ts.factory.createSourceFile(
    statements,
    ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
    ts.NodeFlags.None,
  );
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const code = HEADER + printer.printFile(sourceFile);
  const reparsed = ts.createSourceFile(
    "gen.js",
    code,
    ts.ScriptTarget.ESNext,
    true,
    ts.ScriptKind.JS,
  );
  const parseErrorCount = (
    (
      reparsed as unknown as {
        parseDiagnostics?: ts.Diagnostic[];
      }
    ).parseDiagnostics ?? []
  ).length;
  return { code, coverage: gen.coverage, perDef: gen.perDef, parseErrorCount };
}
export { summarizeCoverage } from "./coverage.js";
export { TARGET_FILES } from "./files.js";
export { asyncMethodsForRailsFile } from "./async-source.js";
