import { loadPrism } from "@ruby/prism";
import ts from "typescript";
import { Codegen } from "./codegen.js";
import { defaultRegistry } from "./handlers/index.js";
import { collectDelegations, mergeDelegations, type DelegationTable } from "./delegation.js";
import type { Linearization } from "./linearization.js";
import type { Coverage, PrismNode } from "./types.js";
let parsePromise:
  | Promise<
      (src: string) => {
        value: unknown;
      }
    >
  | undefined;
async function getParser() {
  if (!parsePromise) parsePromise = loadPrism();
  return parsePromise;
}
export interface GenResult {
  code: string;
  coverage: Coverage;
  perDef: Map<
    string,
    {
      total: number;
      passthrough: number;
    }
  >;
  parseErrorCount: number;
}
const HEADER =
  "// GENERATED by scripts/prism-codegen (deterministic spike). Not compiled or tested,\n" +
  "// but parse-clean by construction (emitted via the TypeScript AST factory).\n" +
  "// Regenerate with `pnpm codegen:generate`. Do not edit by hand.\n\n";
export async function generateFromSource(
  rubySource: string,
  asyncMethods: ReadonlySet<string> = new Set(),
  runtimeImportPath = "./runtime.js",
  inheritedDelegations: DelegationTable = new Map(),
  linearization: Linearization | null = null,
): Promise<GenResult> {
  const parse = await getParser();
  const result = parse(rubySource);
  const program = result.value as PrismNode;
  const delegations = mergeDelegations(inheritedDelegations, collectDelegations(program));
  const gen = new Codegen(defaultRegistry(), asyncMethods, delegations, linearization);
  const statements = gen.stmt(program, false);
  const sourceFile = ts.factory.createSourceFile(
    statements,
    ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
    ts.NodeFlags.None,
  );
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  let helperImport = "";
  if (gen.helpers.size > 0) {
    const names = [...gen.helpers].sort().join(", ");
    helperImport = `import { ${names} } from "${runtimeImportPath}";\n\n`;
  }
  const code = HEADER + helperImport + printer.printFile(sourceFile);
  return {
    code,
    coverage: gen.coverage,
    perDef: gen.perDef,
    parseErrorCount: countParseErrors(code),
  };
}
export function countParseErrors(code: string): number {
  const reparsed = ts.createSourceFile(
    "gen.js",
    code,
    ts.ScriptTarget.ESNext,
    true,
    ts.ScriptKind.JS,
  );
  return (
    (
      reparsed as unknown as {
        parseDiagnostics?: ts.Diagnostic[];
      }
    ).parseDiagnostics ?? []
  ).length;
}
export { summarizeCoverage } from "./coverage.js";
export { TARGET_FILES } from "./files.js";
export { asyncMethodsForRailsFile } from "./async-source.js";
export { type DelegationTable } from "./delegation.js";
export { buildLinearization, Linearization, parseIncludeOrder } from "./linearization.js";

/** Standalone pre-pass: the delegation table a file contributes to its family. */
export async function delegationsFromSource(rubySource: string): Promise<DelegationTable> {
  const parse = await getParser();
  return collectDelegations(parse(rubySource).value as PrismNode);
}
