export { AppGenerator } from "./app-generator.js";
export type { AppGeneratorOptions, AppDatabase } from "./app-generator.js";
export { ModelGenerator } from "./model-generator.js";
export { MigrationGenerator } from "./migration-generator.js";
export type { MigrationRunOptions } from "./migration-generator.js";
export { ControllerGenerator } from "./rails/controller/controller-generator.js";
export type { ControllerRunOptions } from "./rails/controller/controller-generator.js";
export { ScaffoldGenerator } from "./rails/scaffold/scaffold-generator.js";
export { GeneratorBase } from "./base.js";
export type { GeneratorOptions } from "./base.js";
export { NamedBase } from "./named-base.js";
export type { NamedBaseOptions } from "./named-base.js";
export { BenchmarkGenerator } from "./rails/benchmark/benchmark-generator.js";
export type { BenchmarkRunOptions } from "./rails/benchmark/benchmark-generator.js";
export { TaskGenerator } from "./rails/task/task-generator.js";
export type { TaskRunOptions } from "./rails/task/task-generator.js";
export { ScriptGenerator } from "./rails/script/script-generator.js";
export { AuthenticationGenerator } from "./rails/authentication/authentication-generator.js";
export { GeneratorGenerator } from "./rails/generator/generator-generator.js";
export type { GeneratorRunOptions } from "./rails/generator/generator-generator.js";
export { GeneratedAttribute, GeneratorError } from "./generated-attribute.js";
export type { AttrOptions, IndexType } from "./generated-attribute.js";
// CreateMigration action deferred to a 1.12b follow-up PR to stay under the
// 500 LOC ceiling — see docs/trailties-plan.md.
export { ActiveModel } from "./active-model.js";
export { AppBase } from "./app-base.js";
export type { AppBaseOptions } from "./app-base.js";
export { OPTION_IMPLICATIONS } from "./app-base.js";
export { Database, MySQL2, PostgreSQL, SQLite3, MariaDBMySQL2, DATABASES } from "./database.js";
export type { DatabaseName, PkgDependency, DockerService } from "./database.js";
export * from "./migration.js";
export * from "./model-helpers.js";
export * from "./resource-helpers.js";
