import { Dir } from "@blazetrails/ruby-compat";
import { Command } from "commander";
import { Generators } from "../generators.js";

export function destroyCommand(): Command {
  const cmd = new Command("destroy");
  cmd.alias("d");
  cmd.description("Remove code generated by `bin/trails generate`");

  cmd
    .argument("[generator]", "Generator name")
    .argument("[args...]", "Generator arguments")
    .allowUnknownOption()
    .action(async (generator: string | undefined, args: string[]) => {
      if (!generator) return cmd.help();

      await Generators.invoke(generator, args, {
        cwd: Dir.pwd(),
        output: console.log,
        behavior: "revoke",
      });
    });

  return cmd;
}
