import { Benchmarkable } from "@blazetrails/activesupport";
import { Module } from "@blazetrails/ruby-compat";
import { ActiveModelHelper } from "./helpers/active-model-helper.js";
import * as AssetTagHelper from "./helpers/asset-tag-helper.js";
import * as AssetUrlHelper from "./helpers/asset-url-helper.js";
import * as CacheHelper from "./helpers/cache-helper.js";
import { CaptureHelper } from "./helpers/capture-helper.js";
import { ContentExfiltrationPreventionHelper } from "./helpers/content-exfiltration-prevention-helper.js";
import * as ControllerHelper from "./helpers/controller-helper.js";
import * as DateHelper from "./helpers/date-helper.js";
import * as DebugHelper from "./helpers/debug-helper.js";
import * as FormHelper from "./helpers/form-helper.js";
import { FormTagHelper } from "./helpers/form-tag-helper.js";
import * as JavaScriptHelper from "./helpers/javascript-helper.js";
import * as NumberHelper from "./helpers/number-helper.js";
import { OutputSafetyHelper } from "./helpers/output-safety-helper.js";
import { RenderingHelper } from "./helpers/rendering-helper.js";
import { SanitizeHelper } from "./helpers/sanitize-helper.js";
import { TagHelper } from "./helpers/tag-helper.js";
import { TextHelper } from "./helpers/text-helper.js";
import { UrlHelper } from "./helpers/url-helper.js";

export const Helpers = new Module((mod) => {
  mod.include(Benchmarkable);
  mod.include(ActiveModelHelper);
  mod.include(AssetTagHelper);
  mod.include(AssetUrlHelper);
  mod.include(CacheHelper);
  mod.include(CaptureHelper);
  mod.include(ContentExfiltrationPreventionHelper);
  mod.include(ControllerHelper);
  mod.include(DateHelper);
  mod.include(DebugHelper);
  mod.include(FormHelper);
  mod.include(FormTagHelper);
  mod.include(JavaScriptHelper);
  mod.include(NumberHelper);
  mod.include(OutputSafetyHelper);
  mod.include(RenderingHelper);
  mod.include(SanitizeHelper);
  mod.include(TagHelper);
  mod.include(TextHelper);
  mod.include(UrlHelper);
});
