import { describe, it, expect, afterEach, afterAll, beforeAll, vi } from "vitest";
import { Inflections, camelize } from "@blazetrails/activesupport";
import {
  assertValidEnumDefinitionValues,
  assertValidEnumOptions,
  castEnumValue,
  detectNegativeEnumConditionsBang,
  enumTypeOf,
  EnumType,
  setEnumWarn,
} from "./enum.js";
import { ArgumentError, DecimalType } from "@blazetrails/activemodel";
import { Base } from "./index.js";
import { Map as MapCaster } from "./type-caster/map.js";
import { fixtures } from "./test-fixtures.js";
import { Book } from "./test-helpers/models/book.js";
import { Lion } from "./test-helpers/models/cat.js";

describe("Enum name conflict detection", () => {
  fixtures(["books"]);

  it("does not treat a user method on an ancestor class as a conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      status() {
        return "user method";
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  it("raises when a second enum reuses a value method defined by another enum", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("status", { active: 0, archived: 1 });
          this.enum("state", { active: 0, closed: 1 });
        }
      }
    }).toThrow(/already defined by another enum/);
  });

  it("raises when a friendly alias collides with a sibling label within one enum", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("status", { "api-key": 0, api_key: 1 });
        }
      }
    }).toThrow(/already defined by another enum/);
  });

  it("does not raise when a second enum reuses a value method but disables instance methods", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.attribute("status", "integer");
          this.attribute("state", "integer");
          this.enum("status", { active: 0, archived: 1 });
          this.enum("state", { active: 0, closed: 1 }, { instanceMethods: false });
        }
      }
      new Klass();
    }).not.toThrow();
  });

  it("does not treat a value method generated by a parent enum as a conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      static {
        this.enum("status", { active: 0, archived: 1 });
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          this.enum("difficulty", { active: 0, closed: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  it("does not treat a user class method on an ancestor as a plural-accessor conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      static statuses() {
        return "user class method";
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  it("raises for an enum name whose plural accessor is a framework class method", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("column", { a: 0, b: 1 });
        }
      }
      new Klass();
    }).toThrow(/enum named "column"/);
  });

  it("does not treat a bespoke subclass static as a class-method conflict", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static statuses() {
          return "bespoke";
        }
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Klass();
    }).not.toThrow();
  });

  it("raises for an enum name whose reader is a framework method", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("attributes", { a: 0, b: 1 });
        }
      }
      new Klass();
    }).toThrow(/enum named "attributes"/);
  });
});

describe("Enum private validators", () => {
  afterEach(() => vi.restoreAllMocks());

  describe("assertValidEnumDefinitionValues", () => {
    it("rejects empty array with ArgumentError", () => {
      expect(() => assertValidEnumDefinitionValues([])).toThrow(ArgumentError);
    });
    it("rejects array with non-string entries", () => {
      expect(() => assertValidEnumDefinitionValues([1, 2])).toThrow(ArgumentError);
    });
    it("accepts array with string entries", () => {
      const out = assertValidEnumDefinitionValues(["draft", "published"]);
      expect(out).toEqual(["draft", "published"]);
    });
    it("accepts array with symbol entries", () => {
      const out = assertValidEnumDefinitionValues([":draft", ":published"]);
      expect(out).toEqual([":draft", ":published"]);
    });
    it("rejects array mixing symbols and strings", () => {
      expect(() => assertValidEnumDefinitionValues([":draft", "published"])).toThrow(/symbols/);
    });
    it("rejects array with blank name", () => {
      expect(() => assertValidEnumDefinitionValues(["a", ""])).toThrow(/blank name/);
    });
    it("rejects array with whitespace-only name", () => {
      expect(() => assertValidEnumDefinitionValues(["a", "   "])).toThrow(/blank name/);
    });
    it("rejects hash with whitespace-only key", () => {
      expect(() => assertValidEnumDefinitionValues({ "   ": 1 })).toThrow(/blank name/);
    });
    it("rejects array with blank-description Symbol", () => {
      expect(() => assertValidEnumDefinitionValues([":"])).toThrow(/blank name/);
      expect(() => assertValidEnumDefinitionValues([":   "])).toThrow(/blank name/);
    });
    it("rejects non-plain-object values (Map/Date/class instances)", () => {
      expect(() => assertValidEnumDefinitionValues(new Map())).toThrow(
        /non-empty hash or an array/,
      );
      expect(() => assertValidEnumDefinitionValues(new Date())).toThrow(
        /non-empty hash or an array/,
      );
      class Foo {}
      expect(() => assertValidEnumDefinitionValues(new Foo())).toThrow(
        /non-empty hash or an array/,
      );
    });
    it("rejects empty hash", () => {
      expect(() => assertValidEnumDefinitionValues({})).toThrow(ArgumentError);
    });
    it("accepts hash with boolean and null values", () => {
      const out = assertValidEnumDefinitionValues({ a: true, b: null, c: 1 });
      expect(out).toEqual({ a: true, b: null, c: 1 });
    });
    it("rejects hash with non-primitive value", () => {
      expect(() => assertValidEnumDefinitionValues({ a: { x: 1 } })).toThrow(ArgumentError);
    });
    it("accepts hash with symbol keys", () => {
      const out = assertValidEnumDefinitionValues({ ":draft": 0 });
      expect(out).toBeDefined();
    });
    it("rejects hash with blank-description symbol key", () => {
      expect(() => assertValidEnumDefinitionValues({ ":": 0 })).toThrow(/blank name/);
    });
    it("rejects hash with NaN or Infinity number values", () => {
      expect(() => assertValidEnumDefinitionValues({ a: NaN })).toThrow(/finite numbers/);
      expect(() => assertValidEnumDefinitionValues({ a: Infinity })).toThrow(/finite numbers/);
    });
  });

  describe("assertValidEnumOptions", () => {
    it("rejects underscore-prefixed option keys with ArgumentError (enum.rb:361-365)", () => {
      expect(() => assertValidEnumOptions({ _prefix: "x" })).toThrow(ArgumentError);
      expect(() => assertValidEnumOptions({ _suffix: "x" })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _scopes: true })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _default: "active" })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _instance_methods: false })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _validate: true })).not.toThrow();
    });
    it("error message uses Ruby symbol inspect format (:key)", () => {
      expect(() => assertValidEnumOptions({ _prefix: "x" })).toThrow(/:_prefix/);
    });
    it("accepts valid options without throwing", () => {
      expect(() => assertValidEnumOptions({ prefix: "x", validate: true })).not.toThrow();
    });
    it("treats arrays as not-an-options-hash", () => {
      expect(() => assertValidEnumOptions([])).not.toThrow();
    });
    it("treats Map / Date / class instances as not-an-options-hash", () => {
      expect(() => assertValidEnumOptions(new Map())).not.toThrow();
      expect(() => assertValidEnumOptions(new Date())).not.toThrow();
      class Foo {}
      expect(() => assertValidEnumOptions(new Foo())).not.toThrow();
    });
  });

  describe("detectNegativeEnumConditionsBang", () => {
    it("warns when notDraft conflicts with draft (camelCase prefix)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["draft", "notDraft"]);
      expect(spy).toHaveBeenCalledWith(
        expect.stringMatching(/conflicts with auto-generated negative scope 'notDraft'/),
      );
    });
    it("warns when not_draft conflicts with draft (snake_case prefix)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["draft", "not_draft"]);
      expect(spy).toHaveBeenCalledWith(expect.stringMatching(/'not_draft'/));
    });
    it("routes warnings through setEnumWarn instead of console.warn", () => {
      const calls: string[] = [];
      setEnumWarn((msg) => calls.push(msg));
      try {
        const consoleSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
        detectNegativeEnumConditionsBang(["draft", "notDraft"]);
        expect(calls.length).toBe(1);
        expect(consoleSpy).not.toHaveBeenCalled();
      } finally {
        setEnumWarn((msg) => console.warn(msg));
      }
    });
    it("does not warn for unrelated identifiers starting with 'not' (notebook, notify)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["ebook", "notebook", "ify", "notify"]);
      expect(spy).not.toHaveBeenCalled();
    });
    it("does not warn when there is no positive-form clash", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["notDraft", "published"]);
      expect(spy).not.toHaveBeenCalled();
    });
  });
});

describe("Enum subtype resolved from the reflected column type", () => {
  class Book extends Base {
    static _tableName = "books";
    static {
      this.attribute("status", "decimal");
      this.enum("status", { proposed: 0, written: 1, published: 2 });
    }
  }

  it("delegates the enum subtype to the reflected decimal type, not the mapping shape", () => {
    const type = Book.typeForAttribute("status");
    expect(type).toBeInstanceOf(EnumType);
    expect((type as EnumType).subtype).toBe("decimal");
    expect((type as EnumType).subtypeType()).toBeInstanceOf(DecimalType);
  });

  it("serializes an enum label through the reflected decimal subtype", () => {
    expect(castEnumValue(Book, "status", "written")).toEqual(new DecimalType().serialize(1));
  });

  it("serializes through the reflected subtype on the query type-caster path too", () => {
    const caster = new MapCaster(Book);
    expect(caster.typeCastForDatabase("status", "written")).toEqual(new DecimalType().serialize(1));
  });
});

describe("Enum subtype resolved from a schema-reflected column type", () => {
  fixtures(["books"]);

  class NumericEnum extends Base {
    static _tableName = "numeric_data";
    static {
      this.enum("decimal_number", { low: 0, mid: 1, high: 2 });
    }
  }

  class DefaultOnlyNumericEnum extends Base {
    static _tableName = "numeric_data";
    static {
      this.attribute("decimal_number", { default: 0 });
      this.enum("decimal_number", { low: 0, mid: 1, high: 2 });
    }
  }

  class ExplicitNumericEnum extends Base {
    static _tableName = "numeric_data";
    static {
      this.attribute("decimal_number", "integer");
      this.enum("decimal_number", { low: 0, mid: 1, high: 2 });
    }
  }

  it("delegates the enum subtype to the reflected decimal column, not the integer mapping shape", () => {
    const type = enumTypeOf(NumericEnum, "decimal_number");
    expect(type).toBeInstanceOf(EnumType);
    expect(type!.subtype).toBe("decimal");
    expect(type!.subtypeType().type()).toBe("decimal");
  });

  it("serializes labels through the reflected decimal subtype on both read paths", () => {
    const subtype = enumTypeOf(NumericEnum, "decimal_number")!.subtypeType();
    expect(castEnumValue(NumericEnum, "decimal_number", "mid")).toEqual(subtype.serialize(1));
    const caster = new MapCaster(NumericEnum);
    expect(caster.typeCastForDatabase("decimal_number", "mid")).toEqual(subtype.serialize(1));
  });

  it("resolves the reflected subtype for a default-only attribute (no explicit type)", () => {
    const type = enumTypeOf(DefaultOnlyNumericEnum, "decimal_number");
    expect(type).toBeInstanceOf(EnumType);
    expect(type!.subtype).toBe("decimal");
    expect(type!.subtypeType().type()).toBe("decimal");
  });

  it("keeps an explicitly-typed enum's declared subtype over the reflected column", () => {
    const type = enumTypeOf(ExplicitNumericEnum, "decimal_number");
    expect(type).toBeInstanceOf(EnumType);
    expect(type!.subtype).toBe("integer");
    expect(type!.subtypeType().type()).toBe("integer");
  });
});

describe("Enum with an undeclared type raises on the serialize path", () => {
  fixtures(["books"]);

  class TypelessBook extends Book {
    static {
      this.enum("typeless_genre", { adventure: 0, comic: 1 });
    }
  }

  it("castEnumValue raises for an enum with no column and no explicit type", async () => {
    expect(() => castEnumValue(TypelessBook, "typeless_genre", "comic")).toThrow(
      /Undeclared attribute type for enum 'typeless_genre' in/,
    );
  });
});

describe("Enum acronym method name consistency", () => {
  let restoreInflections: () => void;

  beforeAll(() => {
    const inflect = Inflections.instance("en");
    const savedAcronyms = new Map(inflect.acronyms);
    const savedAcronymRegex = inflect.acronymRegex;
    const savedAcronymsCamelizeRegex = inflect.acronymsCamelizeRegex;
    const savedAcronymsUnderscoreRegex = inflect.acronymsUnderscoreRegex;
    inflect.acronym("API");
    inflect.acronym("VALID");
    const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
    expect(camelize("api_key", true)).toBe("APIKey");
    expect(cap(camelize("api_key", false))).toBe("ApiKey");
    expect(camelize("valid", true)).toBe("VALID");
    expect(cap(camelize("valid", false))).toBe("Valid");
    restoreInflections = () => {
      inflect.acronyms = savedAcronyms;
      inflect.acronymRegex = savedAcronymRegex;
      inflect.acronymsCamelizeRegex = savedAcronymsCamelizeRegex;
      inflect.acronymsUnderscoreRegex = savedAcronymsUnderscoreRegex;
    };
  });

  afterAll(() => {
    restoreInflections();
  });

  it("records the same predicate name the generator defines for acronym labels", () => {
    class AcroBook extends Base {
      static _tableName = "books";
      static {
        this.enum("status", { api_key: 0, plain: 1 });
      }
    }
    const proto = AcroBook.prototype as unknown as Record<string, unknown>;
    expect(typeof proto.isApiKey).toBe("function");
    expect(proto.isAPIKey).toBeUndefined();
    const recorded = (AcroBook as unknown as { _enumMethodsModuleNames: Set<string> })
      ._enumMethodsModuleNames;
    expect(recorded.has("isApiKey")).toBe(true);
    expect(recorded.has("isAPIKey")).toBe(false);
  });

  it("detects a conflict on the name it actually generates for an acronym label", () => {
    expect(() => {
      class ValidEnum extends Base {
        static _tableName = "books";
        static {
          this.enum("status", { valid: 0, plain: 1 });
        }
      }
    }).toThrow(/generate a instance method "isValid", which is already defined/);
  });
});

describe("Enum inherited from an abstract parent (Lion < Cat)", () => {
  const { lions } = fixtures(["lions"]);

  it("answers the inherited predicate on the concrete subclass", () => {
    expect(() => Lion._defaultAttributes()).not.toThrow();

    const lion = new Lion({ gender: "female" });
    expect(lion.isFemale()).toBe(true);
    expect(lion.isMale()).toBe(false);
  });

  it("resolves the inherited enum on a row read back from the table", async () => {
    const lion = new Lion({ gender: "female" });
    await lion.save();

    const found = await Lion.find(lion.id);
    expect(found.isFemale()).toBe(true);
    expect(found.gender).toBe("female");
  });

  it("applies Cat's default scope to Lion's queries", async () => {
    const ids = await Lion.all().pluck("id");
    expect(ids).toEqual([lions("meat_eating_lion").id]);
  });

  it("builds a new Lion without routing the parent's default scope through a tableless class", () => {
    expect(() => new Lion()).not.toThrow();
  });
});
