/**
 * trails-specific invariants for the internal enum validators — these guard
 * behavior with no Rails enum_test.rb counterpart (the private helpers
 * `assertValidEnumDefinitionValues`, `assertValidEnumOptions`,
 * `detectNegativeEnumConditionsBang`, and the `setEnumWarn` warning hook).
 */
import { describe, it, expect, afterEach, beforeAll, vi } from "vitest";
import {
  assertValidEnumDefinitionValues,
  assertValidEnumOptions,
  castEnumValue,
  detectNegativeEnumConditionsBang,
  enumTypeOf,
  EnumType,
  setEnumWarn,
} from "./enum.js";
import { ArgumentError, DecimalType } from "@blazetrails/activemodel";
import { Base } from "./index.js";
import { Map as MapCaster } from "./type-caster/map.js";
import { fixtures } from "./test-helpers/fixtures.js";
import { rebuildCanonicalTables } from "./test-helpers/canonical-schema.js";

describe("Enum name conflict detection", () => {
  // Rails' `detect_enum_conflict!(name, name)` uses `dangerous_attribute_method?`,
  // which only flags names in `Base.instance_methods` — NOT user methods on the
  // model or an intermediate ancestor. An enum named after such a user method
  // must not raise (regression guard for the curated-set gate replacing the old
  // prototype-chain walk).
  it("does not treat a user method on an ancestor class as a conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      status() {
        return "user method";
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  // Rails' second instance-method branch (`method_defined_within?(method_name,
  // _enum_methods_module)`, enum.rb:383-384) raises when a *different* enum on
  // the same class already generated a value method with this name.
  it("raises when a second enum reuses a value method defined by another enum", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("status", { active: 0, archived: 1 });
          // `active` also maps here → isActive/activeBang collide with status's.
          this.enum("state", { active: 0, closed: 1 });
        }
      }
    }).toThrow(/already defined by another enum/);
  });

  // Rails runs the `?`/`!` `detect_enum_conflict!` calls *only* inside
  // `if instance_methods` (enum.rb:303-311), so a second enum that opts out of
  // instance methods can reuse a value-method name a prior enum generated — no
  // predicate/bang is defined, so there is nothing to conflict with.
  it("does not raise when a second enum reuses a value method but disables instance methods", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.attribute("status", "integer");
          this.attribute("state", "integer");
          this.enum("status", { active: 0, archived: 1 });
          this.enum("state", { active: 0, closed: 1 }, { instanceMethods: false });
        }
      }
      new Klass();
    }).not.toThrow();
  });

  // The *cross-class* counterpart — a subclass enum reusing a value method a
  // parent enum generated — is permitted by Rails (`_enum_methods_module` is a
  // per-class, non-inherited class-instance variable, enum.rb:326-332). The
  // `_enumMethodsModuleNames` set is per-class (fresh, not inherited); the scope
  // pre-check now consults `dangerous_class_method?` (walk from `Base`) rather
  // than the over-broad `fullName in this`, so a scope inherited from the parent
  // enum no longer false-positives.
  it("does not treat a value method generated by a parent enum as a conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      static {
        this.enum("status", { active: 0, archived: 1 });
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          // `active` reuses the value method the parent enum generated.
          this.enum("state", { active: 0, closed: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  // Rails' `detect_enum_conflict!(name, name.pluralize, true)` uses
  // `dangerous_class_method?` — a fixed list plus methods `Base` itself defines,
  // never a user static on the model or an intermediate ancestor. An enum whose
  // pluralized mapping accessor name matches such a user static must not raise.
  it("does not treat a user class method on an ancestor as a plural-accessor conflict", () => {
    class Parent extends Base {
      static _tableName = "books";
      static statuses() {
        return "user class method";
      }
    }
    expect(() => {
      class Child extends Parent {
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Child();
    }).not.toThrow();
  });

  // The reserved-name guard must still fire: `enum :column` generates a
  // `columns` class method, which `Base` itself defines (dangerous).
  it("raises for an enum name whose plural accessor is a framework class method", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("column", { a: 0, b: 1 });
        }
      }
      new Klass();
    }).toThrow(/enum named "column"/);
  });

  // Rails' `dangerous_class_method?` (attribute_methods.rb:201-213) checks
  // `Base.respond_to?` — the framework class, a FIXED reference point, never the
  // receiving subclass. So a bespoke static on the model whose name collides
  // with the enum's pluralized accessor must NOT raise (Base doesn't know about
  // it; the enum accessor simply overwrites it). Regression guard for the
  // class-method branch checking `Base`, not `this`.
  it("does not treat a bespoke subclass static as a class-method conflict", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static statuses() {
          return "bespoke";
        }
        static {
          this.enum("status", { proposed: 0, written: 1 });
        }
      }
      new Klass();
    }).not.toThrow();
  });

  // Rails guards `name=` too (`detect_enum_conflict!(name, "#{name}=")`), so an
  // enum named after a framework writer conflicts on the setter.
  it("raises for an enum name whose reader is a framework method", () => {
    expect(() => {
      class Klass extends Base {
        static _tableName = "books";
        static {
          this.enum("attributes", { a: 0, b: 1 });
        }
      }
      new Klass();
    }).toThrow(/enum named "attributes"/);
  });
});

describe("Enum private validators", () => {
  afterEach(() => vi.restoreAllMocks());

  describe("assertValidEnumDefinitionValues", () => {
    it("rejects empty array with ArgumentError", () => {
      expect(() => assertValidEnumDefinitionValues([])).toThrow(ArgumentError);
    });
    it("rejects array with non-string entries", () => {
      expect(() => assertValidEnumDefinitionValues([1, 2])).toThrow(ArgumentError);
    });
    it("accepts array with string entries", () => {
      const out = assertValidEnumDefinitionValues(["draft", "published"]);
      expect(out).toEqual(["draft", "published"]);
    });
    it("accepts array with symbol entries", () => {
      const sym1 = Symbol("draft");
      const sym2 = Symbol("published");
      const out = assertValidEnumDefinitionValues([sym1, sym2]);
      expect(out).toEqual([sym1, sym2]);
    });
    it("rejects array with blank name", () => {
      expect(() => assertValidEnumDefinitionValues(["a", ""])).toThrow(/blank name/);
    });
    it("rejects array with whitespace-only name", () => {
      expect(() => assertValidEnumDefinitionValues(["a", "   "])).toThrow(/blank name/);
    });
    it("rejects hash with whitespace-only key", () => {
      expect(() => assertValidEnumDefinitionValues({ "   ": 1 })).toThrow(/blank name/);
    });
    it("rejects array with blank-description Symbol", () => {
      expect(() => assertValidEnumDefinitionValues([Symbol("")])).toThrow(/blank name/);
      expect(() => assertValidEnumDefinitionValues([Symbol("   ")])).toThrow(/blank name/);
    });
    it("rejects non-plain-object values (Map/Date/class instances)", () => {
      expect(() => assertValidEnumDefinitionValues(new Map())).toThrow(
        /non-empty hash or an array/,
      );
      expect(() => assertValidEnumDefinitionValues(new Date())).toThrow(
        /non-empty hash or an array/,
      );
      class Foo {}
      expect(() => assertValidEnumDefinitionValues(new Foo())).toThrow(
        /non-empty hash or an array/,
      );
    });
    it("rejects empty hash", () => {
      expect(() => assertValidEnumDefinitionValues({})).toThrow(ArgumentError);
    });
    it("accepts hash with boolean and null values", () => {
      const out = assertValidEnumDefinitionValues({ a: true, b: null, c: 1 });
      expect(out).toEqual({ a: true, b: null, c: 1 });
    });
    it("rejects hash with non-primitive value", () => {
      expect(() => assertValidEnumDefinitionValues({ a: { x: 1 } })).toThrow(ArgumentError);
    });
    it("accepts hash with symbol keys (Reflect.ownKeys)", () => {
      const out = assertValidEnumDefinitionValues({ [Symbol("draft")]: 0 });
      expect(out).toBeDefined();
    });
    it("rejects hash with blank-description symbol key", () => {
      expect(() => assertValidEnumDefinitionValues({ [Symbol("")]: 0 })).toThrow(/blank name/);
    });
    it("rejects hash with NaN or Infinity number values", () => {
      expect(() => assertValidEnumDefinitionValues({ a: NaN })).toThrow(/finite numbers/);
      expect(() => assertValidEnumDefinitionValues({ a: Infinity })).toThrow(/finite numbers/);
    });
  });

  describe("assertValidEnumOptions", () => {
    it("rejects underscore-prefixed option keys with ArgumentError (enum.rb:361-365)", () => {
      // Rails: options.keys & %i[_prefix _suffix _scopes _default _instance_methods]
      expect(() => assertValidEnumOptions({ _prefix: "x" })).toThrow(ArgumentError);
      expect(() => assertValidEnumOptions({ _suffix: "x" })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _scopes: true })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _default: "active" })).toThrow(/invalid option/);
      expect(() => assertValidEnumOptions({ _instance_methods: false })).toThrow(/invalid option/);
      // _validate is NOT in Rails' invalid list — valid options include :validate
      expect(() => assertValidEnumOptions({ _validate: true })).not.toThrow();
    });
    it("error message uses Ruby symbol inspect format (:key)", () => {
      expect(() => assertValidEnumOptions({ _prefix: "x" })).toThrow(/:_prefix/);
    });
    it("accepts valid options without throwing", () => {
      expect(() => assertValidEnumOptions({ prefix: "x", validate: true })).not.toThrow();
    });
    it("treats arrays as not-an-options-hash", () => {
      expect(() => assertValidEnumOptions([])).not.toThrow();
    });
    it("treats Map / Date / class instances as not-an-options-hash", () => {
      expect(() => assertValidEnumOptions(new Map())).not.toThrow();
      expect(() => assertValidEnumOptions(new Date())).not.toThrow();
      class Foo {}
      expect(() => assertValidEnumOptions(new Foo())).not.toThrow();
    });
  });

  describe("detectNegativeEnumConditionsBang", () => {
    it("warns when notDraft conflicts with draft (camelCase prefix)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["draft", "notDraft"]);
      expect(spy).toHaveBeenCalledWith(
        expect.stringMatching(/conflicts with auto-generated negative scope 'notDraft'/),
      );
    });
    it("warns when not_draft conflicts with draft (snake_case prefix)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["draft", "not_draft"]);
      expect(spy).toHaveBeenCalledWith(expect.stringMatching(/'not_draft'/));
    });
    it("routes warnings through setEnumWarn instead of console.warn", () => {
      const calls: string[] = [];
      setEnumWarn((msg) => calls.push(msg));
      try {
        const consoleSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
        detectNegativeEnumConditionsBang(["draft", "notDraft"]);
        expect(calls.length).toBe(1);
        expect(consoleSpy).not.toHaveBeenCalled();
      } finally {
        setEnumWarn((msg) => console.warn(msg));
      }
    });
    it("does not warn for unrelated identifiers starting with 'not' (notebook, notify)", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["ebook", "notebook", "ify", "notify"]);
      expect(spy).not.toHaveBeenCalled();
    });
    it("does not warn when there is no positive-form clash", () => {
      const spy = vi.spyOn(console, "warn").mockImplementation(() => {});
      detectNegativeEnumConditionsBang(["notDraft", "published"]);
      expect(spy).not.toHaveBeenCalled();
    });
  });
});

// Rails resolves the enum subtype lazily inside `decorate_attributes` from the
// column's real `Type::Value` (enum.rb:239-246), NOT from the mapping's value
// shapes. When a column type differs from what the mapping implies — here an
// integer-valued enum on a `decimal`-typed attribute — the EnumType must
// delegate to the reflected column type, not the integer that eager
// mapping-shape inference would have guessed. No canonical model exercises
// this (all canonical enum columns match their mapping shapes), so this is a
// trails-only regression guard for the reflected-type resolution.
describe("Enum subtype resolved from the reflected column type", () => {
  class Book extends Base {
    static _tableName = "books";
    static {
      this.attribute("status", "decimal");
      this.enum("status", { proposed: 0, written: 1, published: 2 });
    }
  }

  it("delegates the enum subtype to the reflected decimal type, not the mapping shape", () => {
    const type = Book.typeForAttribute("status");
    expect(type).toBeInstanceOf(EnumType);
    // Eager mapping-shape inference (all-numbers) would have picked "integer";
    // resolving from the reflected column type yields the real "decimal".
    expect((type as EnumType).subtype).toBe("decimal");
    expect((type as EnumType).subtypeType()).toBeInstanceOf(DecimalType);
  });

  it("serializes an enum label through the reflected decimal subtype", () => {
    // castEnumValue serializes the label to its stored value via the single
    // registered EnumType, coercing through the decimal subtype exactly as the
    // reflected DecimalType would.
    expect(castEnumValue(Book, "status", "written")).toEqual(new DecimalType().serialize(1));
  });

  it("serializes through the reflected subtype on the query type-caster path too", () => {
    // The predicate builder's TypeCaster::Map serialize path must resolve the
    // same reflected EnumType (not the pre-reflection one), so where(status:)
    // round-trips the label through the decimal subtype.
    const caster = new MapCaster(Book);
    expect(caster.typeCastForDatabase("status", "written")).toEqual(new DecimalType().serialize(1));
  });
});

// The harder case the explicit-`attribute(...)` block above does NOT cover: an
// enum whose subtype comes purely from SCHEMA REFLECTION. `numeric_data`'s
// `decimal_number` is a real `decimal` column, so an integer-valued enum on it
// must delegate to the reflected `DecimalType`, even though (a) mapping-shape
// inference would guess `integer` and (b) reflection skips the userProvided
// enum def, leaving `_attributeDefinitions` carrying the pre-reflection integer
// EnumType — so the reflected subtype only lives in the replayed AttributeSet.
describe("Enum subtype resolved from a schema-reflected column type", () => {
  fixtures(["books"]);

  class NumericEnum extends Base {
    static _tableName = "numeric_data";
    static {
      this.enum("decimal_number", { low: 0, mid: 1, high: 2 });
    }
  }

  beforeAll(async () => {
    await rebuildCanonicalTables(Base.connection, ["numeric_data"]);
    await NumericEnum.loadSchema();
  });

  it("delegates the enum subtype to the reflected decimal column, not the integer mapping shape", () => {
    const type = enumTypeOf(NumericEnum, "decimal_number");
    expect(type).toBeInstanceOf(EnumType);
    expect(type!.subtype).toBe("decimal");
    expect(type!.subtypeType()).toBeInstanceOf(DecimalType);
  });

  it("serializes labels through the reflected decimal subtype on both read paths", () => {
    // castEnumValue (predicate/read) and TypeCaster::Map (query) must both
    // resolve the reflected EnumType, coercing the mapped value through decimal.
    expect(castEnumValue(NumericEnum, "decimal_number", "mid")).toEqual(
      new DecimalType().serialize(1),
    );
    const caster = new MapCaster(NumericEnum);
    expect(caster.typeCastForDatabase("decimal_number", "mid")).toEqual(
      new DecimalType().serialize(1),
    );
  });
});
