/**
 * Mirrors: activerecord/test/cases/errors_test.rb
 *
 * Faithful port of Rails' ErrorsTest — one test, no database, no fixtures,
 * no inline `class extends Base`. Enumerates every implemented exported
 * ActiveRecordError subclass and asserts each can be constructed with no
 * arguments.
 *
 * AmbiguousSourceReflectionForThroughAssociation is excluded (same exclusion
 * as Rails). In Rails the no-arg constructor raises ArgumentError (wrong number
 * of arguments); in TS it raises TypeError (sources.join is not a function).
 * Different mechanism, same observable outcome: construction fails.
 */
import { describe, it } from "vitest";
import {
  SubclassNotFound,
  AssociationTypeMismatch,
  SerializationTypeMismatch,
  AdapterNotSpecified,
  AdapterNotFound,
  AdapterError,
  ConnectionNotEstablished,
  ConnectionTimeoutError,
  ExclusiveConnectionTimeoutError,
  ConnectionNotDefined,
  DatabaseConnectionError,
  NotImplementedError,
  ReadOnlyError,
  RecordNotFound,
  RecordNotSaved,
  RecordNotDestroyed,
  SoleRecordExceeded,
  StatementInvalid,
  QueryAborted,
  ConnectionFailed,
  TransactionRollbackError,
  SerializationFailure,
  Deadlocked,
  LockWaitTimeout,
  StatementTimeout,
  AdapterTimeout,
  QueryCanceled,
  WrappedDatabaseException,
  RecordNotUnique,
  InvalidForeignKey,
  MismatchedForeignKey,
  NotNullViolation,
  ValueTooLong,
  PreparedStatementInvalid,
  PreparedStatementCacheExpired,
  NoDatabaseError,
  DatabaseVersionError,
  RangeError,
  DatabaseAlreadyExists,
  StaleObjectError,
  ConfigurationError,
  ReadOnlyRecord,
  StrictLoadingViolationError,
  Rollback,
  DangerousAttributeError,
  AttributeAssignmentError,
  TransactionIsolationError,
  UnmodifiableRelation,
  IrreversibleOrderError,
  UnknownAttributeError,
  SQLWarning,
  UnknownAttributeReference,
  UnknownPrimaryKey,
  MultiparameterAssignmentErrors,
  TableNotSpecified,
  AsynchronousQueryInsideTransactionError,
  RecordInvalid,
  ReadonlyAttributeError,
  AssociationNotFoundError,
  InverseOfAssociationNotFoundError,
  InverseOfAssociationRecursiveError,
  HasManyThroughAssociationNotFoundError,
  HasManyThroughAssociationPolymorphicSourceError,
  HasManyThroughAssociationPolymorphicThroughError,
  HasManyThroughAssociationPointlessSourceTypeError,
  HasOneThroughCantAssociateThroughCollection,
  HasOneAssociationPolymorphicThroughError,
  HasManyThroughSourceAssociationNotFoundError,
  HasManyThroughOrderError,
  ThroughCantAssociateThroughHasOneOrManyReflection,
  HasManyThroughCantAssociateThroughHasOneOrManyReflection,
  HasOneThroughCantAssociateThroughHasOneOrManyReflection,
  CompositePrimaryKeyMismatchError,
  ThroughNestedAssociationsAreReadonly,
  HasManyThroughNestedAssociationsAreReadonly,
  HasOneThroughNestedAssociationsAreReadonly,
  EagerLoadPolymorphicError,
  DeleteRestrictionError,
  TooManyRecords,
} from "./index.js";

describe("ErrorsTest", () => {
  it("can be instantiated with no args", () => {
    const errorKlasses = [
      SubclassNotFound,
      AssociationTypeMismatch,
      SerializationTypeMismatch,
      AdapterNotSpecified,
      AdapterNotFound,
      AdapterError,
      ConnectionNotEstablished,
      ConnectionTimeoutError,
      ExclusiveConnectionTimeoutError,
      ConnectionNotDefined,
      DatabaseConnectionError,
      NotImplementedError,
      ReadOnlyError,
      RecordNotFound,
      RecordNotSaved,
      RecordNotDestroyed,
      SoleRecordExceeded,
      StatementInvalid,
      QueryAborted,
      ConnectionFailed,
      TransactionRollbackError,
      SerializationFailure,
      Deadlocked,
      LockWaitTimeout,
      StatementTimeout,
      AdapterTimeout,
      QueryCanceled,
      WrappedDatabaseException,
      RecordNotUnique,
      InvalidForeignKey,
      MismatchedForeignKey,
      NotNullViolation,
      ValueTooLong,
      PreparedStatementInvalid,
      PreparedStatementCacheExpired,
      NoDatabaseError,
      DatabaseVersionError,
      RangeError,
      TableNotSpecified,
      AsynchronousQueryInsideTransactionError,
      DatabaseAlreadyExists,
      StaleObjectError,
      ConfigurationError,
      ReadOnlyRecord,
      StrictLoadingViolationError,
      Rollback,
      DangerousAttributeError,
      AttributeAssignmentError,
      TransactionIsolationError,
      UnmodifiableRelation,
      IrreversibleOrderError,
      UnknownAttributeError,
      SQLWarning,
      UnknownAttributeReference,
      UnknownPrimaryKey,
      MultiparameterAssignmentErrors,
      RecordInvalid,
      ReadonlyAttributeError,
      AssociationNotFoundError,
      InverseOfAssociationNotFoundError,
      InverseOfAssociationRecursiveError,
      HasManyThroughAssociationNotFoundError,
      HasManyThroughAssociationPolymorphicSourceError,
      HasManyThroughAssociationPolymorphicThroughError,
      HasManyThroughAssociationPointlessSourceTypeError,
      HasOneThroughCantAssociateThroughCollection,
      HasOneAssociationPolymorphicThroughError,
      HasManyThroughSourceAssociationNotFoundError,
      HasManyThroughOrderError,
      ThroughCantAssociateThroughHasOneOrManyReflection,
      HasManyThroughCantAssociateThroughHasOneOrManyReflection,
      HasOneThroughCantAssociateThroughHasOneOrManyReflection,
      CompositePrimaryKeyMismatchError,
      ThroughNestedAssociationsAreReadonly,
      HasManyThroughNestedAssociationsAreReadonly,
      HasOneThroughNestedAssociationsAreReadonly,
      EagerLoadPolymorphicError,
      DeleteRestrictionError,
      TooManyRecords,
    ];
    for (const errorKlass of errorKlasses) {
      try {
        new (errorKlass as any)();
      } catch {
        throw new Error(
          `Instance of ${(errorKlass as any).name} can't be initialized with no arguments`,
        );
      }
    }
  });
});
