/**
 * Mirrors: activerecord/test/cases/errors_test.rb
 *
 * Faithful port of Rails' ErrorsTest — one test, no database, no fixtures,
 * no inline `class extends Base`. Enumerates every exported ActiveRecordError
 * subclass and asserts each can be constructed with no arguments.
 *
 * AmbiguousSourceReflectionForThroughAssociation is excluded because its
 * constructor calls sources.join() which throws when sources is undefined —
 * matching Rails' exclusion of the same class for the same reason.
 */
import { describe, it } from "vitest";
import {
  ActiveRecordError,
  SubclassNotFound,
  AssociationTypeMismatch,
  SerializationTypeMismatch,
  AdapterNotSpecified,
  AdapterNotFound,
  AdapterError,
  ConnectionNotEstablished,
  ConnectionTimeoutError,
  ExclusiveConnectionTimeoutError,
  ConnectionNotDefined,
  DatabaseConnectionError,
  NotImplementedError,
  ReadOnlyError,
  RecordNotFound,
  RecordNotSaved,
  RecordNotDestroyed,
  SoleRecordExceeded,
  StatementInvalid,
  QueryAborted,
  ConnectionFailed,
  TransactionRollbackError,
  SerializationFailure,
  Deadlocked,
  LockWaitTimeout,
  StatementTimeout,
  AdapterTimeout,
  QueryCanceled,
  WrappedDatabaseException,
  RecordNotUnique,
  InvalidForeignKey,
  MismatchedForeignKey,
  NotNullViolation,
  ValueTooLong,
  PreparedStatementInvalid,
  PreparedStatementCacheExpired,
  NoDatabaseError,
  DatabaseVersionError,
  RangeError,
  DatabaseAlreadyExists,
  StaleObjectError,
  ConfigurationError,
  ReadOnlyRecord,
  StrictLoadingViolationError,
  Rollback,
  DangerousAttributeError,
  AttributeAssignmentError,
  TransactionIsolationError,
  UnmodifiableRelation,
  IrreversibleOrderError,
  UnknownAttributeError,
  SQLWarning,
  UnknownAttributeReference,
  UnknownPrimaryKey,
  MultiparameterAssignmentErrors,
  RecordInvalid,
  ReadonlyAttributeError,
  AssociationNotFoundError,
  InverseOfAssociationNotFoundError,
  InverseOfAssociationRecursiveError,
  HasManyThroughAssociationNotFoundError,
  HasManyThroughAssociationPolymorphicSourceError,
  HasManyThroughAssociationPolymorphicThroughError,
  HasManyThroughAssociationPointlessSourceTypeError,
  HasOneThroughCantAssociateThroughCollection,
  HasOneAssociationPolymorphicThroughError,
  HasManyThroughSourceAssociationNotFoundError,
  HasManyThroughOrderError,
  ThroughCantAssociateThroughHasOneOrManyReflection,
  HasManyThroughCantAssociateThroughHasOneOrManyReflection,
  HasOneThroughCantAssociateThroughHasOneOrManyReflection,
  CompositePrimaryKeyMismatchError,
  AmbiguousSourceReflectionForThroughAssociation,
  ThroughNestedAssociationsAreReadonly,
  HasManyThroughNestedAssociationsAreReadonly,
  HasOneThroughNestedAssociationsAreReadonly,
  EagerLoadPolymorphicError,
  DeleteRestrictionError,
  TooManyRecords,
} from "./index.js";

describe("ErrorsTest", () => {
  it("can be instantiated with no args", () => {
    const base = ActiveRecordError;
    void base;
    const errorKlasses = [
      SubclassNotFound,
      AssociationTypeMismatch,
      SerializationTypeMismatch,
      AdapterNotSpecified,
      AdapterNotFound,
      AdapterError,
      ConnectionNotEstablished,
      ConnectionTimeoutError,
      ExclusiveConnectionTimeoutError,
      ConnectionNotDefined,
      DatabaseConnectionError,
      NotImplementedError,
      ReadOnlyError,
      RecordNotFound,
      RecordNotSaved,
      RecordNotDestroyed,
      SoleRecordExceeded,
      StatementInvalid,
      QueryAborted,
      ConnectionFailed,
      TransactionRollbackError,
      SerializationFailure,
      Deadlocked,
      LockWaitTimeout,
      StatementTimeout,
      AdapterTimeout,
      QueryCanceled,
      WrappedDatabaseException,
      RecordNotUnique,
      InvalidForeignKey,
      MismatchedForeignKey,
      NotNullViolation,
      ValueTooLong,
      PreparedStatementInvalid,
      PreparedStatementCacheExpired,
      NoDatabaseError,
      DatabaseVersionError,
      RangeError,
      DatabaseAlreadyExists,
      StaleObjectError,
      ConfigurationError,
      ReadOnlyRecord,
      StrictLoadingViolationError,
      Rollback,
      DangerousAttributeError,
      AttributeAssignmentError,
      TransactionIsolationError,
      UnmodifiableRelation,
      IrreversibleOrderError,
      UnknownAttributeError,
      SQLWarning,
      UnknownAttributeReference,
      UnknownPrimaryKey,
      MultiparameterAssignmentErrors,
      RecordInvalid,
      ReadonlyAttributeError,
      AssociationNotFoundError,
      InverseOfAssociationNotFoundError,
      InverseOfAssociationRecursiveError,
      HasManyThroughAssociationNotFoundError,
      HasManyThroughAssociationPolymorphicSourceError,
      HasManyThroughAssociationPolymorphicThroughError,
      HasManyThroughAssociationPointlessSourceTypeError,
      HasOneThroughCantAssociateThroughCollection,
      HasOneAssociationPolymorphicThroughError,
      HasManyThroughSourceAssociationNotFoundError,
      HasManyThroughOrderError,
      ThroughCantAssociateThroughHasOneOrManyReflection,
      HasManyThroughCantAssociateThroughHasOneOrManyReflection,
      HasOneThroughCantAssociateThroughHasOneOrManyReflection,
      CompositePrimaryKeyMismatchError,
      AmbiguousSourceReflectionForThroughAssociation,
      ThroughNestedAssociationsAreReadonly,
      HasManyThroughNestedAssociationsAreReadonly,
      HasOneThroughNestedAssociationsAreReadonly,
      EagerLoadPolymorphicError,
      DeleteRestrictionError,
      TooManyRecords,
    ];
    const excluded = [AmbiguousSourceReflectionForThroughAssociation];
    for (const errorKlass of errorKlasses) {
      if (excluded.includes(errorKlass as any)) continue;
      try {
        new (errorKlass as any)();
      } catch {
        throw new Error(
          `Instance of ${(errorKlass as any).name} can't be initialized with no arguments`,
        );
      }
    }
  });
});
