import { describe, it, expect, vi, afterEach } from "vitest";
import { Temporal } from "@blazetrails/date";
import { generateModels, unqualify } from "./model-codegen.js";
import type { IntrospectedTable } from "./model-codegen.js";
import { ForeignKeyDefinition } from "./connection-adapters/abstract/schema-definitions.js";
import { Base } from "./base.js";

const NOW = Temporal.Instant.from("2026-04-24T14:23:05.000Z");

function table(
  name: string,
  opts: {
    primaryKey?: string | string[] | null;
    foreignKeys?: ForeignKeyDefinition[];
    columns?: { name: string; type: string }[];
  } = {},
): IntrospectedTable {
  const primaryKey: string | string[] | null =
    "primaryKey" in opts && opts.primaryKey !== undefined ? opts.primaryKey : "id";
  return {
    name,
    primaryKey,
    foreignKeys: opts.foreignKeys ?? [],
    columns: opts.columns ?? [],
  };
}

function fk(
  fromTable: string,
  toTable: string,
  column: string,
  primaryKey = "id",
  name?: string,
): ForeignKeyDefinition {
  return new ForeignKeyDefinition(fromTable, toTable, {
    column,
    primaryKey,
    name: name ?? `fk_${fromTable}_${column}`,
  });
}

describe("generateModels", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("emits only the header + imports when there are no tables", () => {
    const out = generateModels([], { sourceHint: "sqlite:empty.db", now: NOW });
    expect(out).toContain("GENERATED by trails-models-dump from sqlite:empty.db");
    expect(out).toContain("0 models, 0 associations from 0 foreign keys");
    expect(out).toContain('import { Base } from "@blazetrails/activerecord";');
    expect(out).not.toMatch(/export class/);
  });

  it("emits one class with no _tableName and no _primaryKey for a plain table with default PK", () => {
    const out = generateModels([table("books")], { noHeader: true, now: NOW });
    expect(out).toContain("export class Book extends Base {");
    expect(out).toContain("static {}");
    expect(out).not.toMatch(/_tableName/);
    expect(out).not.toMatch(/_primaryKey/);
  });

  it("emits this._primaryKey for non-default single-column PK", () => {
    const out = generateModels([table("users", { primaryKey: "uuid" })], {
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain('this._primaryKey = "uuid";');
  });

  it("emits belongs_to and has_many without options for convention-matching FK", () => {
    const tables = [
      table("authors"),
      table("books", { foreignKeys: [fk("books", "authors", "author_id")] }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author");');
    expect(out).toContain('this.hasMany("books");');
    expect(out).not.toMatch(/foreignKey:/);
    expect(out).not.toMatch(/className:/);
  });

  it("emits foreignKey option when FK column doesn't match <assoc>_id convention", () => {
    const tables = [
      table("authors"),
      table("books", { foreignKeys: [fk("books", "authors", "written_by")] }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author", { foreignKey: "written_by" });');
    expect(out).toContain('this.hasMany("books", { foreignKey: "written_by" });');
  });

  it("handles self-referential FK without crashing", () => {
    const tables = [table("users", { foreignKeys: [fk("users", "users", "parent_id")] })];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("parent", { className: "User" });');
    expect(out).toContain('this.hasMany("users", { foreignKey: "parent_id" });');
  });

  it("emits TODO comment for composite FK, no association", () => {
    const tables = [
      table("memberships", {
        foreignKeys: [
          fk("memberships", "accounts", "tenant_id,account_id", "tenant_id,id", "fk_composite"),
        ],
      }),
      table("accounts"),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain("// TODO composite FK fk_composite");
    expect(out).toContain("tenant_id,account_id -> accounts.tenant_id,id");
    expect(out).not.toMatch(/this\.belongsTo\("tenant_id,account_id"/);
  });

  it("emits array-valued _primaryKey for composite PK", () => {
    const out = generateModels([table("access_logs", { primaryKey: ["tenant_id", "id"] })], {
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain('this._primaryKey = ["tenant_id","id"];');
  });

  it("skips tables with an empty-array primary key (introspection's no-PK shape)", () => {
    const out = generateModels(
      [table("real_table"), table("v_users_summary", { primaryKey: [] })],
      { sourceHint: "sqlite:app.db", now: NOW },
    );
    expect(out).toContain("SKIPPED v_users_summary: no primary key");
    expect(out).toContain("export class RealTable extends Base {");
    expect(out).not.toMatch(/export class VUsersSummary/);
  });

  it("skips tables with null primary key and logs them in the header tally", () => {
    const out = generateModels(
      [table("real_table"), table("v_users_summary", { primaryKey: null })],
      { sourceHint: "sqlite:app.db", now: NOW },
    );
    expect(out).toContain("SKIPPED v_users_summary: no primary key");
    expect(out).toContain("export class RealTable extends Base {");
    expect(out).not.toMatch(/export class VUsersSummary/);
  });

  it("skips the default bookkeeping tables (schema_migrations / ar_internal_metadata)", () => {
    const out = generateModels(
      [table("books"), table("schema_migrations"), table("ar_internal_metadata")],
      { noHeader: true, now: NOW },
    );
    expect(out).toContain("export class Book extends Base {");
    expect(out).not.toMatch(/export class SchemaMigration/);
    expect(out).not.toMatch(/export class ArInternalMetadata/);
  });

  it("still ignores bookkeeping tables when their names are reconfigured on Base", () => {
    vi.spyOn(Base, "schemaMigrationsTableName", "get").mockReturnValue("my_migrations");
    vi.spyOn(Base, "internalMetadataTableName", "get").mockReturnValue("my_metadata");
    vi.spyOn(Base, "tableNamePrefix", "get").mockReturnValue("app_");
    vi.spyOn(Base, "tableNameSuffix", "get").mockReturnValue("_v2");

    const out = generateModels(
      [table("books"), table("app_my_migrations_v2"), table("app_my_metadata_v2")],
      { noHeader: true, now: NOW },
    );
    expect(out).toContain("export class Book extends Base {");
    expect(out).not.toMatch(/export class AppMyMigrations/);
    expect(out).not.toMatch(/export class AppMyMetadata/);
    const bare = generateModels([table("schema_migrations")], { noHeader: true, now: NOW });
    expect(bare).toContain("export class SchemaMigration extends Base {");
  });

  it("skips _tableName for irregular plural where round-trip works", () => {
    const out = generateModels([table("people")], { noHeader: true, now: NOW });
    expect(out).toContain("export class Person extends Base {");
    expect(out).not.toMatch(/_tableName/);
  });

  it("emits _tableName when round-trip would mis-pluralize (quirky plural)", () => {
    const out = generateModels([table("status")], { noHeader: true, now: NOW });
    expect(out).toContain('this._tableName = "status";');
  });

  it("strips prefix before classify but preserves full _tableName", () => {
    const out = generateModels([table("blog_posts")], {
      stripPrefix: "blog_",
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain("export class Post extends Base {");
    expect(out).toContain('this._tableName = "blog_posts";');
  });

  it("strip-prefix does not change belongsTo association names (only class names)", () => {
    const tables = [
      table("blog_posts"),
      table("comments", {
        foreignKeys: [fk("comments", "blog_posts", "written_by")],
      }),
    ];
    const out = generateModels(tables, {
      stripPrefix: "blog_",
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain("export class Post extends Base {");
    expect(out).toContain(
      'this.belongsTo("blog_post", { className: "Post", foreignKey: "written_by" });',
    );
  });

  it("strips suffix before classify but preserves full _tableName", () => {
    const out = generateModels([table("posts_archive")], {
      stripSuffix: "_archive",
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain("export class Post extends Base {");
    expect(out).toContain('this._tableName = "posts_archive";');
  });

  it("sorts classes alphabetically and hasMany names alphabetically within a class", () => {
    const tables = [
      table("accounts"),
      table("posts", { foreignKeys: [fk("posts", "accounts", "account_id")] }),
      table("comments", { foreignKeys: [fk("comments", "accounts", "account_id")] }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    const accountIdx = out.indexOf("class Account ");
    const commentIdx = out.indexOf("class Comment ");
    const postIdx = out.indexOf("class Post ");
    expect(accountIdx).toBeGreaterThanOrEqual(0);
    expect(commentIdx).toBeGreaterThan(accountIdx);
    expect(postIdx).toBeGreaterThan(commentIdx);
    const commentsHm = out.indexOf('this.hasMany("comments")');
    const postsHm = out.indexOf('this.hasMany("posts")');
    expect(commentsHm).toBeGreaterThan(0);
    expect(postsHm).toBeGreaterThan(commentsHm);
  });

  it("is deterministic — same input yields identical output", () => {
    const tables = [
      table("authors"),
      table("books", { foreignKeys: [fk("books", "authors", "author_id")] }),
    ];
    const a = generateModels(tables, { noHeader: true, now: NOW });
    const b = generateModels(tables, { noHeader: true, now: NOW });
    expect(a).toBe(b);
  });

  it("emits className option when --strip-prefix makes association name mismatch class name", () => {
    const tables = [
      table("blog_posts"),
      table("comments", {
        foreignKeys: [fk("comments", "blog_posts", "blog_post_id")],
      }),
    ];
    const out = generateModels(tables, {
      stripPrefix: "blog_",
      noHeader: true,
      now: NOW,
    });
    expect(out).toContain('this.belongsTo("blog_post", { className: "Post" });');
    expect(out).toContain('this.hasMany("comments", { foreignKey: "blog_post_id" });');
  });

  it("throws on class-name collision from strip-prefix", () => {
    expect(() =>
      generateModels([table("posts"), table("blog_posts")], {
        stripPrefix: "blog_",
        noHeader: true,
        now: NOW,
      }),
    ).toThrow(/class name collision.*"blog_posts".*"posts".*classify to `Post`/);
  });

  it("disambiguates belongsTo when multiple non-_id FKs derive the same name", () => {
    const tables = [
      table("authors"),
      table("books", {
        foreignKeys: [fk("books", "authors", "written_by"), fk("books", "authors", "edited_by")],
      }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author", { foreignKey: "edited_by" });');
    expect(out).toContain(
      'this.belongsTo("written_by", { className: "Author", foreignKey: "written_by" });',
    );
  });

  it("disambiguates inverse hasMany when multiple FKs point at the same target", () => {
    const tables = [
      table("users"),
      table("posts", {
        foreignKeys: [fk("posts", "users", "author_id"), fk("posts", "users", "editor_id")],
      }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author", { className: "User" });');
    expect(out).toContain('this.belongsTo("editor", { className: "User" });');
    expect(out).toContain('this.hasMany("posts", { foreignKey: "author_id" });');
    expect(out).toContain(
      'this.hasMany("editor_posts", { className: "Post", foreignKey: "editor_id" });',
    );
  });

  it("resolves quoted schema-qualified FK targets from the PG adapter", () => {
    const tables = [
      table("authors"),
      table("a"),
      table("books", {
        foreignKeys: [
          fk("books", 'other_schema."authors"', "author_id"),
          fk("books", '"weird schema"."a"', "a_id"),
        ],
      }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author");');
    expect(out).toContain('this.belongsTo("a");');
    expect(out).not.toMatch(/["']\./);
  });

  it("unqualify() strips quoted identifiers and schemas correctly", () => {
    expect(unqualify("authors")).toBe("authors");
    expect(unqualify("schema.authors")).toBe("authors");
    expect(unqualify('schema."Authors"')).toBe("Authors");
    expect(unqualify('"other schema"."authors"')).toBe("authors");
    expect(unqualify('"a""b"."c"')).toBe("c");
    expect(unqualify('schema."tab.le"')).toBe("tab.le");
  });

  it("resolves schema-qualified FK targets from the PG adapter", () => {
    const tables = [
      table("authors"),
      table("books", {
        foreignKeys: [fk("books", "other_schema.authors", "author_id")],
      }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.belongsTo("author");');
    expect(out).toContain('this.hasMany("books");');
    expect(out).not.toMatch(/other_schema\./);
  });

  it("doesn't mangle hasMany name for irregular-plural source tables", () => {
    const tables = [
      table("companies"),
      table("people", { foreignKeys: [fk("people", "companies", "company_id")] }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    expect(out).toContain('this.hasMany("people");');
    expect(out).not.toMatch(/this\.hasMany\("peoples"\)/);
  });

  it("sorts belongsTo by association name, not FK column", () => {
    const tables = [
      table("authors"),
      table("publishers"),
      table("books", {
        foreignKeys: [fk("books", "publishers", "publisher_id"), fk("books", "authors", "zzz_ref")],
      }),
    ];
    const out = generateModels(tables, { noHeader: true, now: NOW });
    const bookBlock = out.slice(out.indexOf("export class Book"));
    const authorIdx = bookBlock.indexOf('this.belongsTo("author"');
    const publisherIdx = bookBlock.indexOf('this.belongsTo("publisher"');
    expect(authorIdx).toBeGreaterThanOrEqual(0);
    expect(publisherIdx).toBeGreaterThan(authorIdx);
  });

  it("renders a full three-table example exactly", () => {
    const tables = [
      table("authors"),
      table("books", { foreignKeys: [fk("books", "authors", "author_id")] }),
      table("reviews", { foreignKeys: [fk("reviews", "books", "book_id")] }),
    ];
    const out = generateModels(tables, {
      sourceHint: "sqlite:blog.db",
      now: NOW,
    });

    const expected = `// GENERATED by trails-models-dump from sqlite:blog.db on 2026-04-24T14:23:05.000Z.
// Do not edit by hand — re-run trails-models-dump to regenerate.
//
// 3 models, 4 associations from 2 foreign keys.

import { Base } from "@blazetrails/activerecord";

export class Author extends Base {
  static {
    this.hasMany("books");
  }
}

export class Book extends Base {
  static {
    this.belongsTo("author");
    this.hasMany("reviews");
  }
}

export class Review extends Base {
  static {
    this.belongsTo("book");
  }
}
`;
    expect(out).toBe(expected);
  });
});
