/**
 * Multiparameter attribute assignment.
 *
 * Mirrors: ActiveRecord::AttributeAssignment (the multiparameter portion)
 *
 * Rails web forms send date/time fields as multiple numbered parameters:
 *   "written_on(1i)" => "2004", "written_on(2i)" => "6", "written_on(3i)" => "24"
 * These are grouped by attribute name and assembled into the appropriate type.
 *
 * Rails source: activerecord/lib/active_record/attribute_assignment.rb
 */

import { Temporal } from "@blazetrails/activesupport/temporal";
import { AttributeAssignmentError, MultiparameterAssignmentErrors } from "./errors.js";

// Read _aggregateReflections directly to avoid a circular dependency:
// persistence.ts → multiparameter-attribute-assignment.ts → reflection.ts → persistence.ts
function getAggregation(modelClass: any, name: string): { klass: any } | null {
  const aggs: Map<string, { klass: any }> | undefined = modelClass._aggregateReflections;
  return aggs?.get(name) ?? null;
}

// Maximum allowed position index — guards against DoS via huge allocations
// (e.g. written_on(99999999i)). Rails only uses 1..6 for date/time.
const MAX_MULTIPARAMETER_INDEX = 100;

const MULTIPARAMETER_ATTRIBUTE_PATTERN = /^([^(]+)\((\d+)([if]?)\)$/;

export function hasMultiparameterKeys(attrs: Record<string, unknown>): boolean {
  return Object.keys(attrs).some((k) => MULTIPARAMETER_ATTRIBUTE_PATTERN.test(k));
}

/**
 * Separate a flat attribute hash into multiparameter groups and regular keys.
 * Mirrors Rails' extract_callstack_for_multiparameter_attributes.
 */
export function extractMultiparameterCallstack(attrs: Record<string, unknown>): {
  multiparams: Record<string, Record<number, unknown>>;
  regular: Record<string, unknown>;
} {
  // Use null-prototype objects to prevent prototype pollution from user-supplied
  // keys like "__proto__", "constructor", or "prototype".
  const multiparams: Record<string, Record<number, unknown>> = Object.create(null);
  const regular: Record<string, unknown> = Object.create(null);

  for (const [key, value] of Object.entries(attrs)) {
    const match = key.match(MULTIPARAMETER_ATTRIBUTE_PATTERN);
    if (match) {
      const name = match[1];
      const pos = parseInt(match[2], 10);
      if (pos > MAX_MULTIPARAMETER_INDEX) continue; // guard against huge allocations
      const typeFlag = match[3];
      let castValue: unknown;
      if (typeFlag === "i") {
        if (isBlank(value)) {
          castValue = null;
        } else {
          const n = parseInt(String(value), 10);
          castValue = isNaN(n) ? null : n; // NaN → null, not silently stored
        }
      } else if (typeFlag === "f") {
        if (isBlank(value)) {
          castValue = null;
        } else {
          const n = parseFloat(String(value));
          castValue = isNaN(n) ? null : n;
        }
      } else {
        castValue = isBlank(value) ? null : value;
      }
      if (!(name in multiparams)) multiparams[name] = Object.create(null);
      multiparams[name][pos] = castValue;
    } else {
      regular[key] = value;
    }
  }

  return { multiparams, regular };
}

/**
 * Assemble and assign multiparameter groups on an instance.
 * Mirrors Rails' execute_callstack_for_multiparameter_attributes.
 */
export function executeMultiparameterAssignment(
  instance: { constructor: any; writeAttribute(name: string, value: unknown): void },
  callstack: Record<string, Record<number, unknown>>,
): void {
  const errors: Error[] = [];
  const modelClass = instance.constructor;

  for (const [name, partsMap] of Object.entries(callstack)) {
    try {
      const aggregation = getAggregation(modelClass, name);
      if (aggregation) {
        assignAggregation(instance as any, name, partsMap, aggregation);
      } else {
        assignDateTimeAttribute(instance, name, partsMap, modelClass);
      }
    } catch (e) {
      errors.push(
        new AttributeAssignmentError(
          `error on assignment of multiparameter attributes for column ${name}`,
          e instanceof Error ? e : undefined,
          name,
        ),
      );
    }
  }

  if (errors.length > 0) {
    throw new MultiparameterAssignmentErrors(errors);
  }
}

function assignAggregation(
  instance: Record<string, unknown> & { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
  aggregation: { klass: any },
): void {
  const maxPos = Math.min(Math.max(...Object.keys(partsMap).map(Number)), MAX_MULTIPARAMETER_INDEX);
  const values = Array.from({ length: maxPos }, (_, i) => partsMap[i + 1] ?? null);

  if (values.every(isBlank)) return;

  const AggClass = aggregation.klass as new (...args: unknown[]) => unknown;
  // Use the property setter generated by composedOf (writes mapped columns + cache).
  instance[name] = new AggClass(...values);
}

function assignDateTimeAttribute(
  instance: { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
  modelClass: any,
): void {
  const colType = modelClass.typeForAttribute?.(name);
  const typeName: string = colType?.type?.() ?? "";

  let maxPos: number;
  if (typeName === "date") {
    maxPos = 3;
  } else if (typeName === "datetime" || typeName === "timestamp" || typeName === "time") {
    maxPos = 6;
  } else {
    maxPos = Math.min(Math.max(...Object.keys(partsMap).map(Number)), MAX_MULTIPARAMETER_INDEX);
  }

  // Track which positions were explicitly provided (even if blank) vs. absent entirely.
  // Rails casts blank strings via .to_i → 0 (non-nil), so blank-but-present date parts
  // trigger a rescued ArgumentError (→ nil). Absent date parts with time parts present
  // trigger an unrescued TypeError (→ MultiparameterAssignmentErrors). We mirror this by
  // distinguishing "key in partsMap" (provided, possibly blank) from key absent.
  const values = Array.from({ length: maxPos }, (_, i) => {
    const pos = i + 1;
    return pos in partsMap ? (partsMap[pos] ?? null) : undefined;
  });

  if (values.every((v) => v === undefined || isBlank(v))) {
    instance.writeAttribute(name, null);
    return;
  }

  const assembled = assembleValue(values, typeName);
  instance.writeAttribute(name, assembled);
}

function parseIntStrict(s: string | null, fieldName: string): number | null {
  if (s === null) return null;
  const n = parseInt(s, 10);
  if (isNaN(n)) throw new Error(`Invalid ${fieldName} value: ${JSON.stringify(s)}`);
  return n;
}

function buildDate(year: number, month: number, day: number): Temporal.PlainDate {
  try {
    return Temporal.PlainDate.from({ year, month, day }, { overflow: "reject" });
  } catch {
    throw new Error(`Invalid date: ${year}-${month}-${day}`);
  }
}

function buildDateTime(
  year: number,
  month: number,
  day: number,
  hour: number,
  min: number,
  sec: number,
): Temporal.PlainDateTime {
  try {
    return Temporal.PlainDateTime.from(
      { year, month, day, hour, minute: min, second: sec },
      { overflow: "reject" },
    );
  } catch {
    throw new Error(`Invalid datetime: ${year}-${month}-${day} ${hour}:${min}:${sec}`);
  }
}

function assembleValue(parts: unknown[], typeName: string): unknown {
  const str = (v: unknown): string | null =>
    v === null || v === undefined || String(v).trim() === "" ? null : String(v).trim();

  if (typeName === "date") {
    const [ys, ms, ds] = parts.map(str);
    if (!ys || !ms || !ds) return null;
    const year = parseIntStrict(ys, "year"),
      month = parseIntStrict(ms, "month"),
      day = parseIntStrict(ds, "day");
    if (year === null || month === null || day === null) return null;
    return buildDate(year, month, day);
  }

  if (typeName === "datetime" || typeName === "timestamp") {
    // Check raw parts BEFORE str() conversion to distinguish:
    // - undefined: key was absent from form params (Rails: nil → TypeError → raises)
    // - null/blank: key present but empty string (Rails: 0 via .to_i → ArgumentError rescued → nil)
    const datePartsAbsent = parts.slice(0, 3).some((v) => v === undefined);
    // Check key presence (not value truthiness): blank time parts like (4i)=>""
    // are cast to null but were still explicitly provided, matching Rails' .to_i → 0 path.
    const timePartsPresent = parts.slice(3).some((v) => v !== undefined);
    if (datePartsAbsent && timePartsPresent) {
      throw new Error(
        `Multiparameter datetime requires year, month, and day (got ${JSON.stringify(parts)})`,
      );
    }
    const [ys, mos, ds, hs, mis, ss] = parts.map(str);
    if (!ys || !mos || !ds) return null; // blank date parts → nil (Rails rescued ArgumentError)
    const year = parseIntStrict(ys, "year")!,
      month = parseIntStrict(mos, "month")!,
      day = parseIntStrict(ds, "day")!;
    const hour = hs !== null ? (parseIntStrict(hs, "hour") ?? 0) : 0;
    const min = mis !== null ? (parseIntStrict(mis, "minute") ?? 0) : 0;
    const sec = ss !== null ? (parseIntStrict(ss, "second") ?? 0) : 0;
    return buildDateTime(year, month, day, hour, min, sec);
  }

  if (typeName === "time") {
    const [ys, mos, ds, hs, mis, ss] = parts.map(str);
    const hour = hs !== null ? (parseIntStrict(hs, "hour") ?? 0) : 0;
    const min = mis !== null ? (parseIntStrict(mis, "minute") ?? 0) : 0;
    const sec = ss !== null ? (parseIntStrict(ss, "second") ?? 0) : 0;
    if (ys && mos && ds) {
      const year = parseIntStrict(ys, "year"),
        month = parseIntStrict(mos, "month"),
        day = parseIntStrict(ds, "day");
      if (year === null || month === null || day === null) return null;
      return buildDateTime(year, month, day, hour, min, sec);
    }
    // Only time parts → PlainTime (no date context needed for time columns)
    return Temporal.PlainTime.from({ hour, minute: min, second: sec }, { overflow: "reject" });
  }

  // Generic: return the first non-blank value
  return parts.find((v) => !isBlank(v)) ?? null;
}

function isBlank(v: unknown): boolean {
  if (v === null || v === undefined) return true;
  if (typeof v === "string") return v.trim() === "";
  if (typeof v === "number") return isNaN(v);
  return false;
}
