/**
 * Multiparameter attribute assignment.
 *
 * Mirrors: ActiveRecord::AttributeAssignment (the multiparameter portion)
 *
 * Rails web forms send date/time fields as multiple numbered parameters:
 *   "written_on(1i)" => "2004", "written_on(2i)" => "6", "written_on(3i)" => "24"
 * These are grouped by attribute name and assembled into the appropriate type.
 *
 * Rails source: activerecord/lib/active_record/attribute_assignment.rb
 */

import { AttributeAssignmentError, MultiparameterAssignmentErrors } from "./errors.js";

// Read _aggregateReflections directly to avoid a circular dependency:
// persistence.ts → multiparameter-attribute-assignment.ts → reflection.ts → persistence.ts
function getAggregation(modelClass: any, name: string): { klass: any } | null {
  const aggs: Map<string, { klass: any }> | undefined = modelClass._aggregateReflections;
  return aggs?.get(name) ?? null;
}

// Maximum allowed position index — guards against DoS via huge allocations
// (e.g. written_on(99999999i)). Rails only uses 1..6 for date/time.
const MAX_MULTIPARAMETER_INDEX = 100;

const MULTIPARAMETER_ATTRIBUTE_PATTERN = /^([^(]+)\((\d+)([if]?)\)$/;

export function hasMultiparameterKeys(attrs: Record<string, unknown>): boolean {
  return Object.keys(attrs).some((k) => MULTIPARAMETER_ATTRIBUTE_PATTERN.test(k));
}

/**
 * Separate a flat attribute hash into multiparameter groups and regular keys.
 * Mirrors Rails' extract_callstack_for_multiparameter_attributes.
 */
export function extractMultiparameterCallstack(attrs: Record<string, unknown>): {
  multiparams: Record<string, Record<number, unknown>>;
  regular: Record<string, unknown>;
} {
  // Use null-prototype objects to prevent prototype pollution from user-supplied
  // keys like "__proto__", "constructor", or "prototype".
  const multiparams: Record<string, Record<number, unknown>> = Object.create(null);
  const regular: Record<string, unknown> = Object.create(null);

  for (const [key, value] of Object.entries(attrs)) {
    const match = key.match(MULTIPARAMETER_ATTRIBUTE_PATTERN);
    if (match) {
      const name = match[1];
      const pos = parseInt(match[2], 10);
      if (pos > MAX_MULTIPARAMETER_INDEX) continue; // guard against huge allocations
      const typeFlag = match[3];
      let castValue: unknown;
      if (typeFlag === "i") {
        if (isBlank(value)) {
          castValue = null;
        } else {
          const n = parseInt(String(value), 10);
          castValue = isNaN(n) ? null : n; // NaN → null, not silently stored
        }
      } else if (typeFlag === "f") {
        if (isBlank(value)) {
          castValue = null;
        } else {
          const n = parseFloat(String(value));
          castValue = isNaN(n) ? null : n;
        }
      } else {
        castValue = isBlank(value) ? null : value;
      }
      if (!(name in multiparams)) multiparams[name] = Object.create(null);
      multiparams[name][pos] = castValue;
    } else {
      regular[key] = value;
    }
  }

  return { multiparams, regular };
}

/**
 * Assemble and assign multiparameter groups on an instance.
 * Mirrors Rails' execute_callstack_for_multiparameter_attributes.
 */
export function executeMultiparameterAssignment(
  instance: { constructor: any; writeAttribute(name: string, value: unknown): void },
  callstack: Record<string, Record<number, unknown>>,
): void {
  const errors: Error[] = [];
  const modelClass = instance.constructor;

  for (const [name, partsMap] of Object.entries(callstack)) {
    try {
      const aggregation = getAggregation(modelClass, name);
      if (aggregation) {
        assignAggregation(instance as any, name, partsMap, aggregation);
      } else {
        assignDateTimeAttribute(instance, name, partsMap);
      }
    } catch (e) {
      errors.push(
        new AttributeAssignmentError(
          `error on assignment of multiparameter attributes for column ${name}`,
          e instanceof Error ? e : undefined,
          name,
        ),
      );
    }
  }

  if (errors.length > 0) {
    throw new MultiparameterAssignmentErrors(errors);
  }
}

function assignAggregation(
  instance: Record<string, unknown> & { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
  aggregation: { klass: any },
): void {
  const maxPos = Math.min(Math.max(...Object.keys(partsMap).map(Number)), MAX_MULTIPARAMETER_INDEX);
  const values = Array.from({ length: maxPos }, (_, i) => partsMap[i + 1] ?? null);

  if (values.every(isBlank)) return;

  const AggClass = aggregation.klass as new (...args: unknown[]) => unknown;
  // Use the property setter generated by composedOf (writes mapped columns + cache).
  instance[name] = new AggClass(...values);
}

function assignDateTimeAttribute(
  instance: { writeAttribute(name: string, value: unknown): void },
  name: string,
  partsMap: Record<number, unknown>,
): void {
  // Mirrors Rails' execute_callstack_for_multiparameter_attributes: an all-nil
  // parts hash collapses to nil; otherwise the raw numeric-keyed hash is written
  // and the type's AcceptsMultiparameterTime cast assembles the value. Writing
  // the hash (not an assembled Temporal value) keeps valueBeforeTypeCast the
  // hash, so came_from_user? is false via isValueConstructedByMassAssignment.
  const values = Object.values(partsMap).every((v) => v === null) ? null : partsMap;
  instance.writeAttribute(name, values);
}

function isBlank(v: unknown): boolean {
  if (v === null || v === undefined) return true;
  if (typeof v === "string") return v.trim() === "";
  if (typeof v === "number") return isNaN(v);
  return false;
}
