import type { Base } from "./base.js";

import {
  ArgumentError,
  Model,
  type AttributeSet,
  type CallbackObject,
} from "@blazetrails/activemodel";
import {
  IsolatedExecutionState,
  defineCallbacks,
  extractOptionsBang,
  included,
  kernelArray,
  peekCallbackChain as asPeekCallbackChain,
  runCallbacks,
  type FilterListEntry,
} from "@blazetrails/activesupport";
import { ActiveRecord } from "./ar-config.js";
import { Rollback } from "./errors.js";
export { Rollback };

import {
  CURRENT_TRANSACTION_KEY,
  Transaction,
} from "./connection-adapters/abstract/transaction.js";
import { Transaction as PublicTransaction } from "./transaction.js";
import { transaction as dbTransaction } from "./connection-adapters/abstract/database-statements.js";

type TransactionAction = "create" | "update" | "destroy";

/**
 * Get the currently active transaction, if any.
 */
export function currentTransaction(): Transaction | null {
  return IsolatedExecutionState.get<Transaction | null>(CURRENT_TRANSACTION_KEY) ?? null;
}

/**
 * Returns the current transaction as the public Transaction wrapper, or
 * Transaction.NULL_TRANSACTION when no transaction is open.
 *
 * NULL_TRANSACTION fires afterCommit immediately and ignores afterRollback,
 * matching Rails' ActiveRecord::Transaction::NULL_TRANSACTION behavior.
 *
 * Mirrors: ActiveRecord::Base.current_transaction
 */
export function currentTransactionPublic(): PublicTransaction {
  const internalTx = currentTransaction();
  if (!internalTx) return PublicTransaction.NULL_TRANSACTION;
  // Use the existing userTransaction so callers get a stable identity (same
  // object per internal transaction, consistent uuid memoization).
  return (internalTx as any).userTransaction ?? new PublicTransaction(internalTx);
}

/**
 * Run a callback after all currently open transactions have committed.
 * If there is no open transaction, the callback is called immediately.
 *
 * Mirrors: ActiveRecord.after_all_transactions_commit (active_record.rb:527),
 * which collects `all_open_transactions` (active_record.rb:553) — only
 * transactions that are `open? && joinable? && !state.invalidated?` — and
 * yields immediately when none are open. A *finalized* or *invalidated*
 * transaction is therefore not "open" here and the block runs immediately; this
 * deliberately does NOT route through the per-transaction
 * `Transaction#afterCommit`, which (per transaction.rb:85) raises on a finalized
 * transaction.
 */
export function afterAllTransactionsCommit(fn: () => void | Promise<void>): void | Promise<void> {
  const tx = currentTransactionPublic();
  if (tx.isClosed()) {
    return fn();
  }
  return tx.afterCommit(fn);
}

/**
 * Execute a block within a database transaction.
 *
 * Mirrors: ActiveRecord::Base.transaction
 *
 * Delegates through the database-statements transaction function which
 * routes through TransactionManager for proper Rails-style transaction
 * lifecycle. Every trails adapter routes transactions through TM
 * (post TM Phase 3 unification).
 */
export async function transaction<T>(
  modelClass: typeof Base,
  fn: (tx: PublicTransaction) => Promise<T>,
  options?: { isolation?: string; requiresNew?: boolean; joinable?: boolean },
): Promise<T | undefined> {
  if (options) {
    for (const key of Object.keys(options)) {
      if (key !== "isolation" && key !== "requiresNew" && key !== "joinable") {
        throw new ArgumentError(`unknown keyword: :${key}`);
      }
    }
  }

  // Taking the yielded connection (the block parameter connection) instead of
  // the deprecated `.connection` getter keeps the build/callback path from
  // flipping the lease permanent under `permanent_connection_checkout =
  // :deprecated | :disallowed`, so the pool releases the connection once the
  // transaction completes.
  return modelClass.withConnection(async (connection) => {
    const result = await dbTransaction.call(connection as any, fn as (tx?: unknown) => Promise<T>, {
      requiresNew: options?.requiresNew,
      isolation: options?.isolation,
      joinable: options?.joinable,
    });
    return result as T | undefined;
  });
}

/**
 * Execute a block within a savepoint (nested transaction).
 * The name parameter is accepted for backward compatibility but
 * savepoint names are auto-generated by the TransactionManager
 * (matching Rails' `active_record_N` naming).
 *
 * Mirrors: ActiveRecord::Base.transaction(requires_new: true)
 */
export async function savepoint<T>(
  modelClass: typeof Base,
  _name: string,
  fn: () => Promise<T>,
): Promise<T | undefined> {
  return transaction(modelClass, async () => fn(), { requiresNew: true });
}

// ---------------------------------------------------------------------------
// ClassMethods — mirrors ActiveRecord::Transactions::ClassMethods
// `this`-typed functions assigned to Base, so `this` is the model class the
// way `self` is in the Ruby ClassMethods module.
// ---------------------------------------------------------------------------

type CallbackFn = (...args: any[]) => any;

/**
 * What the `ClassMethods` transaction macros take as a filter. Rails' `*args`
 * reaches `set_callback`, so a Symbol method name is accepted alongside a
 * block — and a Ruby Symbol is a colon-prefixed string in trails.
 */
type TransactionCallbackFilter<T extends typeof Model> =
  | ((record: InstanceType<T>) => void | boolean | Promise<void | boolean>)
  | CallbackObject
  | string;
/**
 * Rails' `*args` on the transaction macros: the filters `set_callback` takes,
 * optionally closed by the options Hash `set_options_for_callbacks!` extracts.
 */
type TransactionCallbackArgs<T extends typeof Model> = (
  | TransactionCallbackFilter<T>
  | CallbackOptions
)[];
type CallbackOptions = {
  // Rails takes any Symbol here and rejects a bad one at runtime, in
  // `assert_valid_transaction_action` (transactions.rb:344-348) — so the type
  // must stay wide enough for that raise to be reachable.
  on?: string | string[];
  if?: CallbackFn | CallbackFn[];
  unless?: CallbackFn | CallbackFn[];
  prepend?: boolean;
};

/**
 * Mirrors: ActiveRecord::Transactions' `included do ... end` (transactions.rb:10-14).
 */
export const InstanceMethods = {
  [included](base: typeof Model): void {
    for (const name of ["commit", "rollback", "before_commit"]) {
      defineCallbacks(base.prototype, name, { scope: ["kind", "name"] });
    }
  },
};

/** Mirrors: ActiveRecord::Transactions::ClassMethods#before_commit */
export function beforeCommit<T extends typeof Base>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args);
  setCallback.call(this, "before_commit", "before", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_commit */
export function afterCommit<T extends typeof Model>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, prependOption());
  setCallback.call(this, "commit", "after", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_save_commit */
export function afterSaveCommit<T extends typeof Base>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, {
    on: ["create", "update"],
    ...prependOption(),
  });
  setCallback.call(this, "commit", "after", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_create_commit */
export function afterCreateCommit<T extends typeof Base>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, {
    on: "create",
    ...prependOption(),
  });
  setCallback.call(this, "commit", "after", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_update_commit */
export function afterUpdateCommit<T extends typeof Base>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, {
    on: "update",
    ...prependOption(),
  });
  setCallback.call(this, "commit", "after", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_destroy_commit */
export function afterDestroyCommit<T extends typeof Base>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, {
    on: "destroy",
    ...prependOption(),
  });
  setCallback.call(this, "commit", "after", ...args);
}

/** Mirrors: ActiveRecord::Transactions::ClassMethods#after_rollback */
export function afterRollback<T extends typeof Model>(
  this: T,
  ...args: TransactionCallbackArgs<T>
): void {
  setOptionsForCallbacksBang(args, prependOption());
  setCallback.call(this, "rollback", "after", ...args);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#set_callback (transactions.rb:304-318).
 *
 * Rails' `super` is ActiveSupport::Callbacks' `set_callback`, reached here as
 * ActiveModel's `Model.setCallback` — a `this`-typed function assigned to a
 * class cannot spell `super`, so the inherited implementation is named.
 *
 * `*filter_list` is untyped in Ruby and stays open here so the macros above can
 * forward their own `TransactionCallbackFilter<T>` through it. Rails leaves
 * `:on` in the Hash it hands to `super`, where an unknown key is ignored;
 * trails' `assertValidKeys` rejects it, so it comes off at that seam — after
 * this body's own guard, and for every event, since `before_commit` reaches
 * `super` with the `:on` `set_options_for_callbacks!` left in place.
 */
export function setCallback<T extends typeof Model>(
  this: T,
  name: string,
  ...filterList: FilterListEntry<any>[]
): void {
  const [rest, extracted] = extractOptionsBang(filterList);
  const options = { ...extracted } as Record<string, unknown>;

  if ((name === "commit" || name === "rollback") && options.on !== undefined) {
    const fireOn = kernelArray(options.on) as string[];
    assertValidTransactionAction(fireOn);
    options.if = [
      (record: Base): boolean => isTransactionIncludeAnyAction.call(record, fireOn),
      ...kernelArray(options.if),
    ];
  }
  delete options.on;

  (Model.setCallback as (this: T, name: string, ...args: unknown[]) => void).call(
    this,
    name,
    ...rest,
    options,
  );
}

// ---------------------------------------------------------------------------
// Instance methods — mirrors ActiveRecord::Transactions instance methods
// These are standalone functions that take the record as first arg.
// ---------------------------------------------------------------------------

/**
 * Run before_commit callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#before_committed!
 */
export async function beforeCommittedBang(record: Base): Promise<void> {
  const ctor = record.constructor as typeof Base;
  await runCallbacks(record, "before_commit");
}

/**
 * Run after_commit callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#committed!
 */
export async function committedBang(
  this: Base,
  { shouldRunCallbacks = true }: { shouldRunCallbacks?: boolean } = {},
): Promise<void> {
  const r = this as any;
  r._startTransactionState = null;
  try {
    if (shouldRunCallbacks && isTriggerTransactionalCallbacks.call(this)) {
      r._committedAlreadyCalled = true;
      const ctor = this.constructor as typeof Base;
      await runCallbacks(this, "commit");
    }
  } finally {
    r._committedAlreadyCalled = false;
    r._triggerUpdateCallback = false;
    r._triggerDestroyCallback = false;
  }
}

/**
 * Run after_rollback callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#rolledback!
 */
export async function rolledbackBang(
  this: Base,
  {
    forceRestoreState = false,
    shouldRunCallbacks = true,
  }: { forceRestoreState?: boolean; shouldRunCallbacks?: boolean } = {},
): Promise<void> {
  try {
    if (shouldRunCallbacks && isTriggerTransactionalCallbacks.call(this)) {
      const ctor = this.constructor as typeof Base;
      await runCallbacks(this, "rollback");
    }
  } finally {
    restoreTransactionRecordState.call(this, forceRestoreState);
    clearTransactionRecordState.call(this);
    if (forceRestoreState) {
      // Force-null _startTransactionState on full outer rollback. Inner
      // savepoint commits move records to the parent via add_transaction_record
      // without calling committedBang — matching Rails' commit_records else branch
      // which skips committed! in the happy path. Level can therefore be > 1 here.
      // clearTransactionRecordState only decrements and would leave a stale
      // snapshot — null it unconditionally on forceRestore.
      (this as any)._startTransactionState = null;
      (this as any)._triggerUpdateCallback = false;
      (this as any)._triggerDestroyCallback = false;
    }
  }
}

/**
 * Snapshot record state before the transaction so it can be restored on
 * rollback.
 *
 * Mirrors: ActiveRecord::Transactions#remember_transaction_record_state
 */
/**
 * @internal
 * @missingRailsArgs frozen? — PERMANENT: Ruby's `@attributes.frozen?`
 *   (transactions.rb:328) is a zero-arg receiver method every object answers;
 *   JS has no such method, so the same read is spelled with the object as
 *   `Object.isFrozen`'s argument.
 */
export function rememberTransactionRecordState(this: Base): void {
  const r = this as any;
  // Initialize state once per outermost transaction, then increment level for
  // each savepoint. Mirrors Rails' @_start_transaction_state ||= {...}; level += 1.
  if (!r._startTransactionState) {
    const snapshotAttrs = r._attributes.deepDup();
    r._startTransactionState = {
      newRecord: r._newRecord,
      destroyed: r._destroyed,
      frozen: Object.isFrozen(r._attributes),
      id: this.id,
      previouslyNewRecord: r._previouslyNewRecord,
      attributes: snapshotAttrs,
      level: 0,
    };
  }
  r._startTransactionState.level += 1;

  // Mirrors Rails' _committed_already_called guard inside remember_transaction_record_state.
  if (r._committedAlreadyCalled) {
    r._newRecordBeforeLastCommit = false;
  } else {
    r._newRecordBeforeLastCommit = r._startTransactionState.newRecord;
  }
}

/**
 * Restore the new record state and id of a record that was previously saved by
 * a call to save_record_state.
 *
 * Mirrors: ActiveRecord::Transactions#restore_transaction_record_state
 *
 * @internal
 */
export function restoreTransactionRecordState(this: Base, forceRestoreState = false): void {
  const r = this as any;
  const restoreState = r._startTransactionState;
  if (restoreState) {
    if (forceRestoreState || restoreState.level <= 1) {
      r._newRecord = restoreState.newRecord;
      r._previouslyNewRecord = restoreState.previouslyNewRecord;
      r._destroyed = restoreState.destroyed;
      r._attributes = (restoreState.attributes as AttributeSet).map((attr) => {
        const value = r._attributes.fetchValue(attr.name);
        if (attr.value !== value) attr = attr.withValueFromUser(value);
        return attr;
      });
      r._mutationsFromDatabase = null;
      r._mutationsBeforeLastSave = null;
      const ctor = this.constructor as typeof Base;
      const primaryKey = ctor.primaryKey;
      if (ctor.compositePrimaryKey) {
        const cols = primaryKey as string[];
        const savedId = restoreState.id as unknown[];
        if (cols.some((col, i) => r._attributes.fetchValue(col) !== savedId[i])) {
          cols.forEach((col, i) => {
            r._attributes.writeFromUser(col, savedId[i]);
          });
        }
      } else {
        if (r._attributes.fetchValue(primaryKey as string) !== restoreState.id) {
          r._attributes.writeFromUser(primaryKey as string, restoreState.id);
        }
      }

      if (restoreState.frozen) r._attributes.freeze();
    }
  }
}

/**
 * Execute a block within a transaction and capture its return value as a
 * status flag. If the status is falsy (false/null/undefined), the transaction
 * is rolled back. Handles record state snapshotting/restore and callback
 * scheduling.
 *
 * Mirrors: ActiveRecord::Transactions#with_transaction_returning_status
 */
export async function withTransactionReturningStatus<T>(
  this: Base,
  fn: () => Promise<T>,
): Promise<T> {
  const modelClass = this.constructor as typeof Base;

  // _triggerUpdateCallback/_triggerDestroyCallback are NOT reset here; Rails resets
  // those only in committed!/rolledback! ensure blocks.
  const r = this as any;
  r._transactionAction = undefined;

  let status: T;

  // Wrap in `with_connection` so the `ensure_finalize` connection probe and the
  // nested transaction don't permanently lease a connection under
  // `permanent_connection_checkout = :deprecated | :disallowed`. The yielded
  // connection is taken from the block parameter rather than re-read off the
  // deprecated `.connection` getter, matching Rails.
  await modelClass.withConnection(async (connection) => {
    // Mirrors Rails' `ensure_finalize = !connection.transaction_open?`
    // (transactions.rb:411).
    const ensureFinalize = !connection.isTransactionOpen();

    await dbTransaction.call(connection as any, async () => {
      // Enroll record with the TransactionManager so it fires committedBang/
      // rolledbackBang after the transaction commits or rolls back. The TM-driven
      // rolledbackBang path calls restoreTransactionRecordState which reads the
      // persistent _startTransactionState snapshot — matching Rails exactly. We
      // intentionally do NOT register a per-call tx.afterRollback hook here: the
      // closure would capture per-save state, and on multi-save rollbacks the
      // last-registered hook would overwrite the correct outermost snapshot.
      await addToTransaction.call(this, ensureFinalize || hasTransactionalCallbacks.call(this));
      rememberTransactionRecordState.call(this);

      status = await fn();
      // Ruby truthiness: only false/nil trigger rollback (0, "" are truthy in Ruby)
      if (status === false || status == null) {
        throw new Rollback();
      }
      return status;
    });
  });

  return status!;
}

/**
 * Mirrors: ActiveRecord::Transactions#_new_record_before_last_commit (attr_accessor)
 */
export function _newRecordBeforeLastCommit(this: Base): boolean {
  return (this as any)._newRecordBeforeLastCommit ?? false;
}

/**
 * Returns whether the record should trigger transactional callbacks.
 *
 * Mirrors: ActiveRecord::Transactions#trigger_transactional_callbacks?
 */
export function isTriggerTransactionalCallbacks(this: Base): boolean {
  const r = this as any;
  // Use === true to avoid prototype method bleeding through as a truthy value.
  const newBeforeLastCommit = r._newRecordBeforeLastCommit === true;
  const triggerUpdate = r._triggerUpdateCallback === true;
  const triggerDestroy = r._triggerDestroyCallback === true;
  return (
    ((newBeforeLastCommit || triggerUpdate) && this.isPersisted()) ||
    (triggerDestroy && this.isDestroyed())
  );
}

// ---------------------------------------------------------------------------
// Private instance helpers — mirrors ActiveRecord::Transactions private block.
// Exported so base.ts can wire them into include(Base, {...}) for parity:api.
// ---------------------------------------------------------------------------

// Mirrors: attr_reader :_committed_already_called
/** @internal */
export function _committedAlreadyCalled(this: Base): boolean | null {
  return (this as any)._committedAlreadyCalled ?? null;
}

// Mirrors: attr_reader :_trigger_update_callback
/** @internal */
export function _triggerUpdateCallback(this: Base): boolean | null {
  return (this as any)._triggerUpdateCallback ?? null;
}

// Mirrors: attr_reader :_trigger_destroy_callback
/** @internal */
export function _triggerDestroyCallback(this: Base): boolean | null {
  return (this as any)._triggerDestroyCallback ?? null;
}

// Mirrors: ActiveRecord::Transactions#init_internals (transactions.rb:432-437)
/** @internal */
export function initInternals(this: Base, super_: () => void): void {
  super_();
  const r = this as any;
  r._startTransactionState = null;
  r._committedAlreadyCalled = null;
  r._newRecordBeforeLastCommit = null;
}

// Mirrors: ActiveRecord::Transactions#clear_transaction_record_state
/** @internal */
export function clearTransactionRecordState(this: Base): void {
  const r = this as any;
  if (!r._startTransactionState) return;
  r._startTransactionState.level -= 1;
  if (r._startTransactionState.level < 1) r._startTransactionState = null;
}

// Mirrors: ActiveRecord::Transactions#transaction_include_any_action?
/** @internal */
export function isTransactionIncludeAnyAction(this: Base, actions: string[]): boolean {
  const r = this as any;
  return actions.some((action) => {
    switch (action) {
      case "create":
        return this.isPersisted() && r._newRecordBeforeLastCommit === true;
      case "update":
        return (
          !(r._newRecordBeforeLastCommit || this.isDestroyed()) && r._triggerUpdateCallback === true
        );
      case "destroy":
        return r._triggerDestroyCallback === true;
      default:
        return false;
    }
  });
}

// Mirrors: ActiveRecord::Transactions#add_to_transaction
/** @internal */
export async function addToTransaction(this: Base, ensureFinalize = true): Promise<void> {
  const ctor = this.constructor as any;
  // transactions.rb:513-515 — `self.class.with_connection { |connection| ... }`.
  // We're always called from within a transaction, so the lease is already held
  // and `with_connection` yields that same connection rather than checking a
  // second one out.
  await ctor.withConnection((connection: any) => {
    connection?.addTransactionRecord?.(this, ensureFinalize);
  });
}

// Mirrors: ActiveRecord::Transactions#has_transactional_callbacks?
/** @internal */
export function hasTransactionalCallbacks(this: Base): boolean {
  const proto = (this.constructor as any).prototype;
  const rollback = asPeekCallbackChain(proto, "rollback");
  const commit = asPeekCallbackChain(proto, "commit");
  const beforeCommitChain = asPeekCallbackChain(proto, "before_commit");
  return (
    !(rollback == null || rollback.isEmpty) ||
    !(commit == null || commit.isEmpty) ||
    !(beforeCommitChain == null || beforeCommitChain.isEmpty)
  );
}

// ---------------------------------------------------------------------------
// Private class helpers — mirrors ActiveRecord::Transactions::ClassMethods private block.
// ---------------------------------------------------------------------------

// Mirrors: ActiveRecord::Transactions::ClassMethods#prepend_option
/** @internal */
function prependOption(): Record<string, unknown> {
  if (ActiveRecord.runAfterTransactionCallbacksInOrderDefined) {
    return { prepend: true };
  } else {
    return {};
  }
}

const VALID_TRANSACTION_ACTIONS = new Set(["create", "update", "destroy"]);

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#set_options_for_callbacks!
 *
 * Ruby's `args << options` mutates the caller's splat array, and so does this;
 * the filters are copied out first because `extractOptionsBang` answers `args`
 * itself when the last element is not a Hash. `:on` stays in the options
 * afterwards, exactly as `transactions.rb:334-341` leaves it, so `set_callback`
 * sees it again.
 *
 * @internal
 *
 * @missingRailsCall merge! — PERMANENT: Reviewed (RFC 0106 wave 4c): Ruby's
 *   `args.extract_options!.merge!(enforced_options)` mutates the extracted hash
 *   in place; TS builds the merged object with a spread rather than writing the
 *   enforced keys into the caller's own options literal, so there is no
 *   in-place `merge!` to name.
 */
export function setOptionsForCallbacksBang(
  args: unknown[],
  enforcedOptions: Record<string, unknown> = {},
): void {
  const [rest, extracted] = extractOptionsBang(args);
  const options: Record<string, unknown> = { ...extracted, ...enforcedOptions };
  const filterList = [...rest];
  args.length = 0;
  args.push(...filterList, options);

  if (options.on !== undefined) {
    const fireOn = (Array.isArray(options.on) ? options.on : [options.on]) as string[];
    assertValidTransactionAction(fireOn);
    const existingIf = options.if;
    options.if = [
      (record: Base): boolean => isTransactionIncludeAnyAction.call(record, fireOn),
      ...(existingIf === undefined ? [] : Array.isArray(existingIf) ? existingIf : [existingIf]),
    ];
  }
}

// Mirrors: ActiveRecord::Transactions::ClassMethods#assert_valid_transaction_action
/** @internal */
function assertValidTransactionAction(actions: string[]): void {
  const invalid = actions.filter((a) => !VALID_TRANSACTION_ACTIONS.has(a));
  if (invalid.length > 0) {
    throw new ArgumentError(
      `:on conditions for after_commit and after_rollback callbacks have to be one of [:create, :destroy, :update]`,
    );
  }
}
