import type { Base } from "./base.js";

import {
  ArgumentError,
  _registerCallbackOnProto,
  runBeforeCallbacksOnProto,
  runAfterCallbacksOnProto,
  type CallbackConditions,
  type TransactionalCallbackConditions,
} from "@blazetrails/activemodel";
import {
  IsolatedExecutionState,
  peekCallbackChain as asPeekCallbackChain,
} from "@blazetrails/activesupport";
import { Rollback } from "./errors.js";
export { Rollback };

import { Transaction } from "./connection-adapters/abstract/transaction.js";
import { Transaction as PublicTransaction } from "./transaction.js";
import { transaction as dbTransaction } from "./connection-adapters/abstract/database-statements.js";

type TransactionAction = "create" | "update" | "destroy";

const CURRENT_TRANSACTION_KEY = Symbol.for("ar_current_transaction");

/**
 * Get the currently active transaction, if any.
 */
export function currentTransaction(): Transaction | null {
  return IsolatedExecutionState.get<Transaction | null>(CURRENT_TRANSACTION_KEY) ?? null;
}

/**
 * Returns the current transaction as the public Transaction wrapper, or
 * Transaction.NULL_TRANSACTION when no transaction is open.
 *
 * NULL_TRANSACTION fires afterCommit immediately and ignores afterRollback,
 * matching Rails' ActiveRecord::Transaction::NULL_TRANSACTION behavior.
 *
 * Mirrors: ActiveRecord::Base.current_transaction
 */
export function currentTransactionPublic(): PublicTransaction {
  const internalTx = currentTransaction();
  if (!internalTx) return PublicTransaction.NULL_TRANSACTION;
  // Use the existing userTransaction so callers get a stable identity (same
  // object per internal transaction, consistent uuid memoization).
  return (internalTx as any).userTransaction ?? new PublicTransaction(internalTx);
}

/**
 * Run a callback after all currently open transactions have committed.
 * If there is no open transaction, the callback is called immediately.
 * Delegates through currentTransactionPublic() so NULL_TRANSACTION semantics
 * (afterCommit runs immediately) apply consistently.
 *
 * Mirrors: ActiveRecord.after_all_transactions_commit
 */
export function afterAllTransactionsCommit(fn: () => void | Promise<void>): void | Promise<void> {
  return currentTransactionPublic().afterCommit(fn);
}

/**
 * Execute a block within a database transaction.
 *
 * Mirrors: ActiveRecord::Base.transaction
 *
 * Delegates through the database-statements transaction function which
 * routes through TransactionManager for proper Rails-style transaction
 * lifecycle. Every trails adapter routes transactions through TM
 * (post TM Phase 3 unification).
 */
export async function transaction<T>(
  modelClass: typeof Base,
  fn: (tx: Transaction) => Promise<T>,
  options?: { isolation?: string; requiresNew?: boolean; joinable?: boolean },
): Promise<T | undefined> {
  const adapter = modelClass.connection;

  const result = await dbTransaction.call(
    adapter as any,
    async (userTx?: unknown) => {
      let internalTx: Transaction;
      if (userTx instanceof Transaction) {
        internalTx = userTx;
      } else if (userTx && (userTx as any)._internalTransaction instanceof Transaction) {
        internalTx = (userTx as any)._internalTransaction;
      } else {
        const tmCurrent = (adapter as any).currentTransaction?.();
        internalTx = tmCurrent instanceof Transaction ? tmCurrent : new Transaction(adapter);
      }
      return IsolatedExecutionState.scope(CURRENT_TRANSACTION_KEY, internalTx, () =>
        fn(internalTx),
      );
    },
    {
      requiresNew: options?.requiresNew,
      isolation: options?.isolation,
      joinable: options?.joinable,
    },
  );
  return result as T | undefined;
}

/**
 * Execute a block within a savepoint (nested transaction).
 * The name parameter is accepted for backward compatibility but
 * savepoint names are auto-generated by the TransactionManager
 * (matching Rails' `active_record_N` naming).
 *
 * Mirrors: ActiveRecord::Base.transaction(requires_new: true)
 */
export async function savepoint<T>(
  modelClass: typeof Base,
  _name: string,
  fn: () => Promise<T>,
): Promise<T | undefined> {
  return transaction(modelClass, async () => fn(), { requiresNew: true });
}

// ---------------------------------------------------------------------------
// ClassMethods — mirrors ActiveRecord::Transactions::ClassMethods
// These are standalone functions that take the model class as first arg,
// following the codebase mixin pattern.
// ---------------------------------------------------------------------------

type CallbackFn = (...args: any[]) => any;
type CallbackOptions = {
  on?: TransactionAction | TransactionAction[];
  if?: CallbackFn | CallbackFn[];
  unless?: CallbackFn | CallbackFn[];
  prepend?: boolean;
};

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#before_commit
 * Registers directly on the model callback chain (ActiveModel does not
 * provide a `beforeCommit` class helper).
 */
export function beforeCommit(
  modelClass: typeof Base,
  fn: CallbackFn,
  options?: CallbackOptions,
): void {
  _registerCallbackOnProto(
    (modelClass as unknown as { prototype: object }).prototype,
    "before",
    "commit",
    fn,
    synthOnCondition(options as Record<string, unknown>),
  );
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_commit
 */
export function afterCommit(
  modelClass: typeof Base,
  fn: CallbackFn,
  options?: CallbackOptions,
): void {
  (modelClass as any).afterCommit(fn, options);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_save_commit
 */
export function afterSaveCommit(modelClass: typeof Base, fn: CallbackFn): void {
  afterCommit(modelClass, fn, { on: ["create", "update"] });
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_create_commit
 */
export function afterCreateCommit(modelClass: typeof Base, fn: CallbackFn): void {
  afterCommit(modelClass, fn, { on: "create" });
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_update_commit
 */
export function afterUpdateCommit(modelClass: typeof Base, fn: CallbackFn): void {
  afterCommit(modelClass, fn, { on: "update" });
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_destroy_commit
 */
export function afterDestroyCommit(modelClass: typeof Base, fn: CallbackFn): void {
  afterCommit(modelClass, fn, { on: "destroy" });
}

// ---------------------------------------------------------------------------
// this-typed class method implementations for Base static assignment.
// Each mirrors a Rails ClassMethods shortcut that delegates to after_commit
// with an enforced `on:` option.
// ---------------------------------------------------------------------------

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_save_commit
 */
export function afterSaveCommitMethod<T extends typeof Base>(
  this: T,
  fn: ((record: InstanceType<T>) => void | boolean | Promise<void | boolean>) | object,
  conditions?: CallbackConditions<InstanceType<T>>,
): void {
  this.afterCommit(fn, {
    ...conditions,
    on: ["create", "update"],
  } as TransactionalCallbackConditions<InstanceType<T>>);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_create_commit
 */
export function afterCreateCommitMethod<T extends typeof Base>(
  this: T,
  fn: ((record: InstanceType<T>) => void | boolean | Promise<void | boolean>) | object,
  conditions?: CallbackConditions<InstanceType<T>>,
): void {
  this.afterCommit(fn, {
    ...conditions,
    on: "create",
  } as TransactionalCallbackConditions<InstanceType<T>>);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_update_commit
 */
export function afterUpdateCommitMethod<T extends typeof Base>(
  this: T,
  fn: ((record: InstanceType<T>) => void | boolean | Promise<void | boolean>) | object,
  conditions?: CallbackConditions<InstanceType<T>>,
): void {
  this.afterCommit(fn, {
    ...conditions,
    on: "update",
  } as TransactionalCallbackConditions<InstanceType<T>>);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_destroy_commit
 */
export function afterDestroyCommitMethod<T extends typeof Base>(
  this: T,
  fn: ((record: InstanceType<T>) => void | boolean | Promise<void | boolean>) | object,
  conditions?: CallbackConditions<InstanceType<T>>,
): void {
  this.afterCommit(fn, {
    ...conditions,
    on: "destroy",
  } as TransactionalCallbackConditions<InstanceType<T>>);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#after_rollback
 */
export function afterRollback(
  modelClass: typeof Base,
  fn: CallbackFn,
  options?: CallbackOptions,
): void {
  (modelClass as any).afterRollback(fn, options);
}

/**
 * Mirrors: ActiveRecord::Transactions::ClassMethods#set_callback
 */
export function setCallback(
  modelClass: typeof Base,
  name: "commit" | "rollback" | "before_commit",
  fn: CallbackFn,
  options?: CallbackOptions,
): void {
  if (name === "commit") {
    afterCommit(modelClass, fn, options);
  } else if (name === "rollback") {
    afterRollback(modelClass, fn, options);
  } else if (name === "before_commit") {
    beforeCommit(modelClass, fn, options);
  }
}

// ---------------------------------------------------------------------------
// Instance methods — mirrors ActiveRecord::Transactions instance methods
// These are standalone functions that take the record as first arg.
// ---------------------------------------------------------------------------

/**
 * Run before_commit callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#before_committed!
 */
export async function beforeCommittedBang(record: Base): Promise<void> {
  const ctor = record.constructor as typeof Base;
  await runBeforeCallbacksOnProto((ctor as any).prototype, "commit", record);
}

/**
 * Run after_commit callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#committed!
 */
export async function committedBang(
  this: Base,
  { shouldRunCallbacks = true }: { shouldRunCallbacks?: boolean } = {},
): Promise<void> {
  const r = this as any;
  r._startTransactionState = null;
  try {
    if (shouldRunCallbacks && isTriggerTransactionalCallbacks.call(this)) {
      r._committedAlreadyCalled = true;
      const ctor = this.constructor as typeof Base;
      await runAfterCallbacksOnProto((ctor as any).prototype, "commit", this);
    }
  } finally {
    r._committedAlreadyCalled = false;
    r._triggerUpdateCallback = false;
    r._triggerDestroyCallback = false;
  }
}

/**
 * Run after_rollback callbacks on the record.
 *
 * Mirrors: ActiveRecord::Transactions#rolledback!
 */
export async function rolledbackBang(
  this: Base,
  {
    forceRestoreState = false,
    shouldRunCallbacks = true,
  }: { forceRestoreState?: boolean; shouldRunCallbacks?: boolean } = {},
): Promise<void> {
  try {
    if (shouldRunCallbacks && isTriggerTransactionalCallbacks.call(this)) {
      const ctor = this.constructor as typeof Base;
      await runAfterCallbacksOnProto((ctor as any).prototype, "rollback", this);
    }
  } finally {
    _restoreTransactionRecordState.call(this, forceRestoreState);
    clearTransactionRecordState.call(this);
    if (forceRestoreState) {
      // Force-null _startTransactionState on full outer rollback. Inner
      // savepoint commits move records to the parent via add_transaction_record
      // without calling committedBang — matching Rails' commit_records else branch
      // which skips committed! in the happy path. Level can therefore be > 1 here.
      // clearTransactionRecordState only decrements and would leave a stale
      // snapshot — null it unconditionally on forceRestore.
      (this as any)._startTransactionState = null;
      (this as any)._triggerUpdateCallback = false;
      (this as any)._triggerDestroyCallback = false;
    }
  }
}

/**
 * Snapshot record state before the transaction so it can be restored on
 * rollback.
 *
 * Mirrors: ActiveRecord::Transactions#remember_transaction_record_state
 */
/**
 * Record identity state snapshot — only captures fields that define what
 * the record IS (new? destroyed? id?), not what happened to it during the
 * transaction (tracking flags are set by save/destroy and read by
 * trigger_transactional_callbacks?).
 */
interface TransactionRecordSnapshot {
  newRecord: boolean;
  destroyed: boolean;
  frozen: boolean;
  id: unknown;
  previouslyNewRecord: boolean;

  attributes: any;
}

/** @internal */
export function rememberTransactionRecordState(this: Base): void {
  const r = this as any;
  // Initialize state once per outermost transaction, then increment level for
  // each savepoint. Mirrors Rails' @_start_transaction_state ||= {...}; level += 1.
  if (!r._startTransactionState) {
    const snapshotAttrs = r._attributes.deepDup();
    // Revert any pre-TX dirty changes so the snapshot holds DB baseline values.
    // On rollback, _dirty.snapshot(state.attributes) will then establish the
    // correct original baseline, and redetectChanges will show the right diff.
    const dirtyChanges = r._dirty.changes as Record<string, [unknown, unknown]>;
    for (const [name, [original]] of Object.entries(dirtyChanges)) {
      snapshotAttrs.writeFromUser(name, original);
    }
    r._startTransactionState = {
      newRecord: r._newRecord,
      destroyed: r._destroyed,
      frozen: r._attributes.isFrozen(),
      id: this.id,
      previouslyNewRecord: r._previouslyNewRecord,
      attributes: snapshotAttrs,
      level: 0,
    };
  }
  r._startTransactionState.level += 1;

  // Mirrors Rails' _committed_already_called guard inside remember_transaction_record_state.
  if (r._committedAlreadyCalled) {
    r._newRecordBeforeLastCommit = false;
  } else {
    r._newRecordBeforeLastCommit = r._startTransactionState.newRecord;
  }
}

/**
 * Restore record identity state from a snapshot after a transaction rollback.
 * Does NOT restore tracking flags — those reflect what happened during the
 * transaction and are needed by trigger_transactional_callbacks?.
 *
 * Mirrors: ActiveRecord::Transactions#restore_transaction_record_state
 *
 * @internal
 */
export function restoreTransactionRecordState(
  this: Base,
  snapshot: TransactionRecordSnapshot,
): void {
  const r = this as any;
  r._newRecord = snapshot.newRecord;
  r._destroyed = snapshot.destroyed;
  r._previouslyNewRecord = snapshot.previouslyNewRecord;

  // Unfreeze the attribute set while internal fields are restored so the
  // PK write below always succeeds — even when the snapshot itself was
  // frozen. Mirrors Rails' `restore_transaction_record_state`, which
  // unconditionally reassigns `@attributes` to a fresh mapped set.
  if (r._attributes.isFrozen()) {
    r._attributes = r._attributes.deepDup();
  }

  // Restore the primary key if it was auto-assigned during insert. Must happen
  // before dirty snapshot/redetect so the restored pk is the current value when
  // redetectChanges runs — otherwise a second redetect cannot clear the stale
  // id entry left by the first pass (redetectChanges only sets, never deletes).
  if (snapshot.newRecord && !Array.isArray(this.id)) {
    const ctor = this.constructor as typeof Base;
    const pk = ctor.primaryKey as string;
    if (r._attributes.fetchValue(pk) !== snapshot.id) {
      r._attributes.set(pk, snapshot.id);
    }
  }

  // Restore dirty tracking baseline to pre-transaction state while keeping
  // current in-memory attribute values. Mirrors Rails' attribute map that
  // rebuilds @attributes with snapshotted baseline + current values, so
  // changes() reflects the diff between pre-TX and in-memory state.
  // clearChangesInformation() nullifies previousChanges/mutationsBeforeLastSave
  // matching Rails' @mutations_before_last_save = nil after rollback.
  r._dirty.snapshot(snapshot.attributes);
  r._dirty.clearChangesInformation();
  r._dirty.redetectChanges(r._attributes);

  // Re-apply the snapshot's frozen state *after* any internal restores.
  if (snapshot.frozen && !r._attributes.isFrozen()) {
    r._attributes.freeze();
  }
}

/** @internal */
function _restoreTransactionRecordState(this: Base, forceRestoreState = false): void {
  const r = this as any;
  if (!r._startTransactionState) return;
  const state = r._startTransactionState;
  if (forceRestoreState || state.level <= 1) {
    r._newRecord = state.newRecord;
    r._destroyed = state.destroyed;
    r._previouslyNewRecord = state.previouslyNewRecord;

    // Mirrors Rails restore_transaction_record_state:
    //   @attributes = restore_state[:attributes].map { |attr|
    //     value = @attributes.fetch_value(attr.name)
    //     attr = attr.with_value_from_user(value) if attr.value != value
    //     attr }
    //
    // Rails keeps post-TX user edits in memory by reconstructing each attribute
    // with the post-TX value but the pre-TX attribute as the original_attribute.
    // Our DirtyTracker is external, so we achieve the same observable result by:
    //   1. Setting the dirty baseline to the pre-TX snapshot values
    //   2. Redetecting differences against the current (post-TX) r._attributes
    //
    // r._attributes is NOT replaced — post-TX values stay live in memory.
    // Only the PK is explicitly restored (it is auto-assigned by the DB and
    // is not a user edit worth preserving).

    // Unfreeze in place before writing the restored PK.
    if (r._attributes.isFrozen()) {
      r._attributes = r._attributes.deepDup();
    }

    // Restore primary key to the pre-TX value before redetect runs, so the
    // PK does not appear as a spurious pending change.
    const ctor = this.constructor as typeof Base;
    if (Array.isArray(ctor.primaryKey)) {
      const cols = ctor.primaryKey as string[];
      const savedId = state.id as unknown[];
      if (cols.some((col, i) => r._attributes.fetchValue(col) !== savedId[i])) {
        cols.forEach((col, i) => r._attributes.writeFromUser(col, savedId[i]));
      }
    } else if (r._attributes.fetchValue(ctor.primaryKey as string) !== state.id) {
      r._attributes.writeFromUser(ctor.primaryKey as string, state.id);
    }

    if (state.frozen && !r._attributes.isFrozen()) {
      r._attributes.freeze();
    }

    // Set pre-TX snapshot as the dirty baseline, redetect in-TX edits as dirty.
    // Mirrors Rails: @mutations_from_database = nil; @mutations_before_last_save = nil
    r._dirty.snapshot(state.attributes);
    r._dirty.clearChangesInformation();
    r._dirty.redetectChanges(r._attributes);
  }
}

/**
 * Execute a block within a transaction and capture its return value as a
 * status flag. If the status is falsy (false/null/undefined), the transaction
 * is rolled back. Handles record state snapshotting/restore and callback
 * scheduling.
 *
 * Mirrors: ActiveRecord::Transactions#with_transaction_returning_status
 */
export async function withTransactionReturningStatus<T>(
  this: Base,
  fn: () => Promise<T>,
): Promise<T> {
  const modelClass = this.constructor as typeof Base;

  // _triggerUpdateCallback/_triggerDestroyCallback are NOT reset here; Rails resets
  // those only in committed!/rolledback! ensure blocks.
  const r = this as any;
  r._transactionAction = undefined;

  let status: T;

  // Mirrors Rails' `ensure_finalize = !connection.transaction_open?`.
  const adapter = modelClass.connection;
  const hadOuterTransaction = currentTransaction() !== null || adapter.inTransaction;

  await transaction(modelClass, async () => {
    // Enroll record with the TransactionManager so it fires committedBang/
    // rolledbackBang after the transaction commits or rolls back. The TM-driven
    // rolledbackBang path calls _restoreTransactionRecordState which reads the
    // persistent _startTransactionState snapshot — matching Rails exactly. We
    // intentionally do NOT register a per-call tx.afterRollback hook here: the
    // closure would capture per-save state, and on multi-save rollbacks the
    // last-registered hook would overwrite the correct outermost snapshot.
    await addToTransaction.call(this, !hadOuterTransaction || hasTransactionalCallbacks.call(this));
    rememberTransactionRecordState.call(this);

    status = await fn();
    // Ruby truthiness: only false/nil trigger rollback (0, "" are truthy in Ruby)
    if (status === false || status == null) {
      throw new Rollback();
    }
    return status;
  });

  return status!;
}

/**
 * Mirrors: ActiveRecord::Transactions#_new_record_before_last_commit (attr_accessor)
 */
export function _newRecordBeforeLastCommit(this: Base): boolean {
  return (this as any)._newRecordBeforeLastCommit ?? false;
}

/**
 * Returns whether the record should trigger transactional callbacks.
 *
 * Mirrors: ActiveRecord::Transactions#trigger_transactional_callbacks?
 */
export function isTriggerTransactionalCallbacks(this: Base): boolean {
  const r = this as any;
  // Use === true to avoid prototype method bleeding through as a truthy value.
  const newBeforeLastCommit = r._newRecordBeforeLastCommit === true;
  const triggerUpdate = r._triggerUpdateCallback === true;
  const triggerDestroy = r._triggerDestroyCallback === true;
  return (
    ((newBeforeLastCommit || triggerUpdate) && this.isPersisted()) ||
    (triggerDestroy && this.isDestroyed())
  );
}

// ---------------------------------------------------------------------------
// Private instance helpers — mirrors ActiveRecord::Transactions private block.
// Exported so base.ts can wire them into include(Base, {...}) for api:compare.
// ---------------------------------------------------------------------------

// Mirrors: attr_reader :_committed_already_called
/** @internal */
export function _committedAlreadyCalled(this: Base): boolean | null {
  return (this as any)._committedAlreadyCalled ?? null;
}

// Mirrors: attr_reader :_trigger_update_callback
/** @internal */
export function _triggerUpdateCallback(this: Base): boolean | null {
  return (this as any)._triggerUpdateCallback ?? null;
}

// Mirrors: attr_reader :_trigger_destroy_callback
/** @internal */
export function _triggerDestroyCallback(this: Base): boolean | null {
  return (this as any)._triggerDestroyCallback ?? null;
}

// Mirrors: ActiveRecord::Transactions#init_internals
/** @internal */
function initInternals(record: Base): void {
  const r = record as any;
  r._startTransactionState = null;
  r._committedAlreadyCalled = null;
  r._newRecordBeforeLastCommit = null;
}

// Mirrors: ActiveRecord::Transactions#clear_transaction_record_state
/** @internal */
export function clearTransactionRecordState(this: Base): void {
  const r = this as any;
  if (!r._startTransactionState) return;
  r._startTransactionState.level -= 1;
  if (r._startTransactionState.level < 1) r._startTransactionState = null;
}

// Mirrors: ActiveRecord::Transactions#transaction_include_any_action?
/** @internal */
export function isTransactionIncludeAnyAction(this: Base, actions: string[]): boolean {
  const r = this as any;
  return actions.some((action) => {
    switch (action) {
      case "create":
        return this.isPersisted() && r._newRecordBeforeLastCommit === true;
      case "update":
        return (
          !(r._newRecordBeforeLastCommit || this.isDestroyed()) && r._triggerUpdateCallback === true
        );
      case "destroy":
        return r._triggerDestroyCallback === true;
      default:
        return false;
    }
  });
}

// Mirrors: ActiveRecord::Transactions#add_to_transaction
/** @internal */
export async function addToTransaction(this: Base, ensureFinalize = true): Promise<void> {
  const ctor = this.constructor as any;
  // We're always called from within a transaction, so the adapter IS the
  // current connection — no need to go through withConnection.
  ctor.connection?.addTransactionRecord?.(this, ensureFinalize);
}

// Mirrors: ActiveRecord::Transactions#has_transactional_callbacks?
/** @internal */
export function hasTransactionalCallbacks(this: Base): boolean {
  const proto = (this.constructor as any).prototype;
  const commit = asPeekCallbackChain(proto, "commit");
  if (commit && commit.entries.length > 0) return true;
  const rollback = asPeekCallbackChain(proto, "rollback");
  return !!(rollback && rollback.entries.length > 0);
}

// ---------------------------------------------------------------------------
// Private class helpers — mirrors ActiveRecord::Transactions::ClassMethods private block.
// ---------------------------------------------------------------------------

// Mirrors: ActiveRecord::Transactions::ClassMethods#prepend_option
/** @internal */
function prependOption(this: unknown): Record<string, unknown> {
  return {};
}

const VALID_TRANSACTION_ACTIONS = new Set(["create", "update", "destroy"]);

/**
 * Synthesize an `on:` option into an `if:` predicate before the conditions
 * reach the activemodel chain. Mirrors the transformation Rails performs in
 * `ActiveRecord::Transactions::ClassMethods#set_callback` (transactions.rb:308-315).
 *
 * Returns a new conditions object with `on:` removed and a synthesized `if:`
 * prepended, or the original conditions unchanged when `on:` is absent.
 *
 * @internal
 */
export function synthOnCondition(
  conditions: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
  if (!conditions || conditions.on === undefined) return conditions;
  const fireOn = (Array.isArray(conditions.on) ? conditions.on : [conditions.on]) as string[];
  assertValidTransactionAction(fireOn);
  const { on: _on, if: existingIf, ...rest } = conditions;
  const synthIf = (record: Base): boolean => isTransactionIncludeAnyAction.call(record, fireOn);
  return {
    ...rest,
    if: existingIf
      ? (record: Base) => synthIf(record) && (existingIf as CallbackFn)(record)
      : synthIf,
  };
}

/** @internal Mirrors: ActiveRecord::Transactions::ClassMethods#set_options_for_callbacks! */
export const setOptionsForCallbacksBang = synthOnCondition;

// Mirrors: ActiveRecord::Transactions::ClassMethods#assert_valid_transaction_action
/** @internal */
function assertValidTransactionAction(actions: string[]): void {
  const invalid = actions.filter((a) => !VALID_TRANSACTION_ACTIONS.has(a));
  if (invalid.length > 0) {
    throw new ArgumentError(
      `:on conditions for after_commit and after_rollback callbacks have to be one of [:create, :destroy, :update]`,
    );
  }
}
