/**
 * ActionView::FixtureResolver / ActionView::NullResolver
 *
 * Mirrors `actionview/lib/action_view/testing/resolvers.rb`.
 */

import type { LookupDetails } from "../path-set.js";
import { Template } from "../template.js";
import { TemplatePath } from "../template-path.js";
import { Raw } from "../template/handlers/raw.js";
import { FileSystemResolver, Resolver } from "../template/resolver.js";

/**
 * Use FixtureResolver in your tests to simulate the presence of files on the
 * file system.
 */
export class FixtureResolver extends FileSystemResolver {
  private hash: Record<string, string>;

  constructor(hash: Record<string, string> = {}) {
    super("");
    this.hash = hash;
    this._path = "";
  }

  data(): Record<string, string> {
    return this.hash;
  }

  override toString(): string {
    return Object.keys(this.hash).join(", ");
  }

  /** @internal */
  protected override templateGlob(glob: string): string[] {
    const regex = this.fnmatch(glob, false);
    return Object.keys(this.hash)
      .filter((path) => regex.test(path))
      .map((path) => `/${path}`);
  }

  /** @internal */
  protected override sourceForTemplate(template: string): string {
    return this.hash[template.slice(1)] ?? "";
  }
}

export class NullResolver extends Resolver {
  /** @internal */
  protected override findTemplates(
    name: string,
    prefix: string,
    partial: boolean,
    _details: LookupDetails,
    locals: ReadonlyArray<string> = [],
  ): Template[] {
    const path = TemplatePath.build(name, prefix, partial);
    return [
      new Template({
        source: "Template generated by Null Resolver",
        identifier: path.virtual,
        extension: new Raw().extensions[0],
        virtualPath: path.virtual,
        format: null,
        variant: null,
        locals,
      }),
    ];
  }
}
