/**
 * AttributeMethods module — dynamic attribute method generation.
 *
 * Mirrors: ActiveModel::AttributeMethods
 *
 * In Rails, this module's ClassMethods are mixed into the class via `include`.
 * In TS, the exported functions use `this: AttributeMethodHost` so they can
 * be assigned directly to Model's static side — no delegation wrappers needed.
 */
export interface AttributeMethods {
  hasAttribute(name: string): boolean;
  attributePresent(name: string): boolean;
  attributeMissing(match: AttributeMethodMatch, ...args: unknown[]): unknown;
  respondTo(method: string): boolean;
}

/**
 * Match record passed to `attribute_missing` when a generated
 * per-attribute method (like `name_changed?`, `name_was`, …) is
 * invoked. Mirrors the duck type of Rails'
 * `AttributeMethodMatcher::AttributeMethodMatch` (proxy_target +
 * attr_name fields used by attribute_methods.rb:520-522).
 */
export interface AttributeMethodMatch {
  proxyTarget: string;
  attrName: string;
}

export class MissingAttributeError extends globalThis.Error {
  constructor(message?: string) {
    super(message);
    this.name = "MissingAttributeError";
  }
}

/**
 * attribute_missing — generic dispatch for attribute methods recognized
 * via Rails' method_missing path. In TS we lack method_missing, so the
 * per-attribute methods generated by `defineDirtyAttributeMethods` route
 * through `this.attributeMissing(match, …)` to give subclasses a single
 * intercept hook (matches Rails' `attribute_missing` override pattern).
 *
 * Mirrors: attribute_methods.rb:520-522
 *   def attribute_missing(match, ...)
 *     __send__(match.proxy_target, match.attr_name, ...)
 *   end
 */
export function attributeMissing(
  this: Record<string, unknown>,
  match: AttributeMethodMatch,
  ...args: unknown[]
): unknown {
  const target = (this as Record<string, (...a: unknown[]) => unknown>)[match.proxyTarget];
  if (typeof target !== "function") {
    throw new MissingAttributeError(
      `attribute_missing dispatch failed: ${match.proxyTarget} not defined`,
    );
  }
  return target.call(this, match.attrName, ...args);
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace AttrNames {
  const DEF_SAFE_NAME = /^[a-zA-Z_]\w*$/;

  export function defineAttributeAccessorMethod(
    attrName: string,
    writer: boolean = false,
  ): { methodName: string; attrNameRef: string } {
    const methodName = writer ? `${attrName}=` : attrName;
    if (DEF_SAFE_NAME.test(attrName)) {
      return { methodName, attrNameRef: `'${attrName}'` };
    }
    const escaped = attrName
      .replace(/\\/g, "\\\\")
      .replace(/'/g, "\\'")
      .replace(/\r/g, "\\r")
      .replace(/\n/g, "\\n");
    return { methodName, attrNameRef: `'${escaped}'` };
  }
}

export class AttributeMethodPattern {
  readonly prefix: string;
  readonly suffix: string;
  readonly proxyTarget: string;
  readonly parameters: string;
  readonly method_missing_target: string;

  constructor(prefix: string = "", suffix: string = "", parameters?: string) {
    this.prefix = prefix;
    this.suffix = suffix;
    this.parameters = parameters === undefined ? "..." : parameters;
    this.proxyTarget = `${prefix}attribute${suffix}`;
    this.method_missing_target = `attribute_${prefix}${suffix ? `${suffix}` : ""}`;
  }

  match(method: string): { attr: string } | null {
    if (this.prefix && !method.startsWith(this.prefix)) return null;
    if (this.suffix && !method.endsWith(this.suffix)) return null;
    const attr = method.slice(this.prefix.length, this.suffix ? -this.suffix.length : undefined);
    return attr ? { attr } : null;
  }

  methodName(attrName: string): string {
    return `${this.prefix}${attrName}${this.suffix}`;
  }
}

// ---------------------------------------------------------------------------
// ClassMethods — assigned directly to Model's static side
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRecord = any;

export interface AttributeMethodHost {
  _attributeDefinitions: Map<string, { name: string }>;
  _attributeMethodPatterns: AttributeMethodPattern[];
  _attributeAliases: Record<string, string>;
  _aliasesByAttributeName: Map<string, string[]>;
  _generatedMethods: Set<string>;
  prototype: AnyRecord;
}

function ensureOwnPatterns(host: AttributeMethodHost): void {
  if (!Object.prototype.hasOwnProperty.call(host, "_attributeMethodPatterns")) {
    host._attributeMethodPatterns = [...host._attributeMethodPatterns];
  }
}

function ensureOwnGeneratedMethods(host: AttributeMethodHost): void {
  if (!Object.prototype.hasOwnProperty.call(host, "_generatedMethods")) {
    host._generatedMethods = new Set(host._generatedMethods ?? []);
  }
}

function ensureOwnAliases(host: AttributeMethodHost): void {
  if (!Object.prototype.hasOwnProperty.call(host, "_attributeAliases")) {
    host._attributeAliases = { ...host._attributeAliases };
  }
}

export function aliasesByAttributeName(host: AttributeMethodHost): Map<string, string[]> {
  if (!Object.prototype.hasOwnProperty.call(host, "_aliasesByAttributeName")) {
    const parent = host._aliasesByAttributeName;
    const copy = new Map<string, string[]>();
    if (parent) {
      for (const [k, v] of parent) copy.set(k, [...v]);
    }
    host._aliasesByAttributeName = copy;
  }
  return host._aliasesByAttributeName;
}

// -- Public ClassMethods (use `this`, assigned to Model directly) -----------

export function attributeMethodPrefix(this: AttributeMethodHost, ...prefixes: string[]): void {
  ensureOwnPatterns(this);
  for (const prefix of prefixes) {
    this._attributeMethodPatterns.push(new AttributeMethodPattern(prefix, ""));
  }
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

export function attributeMethodSuffix(this: AttributeMethodHost, ...suffixes: string[]): void {
  ensureOwnPatterns(this);
  for (const suffix of suffixes) {
    this._attributeMethodPatterns.push(new AttributeMethodPattern("", suffix));
  }
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

export function attributeMethodAffix(
  this: AttributeMethodHost,
  ...affixes: Array<{ prefix: string; suffix: string }>
): void {
  ensureOwnPatterns(this);
  for (const { prefix, suffix } of affixes) {
    this._attributeMethodPatterns.push(new AttributeMethodPattern(prefix, suffix));
  }
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

export function aliasAttribute(this: AttributeMethodHost, newName: string, oldName: string): void {
  ensureOwnAliases(this);
  this._attributeAliases[newName] = oldName;
  const aliases = aliasesByAttributeName(this);
  if (!aliases.has(oldName)) aliases.set(oldName, []);
  aliases.get(oldName)!.push(newName);

  // Define the direct alias property (bare name → original)
  ensureOwnGeneratedMethods(this);
  const getter = function (this: AnyRecord) {
    return this.readAttribute(oldName);
  };
  (getter as AnyRecord).__generatedAttributeMethod = true;
  Object.defineProperty(this.prototype, newName, {
    get: getter,
    set(this: AnyRecord, value: unknown) {
      this.writeAttribute(oldName, value);
    },
    configurable: true,
  });
  this._generatedMethods.add(newName);

  // Generate pattern-based alias methods (e.g., clear_fullName if clear_ prefix exists)
  eagerlyGenerateAliasAttributeMethods(this, newName, oldName);
}

export function undefineAttributeMethods(this: AttributeMethodHost): void {
  if (!this._generatedMethods) return;
  for (const methodName of this._generatedMethods) {
    const desc = Object.getOwnPropertyDescriptor(this.prototype, methodName);
    if (!desc) continue;
    // Only delete if the method is still the generated one (has our marker)
    const fn = desc.value ?? desc.get;
    if (fn && (fn as AnyRecord).__generatedAttributeMethod) {
      delete this.prototype[methodName];
    }
  }
  this._generatedMethods.clear();
  // Clear the pattern-match cache so stale entries don't survive after patterns change.
  // Mirrors: Rails attribute_method_patterns_cache.clear in undefine_attribute_methods.
  // Only clear an own-property cache; don't reach up and clear a parent's cache
  // via inherited prototype-chain lookup.
  if (Object.prototype.hasOwnProperty.call(this, "_attributeMethodPatternsCache")) {
    (
      this as AttributeMethodHost & { _attributeMethodPatternsCache: Map<unknown, unknown> }
    )._attributeMethodPatternsCache.clear();
  }
}

export function defineAttributeMethods(this: AttributeMethodHost, ...attrNames: string[]): void {
  for (const attrName of attrNames) {
    defineAttributeMethod(this, attrName);
    const aliases = aliasesByAttributeName(this);
    const attrAliases = aliases.get(attrName);
    if (attrAliases) {
      for (const aliasedName of attrAliases) {
        generateAliasAttributeMethods(this, aliasedName, attrName);
      }
    }
  }
}

// -- Internal helpers (take explicit host arg) --------------------------------

export function defineAttributeMethod(host: AttributeMethodHost, attrName: string): void {
  for (const pattern of host._attributeMethodPatterns) {
    defineAttributeMethodPattern(host, pattern, attrName);
  }
}

export function defineAttributeMethodPattern(
  host: AttributeMethodHost,
  pattern: AttributeMethodPattern,
  attrName: string,
  options?: { override?: boolean },
): void {
  const methodName = pattern.methodName(attrName);
  if (host.prototype[methodName] !== undefined && !options?.override) return;
  ensureOwnGeneratedMethods(host);
  const fn = function (this: AnyRecord) {
    return this.readAttribute(attrName);
  };
  (fn as AnyRecord).__generatedAttributeMethod = true;
  Object.defineProperty(host.prototype, methodName, {
    value: fn,
    writable: true,
    configurable: true,
  });
  host._generatedMethods.add(methodName);
}

export function eagerlyGenerateAliasAttributeMethods(
  host: AttributeMethodHost,
  newName: string,
  oldName: string,
): void {
  generateAliasAttributeMethods(host, newName, oldName);
}

export function generateAliasAttributeMethods(
  host: AttributeMethodHost,
  newName: string,
  oldName: string,
): void {
  for (const pattern of host._attributeMethodPatterns) {
    aliasAttributeMethodDefinition(host, pattern, newName, oldName);
  }
}

export function aliasAttributeMethodDefinition(
  host: AttributeMethodHost,
  pattern: AttributeMethodPattern,
  newName: string,
  oldName: string,
): void {
  const methodName = pattern.methodName(newName);
  const targetName = pattern.methodName(oldName);
  ensureOwnGeneratedMethods(host);
  const fn = function (this: AnyRecord, ...args: unknown[]) {
    const target = this[targetName];
    if (typeof target === "function") {
      return target.apply(this, args);
    }
    return this.readAttribute(oldName);
  };
  (fn as AnyRecord).__generatedAttributeMethod = true;
  Object.defineProperty(host.prototype, methodName, {
    value: fn,
    writable: true,
    configurable: true,
  });
  host._generatedMethods.add(methodName);
}

export function isAttributeAlias(host: AttributeMethodHost, name: string): boolean {
  return Object.prototype.hasOwnProperty.call(host._attributeAliases, name);
}

export function attributeAlias(host: AttributeMethodHost, name: string): string | undefined {
  return host._attributeAliases[name];
}

/**
 * Resolve `name` to its canonical attribute name, following one alias
 * hop. Mirrors Rails `ActiveModel::AttributeMethods#read_attribute`'s
 * `attribute_aliases[name] || name` (activemodel/lib/active_model/attribute_methods.rb
 * read_attribute / write_attribute paths) so every read/write path sees
 * the same key whether the caller passed `nickname` or `name`.
 */
export function resolveAliasName(host: AttributeMethodHost, name: string): string {
  const aliased = host._attributeAliases?.[name];
  return aliased ?? name;
}

// ---------------------------------------------------------------------------
// Class-level Rails privates (attribute_methods.rb)
// ---------------------------------------------------------------------------

const NAME_COMPILABLE_REGEXP = /^[a-zA-Z_]\w*[!?=]?$/;

/** @internal Rails-private helper. Mirrors: ClassMethods#resolve_attribute_name */
export function resolveAttributeName(this: AttributeMethodHost, name: string): string {
  return this._attributeAliases?.[name] ?? name;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#generated_attribute_methods */
export function generatedAttributeMethods(this: AttributeMethodHost): Set<string> {
  return this._generatedMethods;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#instance_method_already_implemented? */
export function isInstanceMethodAlreadyImplemented(
  this: AttributeMethodHost,
  methodName: string,
): boolean {
  return this._generatedMethods?.has(methodName) ?? false;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#attribute_method_patterns_cache */
export function attributeMethodPatternsCache(
  this: AttributeMethodHost,
): Map<string, Array<{ proxyTarget: string; attrName: string }>> {
  const h = this as AttributeMethodHost & {
    _attributeMethodPatternsCache?: Map<string, Array<{ proxyTarget: string; attrName: string }>>;
  };
  if (!Object.prototype.hasOwnProperty.call(h, "_attributeMethodPatternsCache")) {
    h._attributeMethodPatternsCache = new Map();
  }
  return h._attributeMethodPatternsCache!;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#attribute_method_patterns_matching */
export function attributeMethodPatternsMatching(
  this: AttributeMethodHost,
  methodName: string,
): Array<{ proxyTarget: string; attrName: string }> {
  const cache = attributeMethodPatternsCache.call(this);
  if (cache.has(methodName)) return cache.get(methodName)!;
  const matches = this._attributeMethodPatterns.flatMap((pattern) => {
    const m = pattern.match(methodName);
    return m ? [{ proxyTarget: pattern.proxyTarget, attrName: m.attr }] : [];
  });
  cache.set(methodName, matches);
  return matches;
}

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#build_mangled_name
 * Returns a compilable temp name for attributes with non-identifier characters.
 */
export function buildMangledName(this: AttributeMethodHost, name: string): string {
  if (NAME_COMPILABLE_REGEXP.test(name)) return name;
  const hex = Array.from(name)
    .map((c) => c.charCodeAt(0).toString(16).padStart(2, "0"))
    .join("");
  return `__temp__${hex}`;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#define_proxy_call */
export function defineProxyCall(
  this: AttributeMethodHost,
  name: string,
  proxyTarget: string,
  _parameters: string | null,
  attrName: string,
): void {
  ensureOwnGeneratedMethods(this);
  const fn = function (this: AnyRecord, ...args: unknown[]) {
    const handler = this[proxyTarget];
    if (typeof handler !== "function") {
      throw new MissingAttributeError(
        `attribute_missing dispatch failed: ${proxyTarget} not defined`,
      );
    }
    return handler.call(this, attrName, ...args);
  };
  (fn as AnyRecord).__generatedAttributeMethod = true;
  Object.defineProperty(this.prototype, name, { value: fn, writable: true, configurable: true });
  this._generatedMethods.add(name);
}

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#define_call
 * Trails has no eval/code generation, so delegates to defineProxyCall.
 */
export function defineCall(
  this: AttributeMethodHost,
  name: string,
  targetName: string,
  _mangledName: string,
  _parameters: string | null,
  attrName: string,
): void {
  defineProxyCall.call(this, name, targetName, _parameters, attrName);
}

// ---------------------------------------------------------------------------
// Instance-level Rails privates (attribute_methods.rb)
// ---------------------------------------------------------------------------

type InstanceHost = {
  _attributes?: { has(name: string): boolean };
  _attributeMethodPatterns?: AttributeMethodPattern[];
  constructor: AttributeMethodHost;
};

/** @internal Rails-private helper. Mirrors: #attribute_method? */
export function isAttributeMethod(this: InstanceHost, attrName: string): boolean {
  return this._attributes?.has(attrName) ?? false;
}

/** @internal Rails-private helper. Mirrors: #matched_attribute_method */
export function matchedAttributeMethod(
  this: InstanceHost,
  methodName: string,
): { proxyTarget: string; attrName: string } | null {
  const matches = attributeMethodPatternsMatching.call(
    this.constructor as AttributeMethodHost,
    methodName,
  );
  return matches.find((m) => isAttributeMethod.call(this, m.attrName)) ?? null;
}

/** @internal Rails-private helper. Mirrors: #missing_attribute */
export function missingAttribute(this: InstanceHost, attrName: string): never {
  throw new MissingAttributeError(
    `missing attribute '${attrName}' for ${(this.constructor as { name?: string }).name ?? "unknown"}`,
  );
}

/**
 * @internal Rails-private helper. Mirrors: #_read_attribute
 * Bypasses alias resolution and reads directly from the attribute store,
 * matching Rails AR _read_attribute (fetch_value without alias lookup).
 */
export function _readAttribute(
  this: InstanceHost & {
    _attributes?: { fetchValue(name: string): unknown };
    _readAttribute?(name: string): unknown;
  },
  attr: string,
): unknown {
  if (typeof this._readAttribute === "function" && this._readAttribute !== _readAttribute) {
    return this._readAttribute(attr);
  }
  return this._attributes?.fetchValue(attr) ?? null;
}
