/**
 * AttributeMethods module — dynamic attribute method generation.
 *
 * Mirrors: ActiveModel::AttributeMethods
 *
 * In Rails, this module's ClassMethods are mixed into the class via `include`.
 * In TS, the exported functions use `this: AttributeMethodHost` so they can
 * be assigned directly to Model's static side — no delegation wrappers needed.
 */
import { camelize, CodeGenerator, include, Module } from "@blazetrails/activesupport";

export interface AttributeMethods {
  hasAttribute(name: string): boolean;
  attributePresent(name: string): boolean;
  attributeMissing(match: AttributeMethodMatch, ...args: unknown[]): unknown;
  respondTo(method: string): boolean;
}

/**
 * Match record passed to `attribute_missing` when a generated
 * per-attribute method (like `name_changed?`, `name_was`, …) is
 * invoked. Mirrors the duck type of Rails'
 * `AttributeMethodMatcher::AttributeMethodMatch` (proxy_target +
 * attr_name fields used by attribute_methods.rb:520-522).
 */
export interface AttributeMethodMatch {
  proxyTarget: string;
  attrName: string;
}

/**
 * Rails threads `__FILE__, __LINE__` into every `CodeGenerator.batch` so the
 * `module_eval` it performs reports a real source location. The port defines
 * methods directly instead of evaluating source, so the pair is inert — it is
 * still passed, under the Ruby names, because `batch`'s signature is Rails'
 * (code_generator.rb:39).
 */
const __FILE__ = import.meta.url;
const __LINE__ = 0;

export class MissingAttributeError extends globalThis.Error {
  constructor(message?: string) {
    super(message);
    this.name = "MissingAttributeError";
  }
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace AttrNames {
  const DEF_SAFE_NAME = /^[a-zA-Z_]\w*$/;

  export function defineAttributeAccessorMethod(
    owner: unknown,
    attrName: string,
    { writer = false }: { writer?: boolean } = {},
  ): { methodName: string; attrNameRef: string } {
    const methodName = writer ? `${attrName}=` : attrName;
    if (DEF_SAFE_NAME.test(attrName)) {
      return { methodName, attrNameRef: `'${attrName}'` };
    }
    const escaped = attrName
      .replace(/\\/g, "\\\\")
      .replace(/'/g, "\\'")
      .replace(/\r/g, "\\r")
      .replace(/\n/g, "\\n");
    return { methodName, attrNameRef: `'${escaped}'` };
  }
}

export class AttributeMethodPattern {
  readonly prefix: string;
  readonly suffix: string;
  readonly proxyTarget: string;
  readonly parameters: string | false;

  constructor({
    prefix = "",
    suffix = "",
    parameters = null,
  }: { prefix?: string; suffix?: string; parameters?: string | null | false } = {}) {
    this.prefix = prefix;
    this.suffix = suffix;
    this.parameters = parameters == null ? "..." : parameters;
    this.proxyTarget = `${prefix}attribute${suffix}`;
  }

  match(method: string): { attr: string } | null {
    if (this.prefix && !method.startsWith(this.prefix)) return null;
    if (this.suffix && !method.endsWith(this.suffix)) return null;
    const attr = method.slice(this.prefix.length, this.suffix ? -this.suffix.length : undefined);
    return attr ? { attr } : null;
  }

  methodName(attrName: string): string {
    return `${this.prefix}${attrName}${this.suffix}`;
  }
}

// ---------------------------------------------------------------------------
// ClassMethods — assigned directly to Model's static side
// ---------------------------------------------------------------------------

/** Minimum shape required of an instance accessed through a generated attribute method closure. */
interface ReadWriteHost {
  readAttribute(name: string): unknown;
  writeAttribute(name: string, value: unknown): void;
  [key: string]: unknown;
}

export interface AttributeMethodHost {
  _attributeDefinitions: Map<string, { name: string }>;
  attributeMethodPatterns: AttributeMethodPattern[];
  attributeAliases: Record<string, string>;
  _aliasesByAttributeName: Map<string, string[]>;
  _generatedAttributeMethods?: Module;
}

/**
 * attribute_missing — generic dispatch for attribute methods recognized
 * via Rails' method_missing path. In TS we lack method_missing, so the
 * per-attribute methods generated by `defineDirtyAttributeMethods` route
 * through `this.attributeMissing(match, …)` to give subclasses a single
 * intercept hook (matches Rails' `attribute_missing` override pattern).
 *
 * Mirrors: attribute_methods.rb:520-522
 *   def attribute_missing(match, ...)
 *     __send__(match.proxy_target, match.attr_name, ...)
 *   end
 */
export function attributeMissing(
  this: Record<string, unknown>,
  match: AttributeMethodMatch,
  ...args: unknown[]
): unknown {
  const target = (this as Record<string, (...a: unknown[]) => unknown>)[match.proxyTarget];
  if (typeof target !== "function") {
    throw new MissingAttributeError(
      `attribute_missing dispatch failed: ${match.proxyTarget} not defined`,
    );
  }
  return target.call(this, match.attrName, ...args);
}

/**
 * Mirrors: #respond_to_without_attributes? — the alias Rails captures for the
 * original `respond_to?` before overriding it (attribute_methods.rb:527-528,
 * `alias :respond_to_without_attributes? :respond_to?`). It keeps the
 * `respond_to?(method, include_private_methods = false)` signature and answers
 * whether the receiver responds to `method` at all — including attribute
 * accessors exposed as getter/setter properties, not just plain functions. The
 * `in` check mirrors Ruby `respond_to?` across the prototype chain; trails has
 * no Ruby-private methods, so `includePrivateMethods` is accepted for signature
 * fidelity but does not change the answer.
 */
export function isRespondToWithoutAttributes(
  this: object,
  method: string,
  includePrivateMethods: boolean = false,
): boolean {
  void includePrivateMethods;
  return method in (this as Record<string, unknown>);
}

/** @internal Rails-private helper. Mirrors: #attribute_method? */
export function isAttributeMethod(this: InstanceHost, attrName: string): boolean {
  return this._attributes?.has(attrName) ?? false;
}

/** @internal Rails-private helper. Mirrors: #matched_attribute_method */
export function matchedAttributeMethod(
  this: InstanceHost,
  methodName: string,
): { proxyTarget: string; attrName: string } | null {
  const matches = attributeMethodPatternsMatching.call(this.constructor, methodName);
  return matches.find((m) => isAttributeMethod.call(this, m.attrName)) ?? null;
}

/**
 * @internal Rails-private helper. Mirrors: #missing_attribute
 * Rails passes `stack` (a `caller` backtrace) so `raise` reports the call site
 * rather than this helper; JS `Error` captures its own stack, so when a `stack`
 * string is supplied we overwrite the error's stack to match Rails' intent.
 */
export function missingAttribute(this: InstanceHost, attrName: string, stack?: string): never {
  const err = new MissingAttributeError(
    `missing attribute '${attrName}' for ${(this.constructor as { name?: string }).name ?? "unknown"}`,
  );
  if (stack !== undefined) err.stack = stack;
  throw err;
}

/**
 * @internal Rails-private helper. Mirrors: #_read_attribute
 * Bypasses alias resolution and reads directly from the attribute store,
 * matching Rails AR _read_attribute (fetch_value without alias lookup).
 */
export function _readAttribute(
  this: InstanceHost & {
    _attributes?: { fetchValue(name: string, block?: (name: string) => unknown): unknown };
    _readAttribute?(name: string, block?: (name: string) => unknown): unknown;
  },
  attr: string,
  block?: (name: string) => unknown,
): unknown {
  if (typeof this._readAttribute === "function" && this._readAttribute !== _readAttribute) {
    return this._readAttribute(attr, block);
  }
  return this._attributes?.fetchValue(attr, block) ?? null;
}

/**
 * Mirrors Rails' `attribute_method_prefix(*prefixes, parameters: nil)`
 * (attribute_methods.rb:106-109). TS forbids a keyword after a rest element, so
 * the trailing `parameters:` hash rides in the splat and is peeled off — the
 * same shape `touch(*names, time:)` uses in `activerecord/timestamp.ts`.
 *
 * Rails stops at `undefine_attribute_methods` and regenerates a late-declared
 * pattern lazily via `method_missing` (attribute_methods.rb:504-518). JS has no
 * `method_missing`, so the `defineAttributeMethods` call here — and in
 * `attributeMethodSuffix` / `attributeMethodAffix` — materializes it eagerly.
 */
export function attributeMethodPrefix(
  this: AttributeMethodHost,
  ...prefixes: Array<string | { parameters?: string | null | false }>
): void {
  const parameters = extractParameters(prefixes);
  this.attributeMethodPatterns = [
    ...this.attributeMethodPatterns,
    ...(prefixes as string[]).map((prefix) => new AttributeMethodPattern({ prefix, parameters })),
  ];
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

/** Mirrors: ClassMethods#attribute_method_suffix (attribute_methods.rb:140-143). */
export function attributeMethodSuffix(
  this: AttributeMethodHost,
  ...suffixes: Array<string | { parameters?: string | null | false }>
): void {
  const parameters = extractParameters(suffixes);
  this.attributeMethodPatterns = [
    ...this.attributeMethodPatterns,
    ...(suffixes as string[]).map((suffix) => new AttributeMethodPattern({ suffix, parameters })),
  ];
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

/** Mirrors: ClassMethods#attribute_method_affix (attribute_methods.rb:175-178). */
export function attributeMethodAffix(
  this: AttributeMethodHost,
  ...affixes: Array<{ prefix: string; suffix: string }>
): void {
  this.attributeMethodPatterns = [
    ...this.attributeMethodPatterns,
    ...affixes.map((affix) => new AttributeMethodPattern(affix)),
  ];
  undefineAttributeMethods.call(this);
  defineAttributeMethods.call(this, ...Array.from(this._attributeDefinitions.keys()));
}

export function aliasAttribute(this: AttributeMethodHost, newName: string, oldName: string): void {
  this.attributeAliases = { ...this.attributeAliases, [newName]: oldName };
  const aliases = aliasesByAttributeName(this);
  if (!aliases.has(oldName)) aliases.set(oldName, []);
  aliases.get(oldName)!.push(newName);

  // Generate pattern-based alias methods. The default bare pattern emits the
  // direct alias accessor (bare name → original); affix patterns (e.g.
  // `clear_fullName` if a `clear_` prefix exists) emit their proxy methods.
  eagerlyGenerateAliasAttributeMethods.call(this, newName, oldName);
  // Generate dirty predicates (nameChanged, nameWas, etc.) for the alias name.
  // Rails generates these via attribute_method_suffix/affix declarations; we do
  // it explicitly so titleChanged? delegates to attributeChanged("title") which
  // resolves the alias at runtime.
  defineDirtyAttributeMethods.call(this, newName);
}

export function eagerlyGenerateAliasAttributeMethods(
  this: AttributeMethodHost,
  newName: string,
  oldName: string,
): void {
  CodeGenerator.batch(generatedAttributeMethods.call(this), __FILE__, __LINE__, (codeGenerator) => {
    generateAliasAttributeMethods(this, codeGenerator, newName, oldName);
  });
}

export function generateAliasAttributeMethods(
  host: AttributeMethodHost,
  codeGenerator: CodeGenerator,
  newName: string,
  oldName: string,
): void {
  CodeGenerator.batch(codeGenerator, __FILE__, __LINE__, () => {
    for (const pattern of host.attributeMethodPatterns) {
      aliasAttributeMethodDefinition.call(host, codeGenerator, pattern, newName, oldName);
    }
    attributeMethodPatternsCache.call(host).clear();
  });
}

/**
 * Mirrors: ActiveRecord::AttributeMethods::ClassMethods#alias_attribute_method_definition
 * (activerecord/attribute_methods.rb:87-96) — the alias is generated by the
 * same pattern path as a regular attribute method, under the alias' name and
 * with the override arm on.
 */
export function aliasAttributeMethodDefinition(
  this: AttributeMethodHost,
  codeGenerator: CodeGenerator,
  pattern: AttributeMethodPattern,
  newName: string,
  oldName: string,
): void {
  defineAttributeMethodPattern.call(this, pattern, oldName, {
    owner: codeGenerator,
    as: newName,
    override: true,
  });
}

export function isAttributeAlias(host: AttributeMethodHost, name: string): boolean {
  return Object.prototype.hasOwnProperty.call(host.attributeAliases, name);
}

export function attributeAlias(host: AttributeMethodHost, name: string): string | undefined {
  return host.attributeAliases[name];
}

export function defineAttributeMethods(this: AttributeMethodHost, ...attrNames: string[]): void {
  CodeGenerator.batch(generatedAttributeMethods.call(this), __FILE__, __LINE__, (owner) => {
    for (const attrName of attrNames) {
      defineAttributeMethod.call(this, attrName, { _owner: owner });
      const aliases = aliasesByAttributeName(this);
      const attrAliases = aliases.get(attrName);
      if (attrAliases) {
        for (const aliasedName of attrAliases) {
          generateAliasAttributeMethods(this, owner, aliasedName, attrName);
        }
      }
    }
  });
}

// -- Internal helpers (take explicit host arg) --------------------------------

export function defineAttributeMethod(
  this: AttributeMethodHost,
  attrName: string,
  {
    _owner = generatedAttributeMethods.call(this),
    as = attrName,
  }: { _owner?: Module | CodeGenerator; as?: string } = {},
): void {
  CodeGenerator.batch(_owner, __FILE__, __LINE__, (owner) => {
    for (const pattern of this.attributeMethodPatterns) {
      defineAttributeMethodPattern.call(this, pattern, attrName, { owner, as });
    }
    defineDirtyAttributeMethods.call(this, as);
    attributeMethodPatternsCache.call(this).clear();
  });
}

// ---------------------------------------------------------------------------
// Class-level Rails privates (attribute_methods.rb)
// ---------------------------------------------------------------------------

const NAME_COMPILABLE_REGEXP = /^[a-zA-Z_]\w*[!?=]?$/;

/**
 * Mirrors: ClassMethods#define_attribute_method_pattern
 *
 * ActiveModel's `instance_method_already_implemented?` only consults the
 * generated module. The extra prototype arm of the guard stands in for
 * ActiveRecord's override of that predicate, which also rejects a name the
 * class itself defines; trails has one host interface for both, so the arm
 * lives at this call site.
 *
 * Rails' only `override: true` caller is `alias_attribute_method_definition`
 * (activerecord/attribute_methods.rb:94), and so is trails'.
 *
 * `"define_method_#{pattern.proxy_target}"` (attribute_methods.rb:333) is
 * spelled out rather than interpolated: a proxy target ending in `=` names a
 * Ruby writer, whose bare camel spelling belongs to the reader hook of the same
 * name, so it takes the `set*` fallback docs/ruby-ts-conventions.md gives a
 * `name=` writer.
 */
export function defineAttributeMethodPattern(
  this: AttributeMethodHost,
  pattern: AttributeMethodPattern,
  attrName: string,
  { owner, as, override = false }: { owner: CodeGenerator; as: string; override?: boolean },
): void {
  const canonicalMethodName = pattern.methodName(attrName);
  const publicMethodName = pattern.methodName(as);

  // If defining a regular attribute method, we don't override methods that are
  // explicitly defined in parent classes (attribute_methods.rb:326). The
  // predicate is a template method: Ruby dispatches it through the class, and
  // ActiveRecord overrides it to raise DangerousAttributeError for a name
  // Active Record itself defines and to consult the class's own methods
  // (activerecord/attribute_methods.rb:165-179).
  const alreadyImplemented = (this as unknown as Record<string, unknown>)
    .isInstanceMethodAlreadyImplemented;
  if (
    typeof alreadyImplemented === "function"
      ? (alreadyImplemented as (methodName: string) => boolean).call(this, publicMethodName)
      : isInstanceMethodAlreadyImplemented.call(this, publicMethodName)
  ) {
    // However, for `alias_attribute`, we always define the method.
    if (!override) return;
  }

  const generateMethod = pattern.proxyTarget.endsWith("=")
    ? camelize(`set_define_method_${pattern.proxyTarget.slice(0, -1)}`, false)
    : camelize(`define_method_${pattern.proxyTarget}`, false);

  const generator = (this as unknown as Record<string, unknown>)[generateMethod];
  if (typeof generator === "function") {
    (generator as (attrName: string, options: { owner: CodeGenerator; as: string }) => void).call(
      this,
      attrName,
      { owner, as },
    );
  } else {
    defineProxyCall(owner, canonicalMethodName, pattern.proxyTarget, pattern.parameters, attrName, {
      namespace: "active_model_proxy",
      as: publicMethodName,
    });
  }
}

export function undefineAttributeMethods(this: AttributeMethodHost): void {
  const mod = generatedAttributeMethods.call(this);
  mod.undefMethod(...mod.instanceMethods());
  // Clear the pattern-match cache so stale entries don't survive after patterns change.
  // Mirrors: Rails attribute_method_patterns_cache.clear in undefine_attribute_methods.
  // Only clear an own-property cache; don't reach up and clear a parent's cache
  // via inherited prototype-chain lookup.
  if (Object.prototype.hasOwnProperty.call(this, "_attributeMethodPatternsCache")) {
    (
      this as AttributeMethodHost & { _attributeMethodPatternsCache: Map<unknown, unknown> }
    )._attributeMethodPatternsCache.clear();
  }
}

export function aliasesByAttributeName(host: AttributeMethodHost): Map<string, string[]> {
  if (!Object.prototype.hasOwnProperty.call(host, "_aliasesByAttributeName")) {
    const parent = host._aliasesByAttributeName;
    const copy = new Map<string, string[]>();
    if (parent) {
      for (const [k, v] of parent) copy.set(k, [...v]);
    }
    host._aliasesByAttributeName = copy;
  }
  return host._aliasesByAttributeName;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#resolve_attribute_name */
export function resolveAttributeName(this: AttributeMethodHost, name: string): string {
  return this.attributeAliases?.[name] ?? name;
}

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#generated_attribute_methods
 *
 *   def generated_attribute_methods
 *     @generated_attribute_methods ||= Module.new.tap { |mod| include mod }
 *   end
 *
 * (attribute_methods.rb:400-402.) The `||=` is on a per-class ivar, so the
 * memo is checked as an *own* property: a subclass must build and include its
 * own module rather than reusing the one it inherits from its parent, which is
 * what Ruby's per-class ivar (reset in `inherited`, attribute_methods.rb:386-393)
 * gives for free.
 */
export function generatedAttributeMethods(this: AttributeMethodHost): Module {
  if (!Object.prototype.hasOwnProperty.call(this, "_generatedAttributeMethods")) {
    const mod = new Module();
    include(this as unknown as new (...args: unknown[]) => unknown, mod);
    this._generatedAttributeMethods = mod;
  }
  return this._generatedAttributeMethods!;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#instance_method_already_implemented? */
export function isInstanceMethodAlreadyImplemented(
  this: AttributeMethodHost,
  methodName: string,
): boolean {
  return generatedAttributeMethods.call(this).isMethodDefined(methodName);
}

/** @internal Rails-private helper. Mirrors: ClassMethods#attribute_method_patterns_cache */
export function attributeMethodPatternsCache(
  this: AttributeMethodHost,
): Map<string, Array<{ proxyTarget: string; attrName: string }>> {
  const h = this as AttributeMethodHost & {
    _attributeMethodPatternsCache?: Map<string, Array<{ proxyTarget: string; attrName: string }>>;
  };
  if (!Object.prototype.hasOwnProperty.call(h, "_attributeMethodPatternsCache")) {
    h._attributeMethodPatternsCache = new Map();
  }
  return h._attributeMethodPatternsCache!;
}

/** @internal Rails-private helper. Mirrors: ClassMethods#attribute_method_patterns_matching */
export function attributeMethodPatternsMatching(
  this: AttributeMethodHost,
  methodName: string,
): Array<{ proxyTarget: string; attrName: string }> {
  const cache = attributeMethodPatternsCache.call(this);
  if (cache.has(methodName)) return cache.get(methodName)!;
  const matches = this.attributeMethodPatterns.flatMap((pattern) => {
    const m = pattern.match(methodName);
    return m ? [{ proxyTarget: pattern.proxyTarget, attrName: m.attr }] : [];
  });
  cache.set(methodName, matches);
  return matches;
}

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#define_proxy_call
 *
 * Ruby's `(code_generator, name, proxy_target, parameters, *call_args,
 * namespace:, as:)` puts required keywords after a splat, which TS cannot
 * express: the kwargs travel as the last element of the rest tuple.
 *
 * Two steps of attribute_methods.rb:408-424 have no TS analogue and are
 * dropped rather than emulated: `call_args.map!(&:inspect)` quotes each
 * argument for the Ruby source string, where the port passes the values
 * themselves, and `call_args << parameters if parameters` appends the
 * forwarding signature, which `defineCall`'s rest parameter already does.
 */
export function defineProxyCall(
  codeGenerator: CodeGenerator,
  name: string,
  proxyTarget: string,
  parameters: string | null | false,
  ...rest: [...callArgs: string[], options: { namespace: string; as?: string }]
): void {
  const options = rest[rest.length - 1] as { namespace: string; as?: string };
  const callArgs = rest.slice(0, -1) as string[];
  const mangledName = buildMangledName(name);

  // We have to use a different namespace for every target method, because if
  // someone defines an attribute that looks like an attribute method we could
  // clash, e.g. `attribute :title_was` / `attribute :title`.
  const namespace = `${options.namespace}_${proxyTarget}`;

  defineCall(codeGenerator, name, proxyTarget, mangledName, parameters, callArgs, {
    namespace,
    as: options.as ?? name,
  });
}

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#build_mangled_name
 * Returns a compilable temp name for attributes with non-identifier characters.
 */
export function buildMangledName(name: string): string {
  if (NAME_COMPILABLE_REGEXP.test(name)) return name;
  const hex = Array.from(name)
    .map((c) => c.charCodeAt(0).toString(16).padStart(2, "0"))
    .join("");
  return `__temp__${hex}`;
}

// ---------------------------------------------------------------------------
// Instance-level Rails privates (attribute_methods.rb)
// ---------------------------------------------------------------------------

export type InstanceHost = {
  _attributes?: { has(name: string): boolean };
  attributeMethodPatterns?: AttributeMethodPattern[];
  constructor: AttributeMethodHost;
};

/**
 * @internal Rails-private helper. Mirrors: ClassMethods#define_call
 *
 * Rails compiles `def mangled_name(params); self.target_name(call_args); end`
 * into the generator's batch. A TS "source" is the definition itself, so the
 * emitted body is the equivalent closure over `callArgs`; a rest parameter
 * forwards what Ruby's `params` names, so `parameters` only matters when it is
 * `false` — `def #{mangled_name}(#{parameters || ''})` (attribute_methods.rb:465)
 * is then a zero-arg reader, which is an accessor property in TS (CLAUDE.md,
 * "Generated attribute readers are properties"). A `parameters: false` pattern
 * (before_type_cast.rb:32, query.rb:10) is NOT nil, so it survives as `false`.
 * `CALL_COMPILABLE_REGEXP` has no analogue either: a JS property lookup needs
 * no name to be compilable, so the `send(...)` arm it guards never applies.
 * `name` is unused here exactly as it is in Ruby.
 */
export function defineCall(
  codeGenerator: CodeGenerator,
  _name: string,
  targetName: string,
  mangledName: string,
  parameters: string | null | false,
  callArgs: string[],
  { namespace, as }: { namespace: string; as: string },
): void {
  codeGenerator.defineCachedMethod(mangledName, { namespace, as }, (batch) => {
    batch.push((mod) => {
      if (parameters === false) {
        Object.defineProperty(mod, mangledName, {
          get(this: ReadWriteHost) {
            const target = this[targetName] as (...a: unknown[]) => unknown;
            return target.call(this, ...callArgs);
          },
          configurable: true,
        });
        return;
      }
      Object.defineProperty(mod, mangledName, {
        value: function (this: ReadWriteHost, ...args: unknown[]) {
          const target = this[targetName] as (...a: unknown[]) => unknown;
          return target.call(this, ...callArgs, ...args);
        },
        writable: true,
        configurable: true,
      });
    });
  });
}

// -- Public ClassMethods (use `this`, assigned to Model directly) -----------

/**
 * @noRailsEquivalent Peels Ruby's trailing `parameters:` keyword back off the
 * splat that carries it — the arg-shape half of `attribute_method_prefix` /
 * `attribute_method_suffix`, which TS cannot spell as a real keyword after a
 * rest element.
 */
function extractParameters(
  affixes: Array<string | { parameters?: string | null | false }>,
): string | null | false {
  const last = affixes[affixes.length - 1];
  if (last === undefined || typeof last === "string") return null;
  affixes.pop();
  return last.parameters ?? null;
}

/**
 * Whether a class body — as opposed to a generated attribute-methods module —
 * answers `name` anywhere up the chain. `include()` splices a module's carrier
 * directly below the including class's prototype, and a carrier has no own
 * `constructor`, which is what tells the two apart; that is the JS spelling of
 * Rails' `!superclass.instance_method(name).owner.is_a?(GeneratedAttributeMethods)`
 * (activerecord/attribute_methods.rb:170-176).
 *
 * @noRailsEquivalent PERMANENT. The shadowing consequence of the repo-wide
 * "generated attribute readers are properties" rule (CLAUDE.md, "Generated
 * attribute readers are properties"); see there rather than re-deriving it.
 * Pinned by "attribute named toJSON does not shadow Model#toJSON". ActiveRecord
 * needs none of this: its `instance_method_already_implemented?` override
 * (attribute_methods.rb:165-179) rejects such a name before the hook runs.
 */
function isDefinedByAClassBody(klass: unknown, name: string): boolean {
  const start = (klass as { prototype?: object }).prototype;
  for (
    let link: object | null = start ?? null;
    link;
    link = Object.getPrototypeOf(link) as object | null
  ) {
    if (!Object.prototype.hasOwnProperty.call(link, name)) continue;
    return Object.prototype.hasOwnProperty.call(link, "constructor");
  }
  return false;
}

/**
 * @noRailsEquivalent PERMANENT. ActiveModel has no `define_method_attribute`:
 * for a plain `ActiveModel::Attributes` includer,
 * `respond_to?("define_method_attribute", true)` is false, so the bare pattern
 * takes the `else` branch of attribute_methods.rb:333-346 and
 * `define_proxy_call` generates the ordinary method
 * `def name; attribute("name"); end`, dispatching to the private instance
 * method `attribute(attr_name)` (attributes.rb:161). Only ActiveRecord defines
 * the hook (attribute_methods/read.rb:11). trails needs it in ActiveModel too,
 * and this descriptor carries the `set` half as well — both are consequences of
 * the repo-wide "generated attribute readers are properties" rule (CLAUDE.md,
 * "Generated attribute readers are properties"), which is where that decision
 * is ratified; it is not re-argued here.
 */
export function defineMethodAttribute(
  this: unknown,
  canonicalName: string,
  { owner, as = canonicalName }: { owner: CodeGenerator; as?: string },
): void {
  if (as === canonicalName && isDefinedByAClassBody(this, as)) return;
  const { methodName } = AttrNames.defineAttributeAccessorMethod(owner, canonicalName);
  const mangledName = buildMangledName(methodName);
  owner.defineCachedMethod(mangledName, { namespace: "active_model", as }, (sources) => {
    sources.push((mod) => {
      Object.defineProperty(mod, mangledName, {
        get(
          this: ReadWriteHost & {
            _attributes: { getAttribute(n: string): { isInitialized(): boolean } };
          },
        ) {
          if (!this._attributes.getAttribute(canonicalName).isInitialized()) {
            throw new MissingAttributeError(
              `missing attribute '${canonicalName}' for ${(this.constructor as { name?: string }).name ?? "unknown"}`,
            );
          }
          return this.readAttribute(canonicalName);
        },
        set(this: ReadWriteHost, value: unknown) {
          this.writeAttribute(canonicalName, value);
        },
        configurable: true,
      });
    });
  });
}

/**
 * Generate per-attribute dirty methods into the class's
 * `generated_attribute_methods` module, mirroring the method cascade Rails
 * produces via `attribute_method_suffix` / `attribute_method_affix`
 * declarations in activemodel/lib/active_model/dirty.rb.
 *
 * For an attribute `name` the generated methods are:
 *   nameChanged, nameChange, nameWas,
 *   nameInDatabase, nameBeforeLastSave,
 *   namePreviouslyChanged, namePreviousChange, namePreviouslyWas,
 *   savedChangeToName, willSaveChangeToName,
 *   restoreName
 *
 * Each forwards to the corresponding generic `attributeX(name, ...)` on
 * Model, so subclasses can override the generic and have the
 * per-attribute form pick up the change automatically.
 *
 * The owner is `generated_attribute_methods` (attribute_methods.rb:400-402), as
 * it is for every other generated attribute method: Rails declares this cascade
 * with `attribute_method_suffix` (dirty.rb), so the whole set is generated by
 * the `define_attribute_methods` path into that module. That makes
 * `instance_method_already_implemented?` the one guard, dispatched through the
 * class exactly as `define_attribute_method_pattern` dispatches it
 * (attribute_methods.rb:326) — a class-body method outranks the module and
 * survives, an inherited GENERATED one does not count as hand-written — and it
 * makes `undefine_attribute_methods` clear the cascade.
 *
 * @noRailsEquivalent CONVERGEABLE — Rails declares this cascade as
 * `attribute_method_suffix` / `attribute_method_affix` patterns (dirty.rb:241-245,
 * plus AR's `saved_change_to_*` set in activerecord/attribute_methods/dirty.rb)
 * and lets `define_attribute_methods` walk them (attribute_methods.rb:313-316);
 * this stands in for that walk. Blocked on `methodName` concatenating
 * `prefix + attrName + suffix`, which cannot produce a camelCased
 * `savedChangeToName`, and on the cascade spanning both packages. Story:
 * 0096-naming-identifier-burndown/declare-dirty-cascade-as-attribute-method-suffix-patterns.
 */
export function defineDirtyAttributeMethods(this: AttributeMethodHost, attrName: string): void {
  const cap = attrName.charAt(0).toUpperCase() + attrName.slice(1);
  const binding: Array<[string, string]> = [
    [`${attrName}Changed`, "attributeChanged"],
    [`${attrName}Change`, "attributeChange"],
    [`${attrName}Was`, "attributeWas"],
    [`${attrName}WillChange`, "attributeWillChange"],
    [`${attrName}InDatabase`, "attributeInDatabase"],
    [`${attrName}BeforeLastSave`, "attributeBeforeLastSave"],
    [`${attrName}PreviouslyChanged`, "attributePreviouslyChanged"],
    [`${attrName}PreviousChange`, "attributePreviousChange"],
    [`${attrName}PreviouslyWas`, "attributePreviouslyWas"],
    [`savedChangeTo${cap}`, "savedChangeToAttribute"],
    [`willSaveChangeTo${cap}`, "willSaveChangeToAttribute"],
    [`restore${cap}`, "restoreAttribute"],
  ];
  const mod = generatedAttributeMethods.call(this);
  const alreadyImplemented = (this as unknown as Record<string, unknown>)
    .isInstanceMethodAlreadyImplemented;
  for (const [methodName, target] of binding) {
    if (
      typeof alreadyImplemented === "function"
        ? (alreadyImplemented as (methodName: string) => boolean).call(this, methodName)
        : isInstanceMethodAlreadyImplemented.call(this, methodName)
    ) {
      continue;
    }
    // Route through attribute_missing(match, ...) so subclasses can
    // intercept the entire generated cascade by overriding a single
    // method (Rails attribute_methods.rb:520-522). The match shape
    // mirrors Rails' AttributeMethodMatch — proxyTarget names the
    // generic handler; attrName is the bound attribute.
    mod.defineMethod(
      methodName,
      function (
        this: {
          attributeMissing(
            match: { proxyTarget: string; attrName: string },
            ...a: unknown[]
          ): unknown;
        },
        ...args: unknown[]
      ) {
        return this.attributeMissing({ proxyTarget: target, attrName: attrName }, ...args);
      },
    );
  }
}
