import type { AssociationProxy } from "../../associations/collection-proxy.js";
import type { Relation } from "../../relation.js";
import type { Temporal } from "@blazetrails/activesupport/temporal";
import type { Author } from "./author.js";
import type { Citation } from "./citation.js";
import type { Essay } from "./essay.js";
import type { Reference } from "./reference.js";
import type { Subscriber } from "./subscriber.js";
import type { Subscription } from "./subscription.js";
// vendor/rails/activerecord/test/models/book.rb
import { Base } from "../../base.js";

export class Book extends Base {
  declare author: Author | null;
  declare formatRecord: Base | null;
  declare citations: AssociationProxy<Citation>;
  declare references: AssociationProxy<Reference>;
  declare subscriptions: AssociationProxy<Subscription>;
  declare subscribers: AssociationProxy<Subscriber>;
  declare essay: Essay | null;
  declare isProposed: () => boolean;
  declare proposedBang: () => Promise<true | undefined>;
  declare static proposed: () => Relation<Book>;
  declare static notProposed: () => Relation<Book>;
  declare isWritten: () => boolean;
  declare writtenBang: () => Promise<true | undefined>;
  declare static written: () => Relation<Book>;
  declare static notWritten: () => Relation<Book>;
  declare isPublished: () => boolean;
  declare publishedBang: () => Promise<true | undefined>;
  declare static published: () => Relation<Book>;
  declare static notPublished: () => Relation<Book>;
  declare isUnread: () => boolean;
  declare unreadBang: () => Promise<true | undefined>;
  declare static unread: () => Relation<Book>;
  declare static notUnread: () => Relation<Book>;
  declare isReading: () => boolean;
  declare readingBang: () => Promise<true | undefined>;
  declare static reading: () => Relation<Book>;
  declare static notReading: () => Relation<Book>;
  declare isRead: () => boolean;
  declare readBang: () => Promise<true | undefined>;
  declare static read: () => Relation<Book>;
  declare static notRead: () => Relation<Book>;
  declare isSingle: () => boolean;
  declare singleBang: () => Promise<true | undefined>;
  declare static single: () => Relation<Book>;
  declare static notSingle: () => Relation<Book>;
  declare isMarried: () => boolean;
  declare marriedBang: () => Promise<true | undefined>;
  declare static married: () => Relation<Book>;
  declare static notMarried: () => Relation<Book>;
  declare isInEnglish: () => boolean;
  declare inEnglishBang: () => Promise<true | undefined>;
  declare static inEnglish: () => Relation<Book>;
  declare static notInEnglish: () => Relation<Book>;
  declare isInSpanish: () => boolean;
  declare inSpanishBang: () => Promise<true | undefined>;
  declare static inSpanish: () => Relation<Book>;
  declare static notInSpanish: () => Relation<Book>;
  declare isInFrench: () => boolean;
  declare inFrenchBang: () => Promise<true | undefined>;
  declare static inFrench: () => Relation<Book>;
  declare static notInFrench: () => Relation<Book>;
  declare isAuthorVisibilityVisible: () => boolean;
  declare authorVisibilityVisibleBang: () => Promise<true | undefined>;
  declare static authorVisibilityVisible: () => Relation<Book>;
  declare static notAuthorVisibilityVisible: () => Relation<Book>;
  declare isAuthorVisibilityInvisible: () => boolean;
  declare authorVisibilityInvisibleBang: () => Promise<true | undefined>;
  declare static authorVisibilityInvisible: () => Relation<Book>;
  declare static notAuthorVisibilityInvisible: () => Relation<Book>;
  declare isIllustratorVisibilityVisible: () => boolean;
  declare illustratorVisibilityVisibleBang: () => Promise<true | undefined>;
  declare static illustratorVisibilityVisible: () => Relation<Book>;
  declare static notIllustratorVisibilityVisible: () => Relation<Book>;
  declare isIllustratorVisibilityInvisible: () => boolean;
  declare illustratorVisibilityInvisibleBang: () => Promise<true | undefined>;
  declare static illustratorVisibilityInvisible: () => Relation<Book>;
  declare static notIllustratorVisibilityInvisible: () => Relation<Book>;
  declare isWithSmallFontSize: () => boolean;
  declare withSmallFontSizeBang: () => Promise<true | undefined>;
  declare static withSmallFontSize: () => Relation<Book>;
  declare static notWithSmallFontSize: () => Relation<Book>;
  declare isWithMediumFontSize: () => boolean;
  declare withMediumFontSizeBang: () => Promise<true | undefined>;
  declare static withMediumFontSize: () => Relation<Book>;
  declare static notWithMediumFontSize: () => Relation<Book>;
  declare isWithLargeFontSize: () => boolean;
  declare withLargeFontSizeBang: () => Promise<true | undefined>;
  declare static withLargeFontSize: () => Relation<Book>;
  declare static notWithLargeFontSize: () => Relation<Book>;
  declare isEasyToRead: () => boolean;
  declare easyToReadBang: () => Promise<true | undefined>;
  declare static easyToRead: () => Relation<Book>;
  declare static notEasyToRead: () => Relation<Book>;
  declare isMediumToRead: () => boolean;
  declare mediumToReadBang: () => Promise<true | undefined>;
  declare static mediumToRead: () => Relation<Book>;
  declare static notMediumToRead: () => Relation<Book>;
  declare isHardToRead: () => boolean;
  declare hardToReadBang: () => Promise<true | undefined>;
  declare static hardToRead: () => Relation<Book>;
  declare static notHardToRead: () => Relation<Book>;
  declare isForgotten: () => boolean;
  declare forgottenBang: () => Promise<true | undefined>;
  declare static forgotten: () => Relation<Book>;
  declare static notForgotten: () => Relation<Book>;
  declare isHard: () => boolean;
  declare hardBang: () => Promise<true | undefined>;
  declare static hard: () => Relation<Book>;
  declare static notHard: () => Relation<Book>;
  declare isSoft: () => boolean;
  declare softBang: () => Promise<true | undefined>;
  declare static soft: () => Relation<Book>;
  declare static notSoft: () => Relation<Book>;
  declare isEnabled: () => boolean;
  declare enabledBang: () => Promise<true | undefined>;
  declare static enabled: () => Relation<Book>;
  declare static notEnabled: () => Relation<Book>;
  declare isDisabled: () => boolean;
  declare disabledBang: () => Promise<true | undefined>;
  declare static disabled: () => Relation<Book>;
  declare static notDisabled: () => Relation<Book>;
  declare loadBelongsTo: ((name: "author") => Promise<Author | null>) &
    ((name: "formatRecord") => Promise<Base | null>);
  declare loadHasOne: (name: "essay") => Promise<Essay | null>;
  declare author_id: number;
  declare author_visibility: number | null;
  declare boolean_status: string | null;
  declare cover: string | null;
  declare created_at: Temporal.Instant | Temporal.PlainDateTime;
  declare difficulty: number | null;
  declare external_id: string;
  declare font_size: number | null;
  declare format: string;
  declare format_record_id: number;
  declare format_record_type: string;
  declare illustrator_visibility: number | null;
  declare isbn: string;
  declare language: number | null;
  declare last_read: number | null;
  declare name: string;
  declare nullable_status: number;
  declare original_name: string;
  declare published_on: Temporal.Instant | Temporal.PlainDateTime;
  declare status: number | null;
  declare tags_count: number | null;
  declare updated_at: Temporal.Instant | Temporal.PlainDateTime;
  declare updated_on: Temporal.PlainDate;

  static {
    this.belongsTo("author");
    this.belongsTo("formatRecord", { polymorphic: true });
    this.hasMany("citations", { inverseOf: "book" });
    this.hasMany("references", { through: "citations", source: "referenceOf" });
    this.hasMany("subscriptions");
    this.hasMany("subscribers", { through: "subscriptions" });
    this.hasOne("essay");
    this.aliasAttribute("title", "name");
    this.enum("status", { proposed: 0, written: 1, published: 2 });
    this.enum("last_read", { unread: 0, reading: 2, read: 3, forgotten: null });
    this.enum("nullable_status", { single: 0, married: 1 });
    this.enum("language", { english: 0, spanish: 1, french: 2 }, { prefix: "in" });
    this.enum("author_visibility", { visible: 0, invisible: 1 }, { prefix: true });
    this.enum("illustrator_visibility", { visible: 0, invisible: 1 }, { prefix: true });
    this.enum("font_size", { small: 0, medium: 1, large: 2 }, { prefix: "with", suffix: true });
    this.enum("difficulty", { easy: 0, medium: 1, hard: 2 }, { suffix: "toRead" });
    this.enum("cover", { hard: "hard", soft: "soft" });
    this.enum("boolean_status", { enabled: true, disabled: false });
  }
}

export class PublishedBook extends Base {
  static _tableName = "books";

  static {
    // Rails: cover { hard: "0", soft: "1" } — string values unsupported by enum(); omitted
    this.validates("isbn", { uniqueness: true });
  }
}
