// vendor/rails/activerecord/test/models/ — ported model classes for fixture-adoption sweep
export * from "./book.js";
export * from "./book-destroy-async.js";
export * from "./category.js";
export * from "./categorization.js";
export * from "./club.js";
export * from "./comment.js";
export * from "./essay.js";
export * from "./member.js";
export * from "./member-detail.js";
export * from "./member-type.js";
export * from "./membership.js";
export * from "./reader.js";
export * from "./reference.js";
export * from "./sponsor.js";
export * from "./subscriber.js";
export * from "./subscription.js";
export * from "./tag.js";
export * from "./tagging.js";
// Cluster 2: pirates/ships universe
export * from "./bird.js";
export * from "./parrot.js";
export * from "./pirate.js";
export * from "./ship.js";
export * from "./ship-part.js";
export * from "./topic.js";
export * from "./treasure.js";
export * from "./wheel.js";
// Cluster 4: pets/animals
export * from "./cat.js";
export * from "./dog.js";
export * from "./dog-lover.js";
export * from "./mouse.js";
export * from "./squeak.js";
export * from "./other-dog.js";
export * from "./owner.js";
export * from "./pet.js";
export * from "./pet-treasure.js";
