/**
 * Builds eslint/rails-tosql-classes.json — the allow-set for the
 * `rails-arel-tosql` ESLint rule. A TS class may only define `toSql` /
 * `toSqlAndBinds` if its Rails counterpart actually defines `to_sql` /
 * `to_sql_and_binds`; a bespoke `toSql` on a class whose Rails counterpart
 * has neither is a strong signal of hand-mashed SQL strings that should
 * route through real Arel AST nodes + visitors instead.
 *
 * Source of truth is the api-compare Rails manifest
 * (`scripts/api-compare/output/rails-api.json`, regenerate via
 * `pnpm api:compare`). We scan the in-scope packages for every class/module
 * that defines `to_sql` or `to_sql_and_binds`, map the Ruby class name +
 * file to its TS counterpart with the shared api-compare conventions
 * (`rubyMethodToTs` / `rubyFileToTs`), and emit a small committed snapshot
 * so the ESLint rule stays decoupled from the 6.9MB manifest:
 *   `{ generatedAt, packages: { arel: [{ name, methods, rubyFile, tsFile }], … } }`
 *
 *   pnpm tsx scripts/build-rails-tosql-manifest.ts
 */
import { readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { rubyMethodToTs, rubyFileToTs } from "./api-compare/conventions.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// Packages whose source the rule scopes over. Arel legitimately defines
// `to_sql` (managers/visitors), so it must come from the manifest allow-set
// rather than being hardcoded.
const PACKAGES = ["activerecord", "activemodel", "arel"] as const;
type Pkg = (typeof PACKAGES)[number];

// The Ruby method names that gate the allow-set, paired with the TS names
// `rubyMethodToTs` maps them to. We store the TS names in the snapshot so the
// rule compares against exactly what api-compare would expect.
const TOSQL_METHODS = ["to_sql", "to_sql_and_binds"];

const MANIFEST = path.join(ROOT, "scripts/api-compare/output/rails-api.json");
const OUT = path.join(ROOT, "eslint/rails-tosql-classes.json");

interface RailsMethod {
  name: string;
}
interface RailsClass {
  name?: string;
  file?: string;
  instanceMethods: RailsMethod[];
  classMethods: RailsMethod[];
}
interface RailsPackage {
  classes: Record<string, RailsClass>;
  modules: Record<string, RailsClass>;
}
interface RailsManifest {
  packages: Record<string, RailsPackage>;
}

interface TosqlClass {
  name: string;
  methods: string[];
  rubyFile: string;
  tsFile: string;
}

/** Last segment of a Ruby FQN (`Arel::Nodes::Node` → `Node`). */
function leaf(fqn: string): string {
  const parts = fqn.split("::");
  return parts[parts.length - 1];
}

function scanPackage(pkg: RailsPackage): TosqlClass[] {
  const byName = new Map<string, TosqlClass>();
  const groups = [pkg.classes ?? {}, pkg.modules ?? {}];
  for (const group of groups) {
    for (const [fqn, info] of Object.entries(group)) {
      const all = [...(info.instanceMethods ?? []), ...(info.classMethods ?? [])];
      const railsMethods = TOSQL_METHODS.filter((m) => all.some((x) => x.name === m));
      if (railsMethods.length === 0) continue;
      // Map each Ruby method to its TS name via the shared convention so the
      // snapshot records exactly the TS method names the rule will look for.
      const methods = [...new Set(railsMethods.flatMap((m) => rubyMethodToTs(m) ?? []))];
      // Prefer the manifest's own (already-unqualified) name field; fall back
      // to extracting the leaf from the FQN only when it's absent.
      const name = info.name ?? leaf(fqn);
      const rubyFile = info.file ?? "";
      const tsFile = rubyFile ? rubyFileToTs(rubyFile) : "";
      const existing = byName.get(name);
      if (existing) {
        existing.methods = [...new Set([...existing.methods, ...methods])];
        continue;
      }
      byName.set(name, { name, methods, rubyFile, tsFile });
    }
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
}

async function main() {
  // `rails-api.json` is generated by `pnpm api:compare` (needs vendored Rails
  // source + Ruby). Like the error manifest, it is absent in the lint CI job,
  // so when it's missing we preserve the committed snapshot rather than
  // overwriting it with empty data.
  if (!existsSync(MANIFEST)) {
    console.warn(
      "[build-rails-tosql-manifest] no scripts/api-compare/output/rails-api.json found; " +
        "preserving committed eslint/rails-tosql-classes.json. Run `pnpm api:compare` to regenerate.",
    );
    return;
  }

  const manifest = JSON.parse(await readFile(MANIFEST, "utf8")) as RailsManifest;
  const packages: Record<string, TosqlClass[]> = {};
  for (const pkg of PACKAGES) {
    const data = manifest.packages?.[pkg];
    packages[pkg] = data ? scanPackage(data) : [];
  }

  // `generatedAt` is fixed (not Date.now()) so the committed snapshot is
  // reproducible and only changes when the Rails source does.
  const out = { generatedAt: "vendored", packages };
  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, JSON.stringify(out, null, 2) + "\n");

  const counts = PACKAGES.map((p) => `${p}: ${packages[p].length}`).join(", ");
  console.log(`Wrote ${OUT} — ${counts}`);
}

main();
