/**
 * Regenerates `TZDATA_ISDST` (packages/date/src/tzdata-isdst.ts), the tzdata
 * `isdst` bit MRI's `Time#isdst` (`ruby/time.c` `time_isdst`, which answers
 * `tm.tm_isdst`) and `TZInfo::TimezonePeriod#dst?` both read straight off the
 * zone's transition records.
 *
 * No ECMAScript or `Temporal` API exposes that bit, and every reading that
 * derives it from offsets is wrong somewhere: sampling January against July
 * misses year-round DST (`America/New_York` 1943), and reading the surrounding
 * `getTimeZoneTransition` segments calls every permanent standard-offset shift
 * DST (`America/Cancun` 2015, `Europe/Istanbul` 2016). So the bit is vendored.
 *
 * The table is data, so it rots silently when tzdata revises a zone's history.
 * `generate-tzdata-isdst.test.ts` runs this script and asserts it still
 * produces the committed table, skipping where `ruby`/`tzinfo` is absent — the
 * regeneration guard `generate-canonical-zone-identifiers.ts` established for
 * the sibling table.
 *
 * Run with `pnpm tsx scripts/generate-tzdata-isdst.ts` to print the module for
 * writing over packages/date/src/tzdata-isdst.ts.
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

/** The last instant the table carries transitions for; past it the final bit holds. */
const HORIZON_YEAR = 2040;

/**
 * Every zone, mapped to its initial `isdst` bit and the instants the bit FLIPS
 * at — a transition that only moves the offset (a permanent shift, a war-time
 * re-basing) is not a flip and carries no entry. TZInfo reads the same records
 * `TimezonePeriod#dst?` answers from (tzinfo `timezone_offset.rb`).
 */
const RUBY_SCRIPT = `
require "tzinfo"
require "json"
zones = JSON.parse(ARGV[0])
out = {}
zones.each do |identifier|
  timezone = (TZInfo::Timezone.get(identifier) rescue nil)
  next if timezone.nil?
  initial = timezone.period_for_utc(Time.utc(1700)).dst?
  current = initial
  flips = []
  timezone.transitions_up_to(Time.utc(${HORIZON_YEAR})).each do |transition|
    dst = transition.offset.dst?
    next if dst == current
    current = dst
    flips << transition.timestamp_value
  end
  out[identifier] = [initial, flips]
end
puts JSON.generate(out)
`;

/** `[initialDst, flipInstants]` per zone, or `null` where `ruby`/`tzinfo` is unavailable. */
export async function rubyZoneDstFlips(
  identifiers: string[],
): Promise<Record<string, [boolean, number[]]> | null> {
  try {
    const { stdout } = await execFileAsync(
      "ruby",
      ["-e", RUBY_SCRIPT, JSON.stringify(identifiers)],
      {
        maxBuffer: 64 * 1024 * 1024,
      },
    );
    return JSON.parse(stdout) as Record<string, [boolean, number[]]>;
  } catch {
    return null;
  }
}

/**
 * The zone's row: the initial bit, then each flip as a base-36 delta in seconds
 * from the one before it. Base 36 rather than decimal because the table is
 * 25,000 flips wide and the deltas are mostly half-year constants.
 */
export function encodeZone(initial: boolean, flips: number[]): string {
  let previous = 0;
  let row = initial ? "1" : "0";
  for (const flip of flips) {
    row += `,${(flip - previous).toString(36)}`;
    previous = flip;
  }
  return row;
}

/** The module packages/date/src/tzdata-isdst.ts carries, table and reader both. */
export function serializeTable(zoneDstFlips: Record<string, [boolean, number[]]>): string {
  const rows: string[] = [];
  for (const identifier of Object.keys(zoneDstFlips).sort()) {
    const [initial, flips] = zoneDstFlips[identifier];
    // A zone that has never observed DST answers `false` at every instant,
    // which is what a missing row already answers.
    if (!initial && flips.length === 0) continue;
    rows.push(`${identifier} ${encodeZone(initial, flips)}`);
  }
  return `${HEADER}export const TZDATA_ISDST = \`\n${rows.join("\n")}\n\`;\n${READER}`;
}

const HEADER = `/**
 * The tzdata \`isdst\` bit, vendored — MRI reads it off the zone's transition
 * record (\`ruby/time.c\` \`time_isdst\` answers \`tm.tm_isdst\`) and TZInfo off the
 * same one (\`TimezonePeriod#dst?\`), and no ECMAScript or \`Temporal\` API
 * exposes it. Generated by scripts/generate-tzdata-isdst.ts; regenerate it
 * there rather than editing this file, and see that script for why every
 * offset-derived reading of the bit is wrong somewhere.
 *
 * One row per zone: the identifier, then the zone's \`isdst\` bit before its
 * first transition, then the instants the bit FLIPS at, as base-36 deltas in
 * seconds. A zone that has never observed DST carries no row. Transitions run
 * to ${HORIZON_YEAR}; past the last one the final bit holds, which is what
 * tzdata's own rules say. The rows are a template literal rather than an object
 * literal so that each zone stays on one line of the file.
 */
`;

const READER = `
let rowsByZoneId: Map<string, string>;

/** The table, split on first read: zone identifier to its flip row. */
function rows(): Map<string, string> {
  rowsByZoneId ??= new Map(
    TZDATA_ISDST.trim()
      .split("\\n")
      .map((row) => {
        const space = row.indexOf(" ");
        return [row.slice(0, space), row.slice(space + 1)] as [string, string];
      }),
  );
  return rowsByZoneId;
}

const flipInstants = new Map<string, number[]>();

/** The row's flip instants, decoded on first read of the zone. */
function zoneFlipInstants(row: string): number[] {
  let instants = flipInstants.get(row);
  if (instants === undefined) {
    instants = [];
    let previous = 0;
    for (const delta of row.split(",").slice(1)) {
      previous += parseInt(delta, 36);
      instants.push(previous);
    }
    flipInstants.set(row, instants);
  }
  return instants;
}

const rowsByPrimaryZoneId = new Map<string, string | undefined>();

/**
 * The zone's row, also answering for its tzdata link names: a host whose local
 * zone is reported as \`Asia/Calcutta\` rather than \`Asia/Kolkata\` is the same
 * zone and reads the same row.
 */
function zoneRow(timeZoneId: string): string | undefined {
  const row = rows().get(timeZoneId);
  if (row !== undefined) return row;
  if (!rowsByPrimaryZoneId.has(timeZoneId)) {
    let primary: string;
    try {
      primary = new Intl.DateTimeFormat("en-US", { timeZone: timeZoneId }).resolvedOptions()
        .timeZone;
    } catch {
      primary = timeZoneId;
    }
    rowsByPrimaryZoneId.set(timeZoneId, rows().get(primary));
  }
  return rowsByPrimaryZoneId.get(timeZoneId);
}

/**
 * tzdata's \`isdst\` bit for \`timeZoneId\` at \`epochSeconds\` — what MRI's
 * \`Time#isdst\` and \`TZInfo::TimezonePeriod#dst?\` answer.
 *
 * @noRailsEquivalent PERMANENT — the bit lives in the zoneinfo file MRI and the
 *   TZInfo gem each read directly; JS has no runtime API for it, so the port
 *   needs a table and a reader over it where Ruby needs neither.
 */
export function tzdataIsdst(timeZoneId: string, epochSeconds: number): boolean {
  const row = zoneRow(timeZoneId);
  if (row === undefined) return false;
  const instants = zoneFlipInstants(row);
  // The bit alternates at every flip, so its value is the initial bit flipped
  // once per instant already passed — a binary search for that count.
  let low = 0;
  let high = instants.length;
  while (low < high) {
    const middle = (low + high) >> 1;
    if (instants[middle] <= epochSeconds) low = middle + 1;
    else high = middle;
  }
  return (row.charCodeAt(0) === 49 ? low + 1 : low) % 2 === 1;
}
`;

async function main(): Promise<void> {
  const zoneDstFlips = await rubyZoneDstFlips(Intl.supportedValuesOf("timeZone"));
  if (zoneDstFlips === null) {
    throw new Error("ruby with the tzinfo gem is required to regenerate the table");
  }
  console.log(serializeTable(zoneDstFlips).trimEnd());
}

void main();
