#!/usr/bin/env tsx
// trails-side CLI for the sibling blazetrailsdev/tasks repo.
//
// All state lives in $TASKS_DIR (default ~/github/blazetrailsdev/tasks).
// Mutations: `git pull --rebase` → frontmatter edit → `git commit` →
// **synchronous** `git push` with one retry on non-fast-forward. The
// retry pulls, re-applies the edit, and pushes again; if it fails a
// second time the caller is told to pick another story.
//
// Read paths consume $TASKS_DIR/index.json, regenerated by the tasks
// repo's pre-commit hook. If the file is missing or any story `.md` is
// newer than index.json, this script invokes the tasks-side
// build-index.mjs as a fallback.
//
// Implementation note: RFC 0001 originally specified SQLite for the
// index. JSON was sufficient for the current scale and avoids a binary
// schema migration cost. If we hit dep-graph queries the JSON+JS shape
// can't handle, switch in a follow-up.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// $TASKS_DIR is the canonical override; $RFCS_DIR is honored as a
// transition fallback after the rfcs → tasks repo rename.
// Treat empty/whitespace-only env vars as unset so `TASKS_DIR=` doesn't
// silently resolve to cwd via `git -C ""`.
const envDir = (v: string | undefined): string | undefined => {
  const t = v?.trim();
  return t ? t : undefined;
};
export const TASKS_DIR =
  envDir(process.env.TASKS_DIR) ??
  envDir(process.env.RFCS_DIR) ??
  join(homedir(), "github", "blazetrailsdev", "tasks");

export type StoryStatus = "draft" | "ready" | "claimed" | "in-progress" | "done" | "blocked";
export type RfcStatus = "draft" | "active" | "closed" | "postponed" | "superseded";
export const STORY_STATUSES: readonly StoryStatus[] = [
  "draft",
  "ready",
  "claimed",
  "in-progress",
  "done",
  "blocked",
];

export interface RfcEntry {
  id: string;
  title: string | null;
  status: RfcStatus | null;
  owner: string | null;
  packages: string[];
  clusters: string[];
  file_path: string;
}
export interface StoryEntry {
  id: string;
  rfc: string;
  title: string | null;
  status: StoryStatus | null;
  cluster: string | null;
  deps: string[];
  deps_rfc: string[];
  est_loc: number | null;
  updated: string | null;
  pr: number | null;
  priority: number | null;
  claim: string | null;
  assignee: string | null;
  blocked_by: string | null;
  file_path: string;
}
export interface Index {
  generated_at: string;
  rfcs: RfcEntry[];
  stories: StoryEntry[];
}

// ──────────────────── index loading ────────────────────

export function loadIndex(): Index {
  const indexPath = join(TASKS_DIR, "index.json");
  if (!existsSync(indexPath) || isIndexStale(indexPath)) {
    // Use `process.execPath` (absolute path to the running Node binary)
    // rather than a bare "node": under pnpm/tsx the spawned environment's
    // PATH may not include `node`, which made the stale-index rebuild fail
    // with `spawnSync node ENOENT`.
    execFileSync(process.execPath, ["scripts/build-index.mjs"], {
      cwd: TASKS_DIR,
      stdio: "inherit",
    });
  }
  return JSON.parse(readFileSync(indexPath, "utf8")) as Index;
}

function isIndexStale(indexPath: string): boolean {
  const indexMtime = statSync(indexPath).mtimeMs;
  for (const rfcDir of readdirSync(TASKS_DIR)) {
    if (!/^\d{4}-/.test(rfcDir)) continue;
    // The RFC README's frontmatter feeds the index too (status, clusters,
    // packages, owner — and clusters drive `deps_rfc` resolution). A
    // README edit without a story touch must invalidate the cache.
    try {
      if (statSync(join(TASKS_DIR, rfcDir, "README.md")).mtimeMs > indexMtime) return true;
    } catch {
      /* missing README — validate step will catch */
    }
    const storiesDir = join(TASKS_DIR, rfcDir, "stories");
    let entries: string[];
    try {
      entries = readdirSync(storiesDir);
    } catch {
      continue;
    }
    for (const name of entries) {
      if (!name.endsWith(".md")) continue;
      if (statSync(join(storiesDir, name)).mtimeMs > indexMtime) return true;
    }
  }
  return false;
}

// ──────────────────── pure queries ────────────────────

export function ready(index: Index, opts: { rfc?: string } = {}): StoryEntry[] {
  const rfcStatus = new Map(index.rfcs.map((r) => [r.id, r.status]));
  const storyStatus = new Map(index.stories.map((s) => [s.id, s.status]));
  return index.stories.filter((s) => {
    if (s.status !== "ready") return false;
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (s.deps.some((d) => storyStatus.get(d) !== "done")) return false;
    if (s.deps_rfc.some((d) => rfcStatus.get(d) !== "closed")) return false;
    return true;
  });
}

// 0/1 knapsack: max total est_loc within budget. N ≤ a few dozen in
// practice; O(N·budget) is trivially fast.
export function bestBundle(items: StoryEntry[], budget: number): StoryEntry[] {
  const n = items.length;
  if (n === 0 || budget <= 0) return [];
  const dp: number[][] = Array.from({ length: n + 1 }, () => new Array(budget + 1).fill(0));
  for (let i = 1; i <= n; i++) {
    const cost = items[i - 1].est_loc ?? 0;
    for (let b = 0; b <= budget; b++) {
      dp[i][b] = dp[i - 1][b];
      if (cost > 0 && cost <= b) {
        dp[i][b] = Math.max(dp[i][b], dp[i - 1][b - cost] + cost);
      }
    }
  }
  const chosen: StoryEntry[] = [];
  let b = budget;
  for (let i = n; i >= 1; i--) {
    if (dp[i][b] !== dp[i - 1][b]) {
      chosen.push(items[i - 1]);
      b -= items[i - 1].est_loc ?? 0;
    }
  }
  return chosen.reverse();
}

export function nextBundle(
  index: Index,
  opts: { maxLoc: number; cluster?: string; rfc?: string },
): StoryEntry[] {
  const candidates = ready(index, { rfc: opts.rfc })
    .filter((s) => s.est_loc !== null)
    .filter((s) => (opts.cluster ? s.cluster === opts.cluster : true));
  // Use Map<string | null, ...> so `null` (unclustered) stays distinct
  // from any real cluster name, even one literally called "_none".
  const byCluster = new Map<string | null, StoryEntry[]>();
  for (const s of candidates) {
    const bucket = byCluster.get(s.cluster) ?? [];
    bucket.push(s);
    byCluster.set(s.cluster, bucket);
  }
  let best: StoryEntry[] = [];
  let bestTotal = 0;
  for (const group of byCluster.values()) {
    const subset = bestBundle(group, opts.maxLoc);
    const total = subset.reduce((a, s) => a + (s.est_loc ?? 0), 0);
    if (total > bestTotal) {
      best = subset;
      bestTotal = total;
    }
  }
  return best;
}

export function listFiltered(
  index: Index,
  opts: { rfc?: string; status?: string; cluster?: string } = {},
): StoryEntry[] {
  return index.stories.filter((s) => {
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (opts.status && s.status !== opts.status) return false;
    if (opts.cluster && s.cluster !== opts.cluster) return false;
    return true;
  });
}

// ──────────────────── mutations ────────────────────

// Today's date (UTC, YYYY-MM-DD) for the `updated:` frontmatter stamp. Every
// mutation that writes a story file stamps this so the backlog page can show
// staleness; build-index passes `updated` through to index.json verbatim, so
// the index stays deterministic (the wall-clock read happens here, at edit
// time, not at build time). Day granularity matches the day-level display.
function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function inGitTasks(): void {
  if (!existsSync(join(TASKS_DIR, ".git"))) {
    console.error(
      `error: ${TASKS_DIR} is not a git repo. Clone blazetrailsdev/tasks there, or set $TASKS_DIR to an existing checkout.`,
    );
    process.exit(1);
  }
}

// `cwd` defaults to TASKS_DIR (the canonical checkout the status mutations
// operate on). `refine` overrides it with an agent's worktree, which lives in
// the same repo but on a feature branch.
function git(args: string[], opts: { silent?: boolean; cwd?: string } = {}): string {
  return execFileSync("git", ["-C", opts.cwd ?? TASKS_DIR, ...args], {
    encoding: "utf8",
    stdio: opts.silent ? ["ignore", "pipe", "pipe"] : ["inherit", "pipe", "inherit"],
  }).trim();
}

// Generated artifacts the tasks repo's pre-commit hook rebuilds and
// re-stages on every commit (scripts/build-index.mjs). `loadIndex()` runs
// that same build script when it finds the index stale, which rewrites
// these tracked files in the working tree — see restoreGeneratedFiles.
const GENERATED_INDEX_FILES = ["index.md", "index.json", "search.json"];

// `loadIndex()` runs before every mutation reaches commitAndPush, and when it
// finds the index stale it invokes build-index.mjs, which rewrites the tracked
// GENERATED_INDEX_FILES in the working tree. With git's default
// rebase.autoStash=false (CI, fresh checkouts) a subsequent `git pull --rebase`
// then aborts: "cannot pull with rebase: You have unstaged changes". With
// autoStash on it instead stashes the throwaway copy and can conflict against
// upstream's own regenerated index on reapply — so neither config is safe.
// These files are regenerated and re-staged by the tasks repo's pre-commit hook
// on every commit, so the locally-rebuilt copies are throwaway — restore them
// to HEAD before pulling, leaving a clean tree regardless of git config.
// Restore each path independently: `git checkout -- a b c` is atomic — if any
// single path is unknown to git (e.g. a checkout predating search.json) the
// whole command fails and restores *nothing*, leaving the others dirty and the
// pull still aborting. Per-file checkout means a path git doesn't track can't
// block the rest; a path git doesn't know isn't dirty, so skipping it is fine.
function restoreGeneratedFiles(cwd: string | undefined): void {
  for (const file of GENERATED_INDEX_FILES) {
    try {
      git(["checkout", "--", file], { silent: true, cwd });
    } catch {
      /* path unknown to git or already clean — nothing to restore here */
    }
  }
}

function storyFilePath(index: Index, id: string): string {
  const entry = index.stories.find((s) => s.id === id);
  if (!entry) {
    console.error(`error: story "${id}" not found in index`);
    process.exit(1);
  }
  return join(TASKS_DIR, entry.file_path);
}

// Edits **single-line scalar** frontmatter fields only. Refuses to
// edit a key whose immediate next line is indented (i.e. a YAML list or
// nested map) — overwriting the key would orphan its children. The
// fields the CLI mutates today (status, claim, assignee, pr, blocked-by)
// are always scalars; refusing on lists is defensive.
export function editFrontmatter(file: string, edits: Record<string, string>): void {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^(---\n)([\s\S]*?)(\n---\n)([\s\S]*)$/);
  if (!m) {
    console.error(`error: ${file} has no frontmatter block`);
    process.exit(1);
  }
  const lines = m[2].split("\n");
  for (const [key, value] of Object.entries(edits)) {
    let found = false;
    for (let i = 0; i < lines.length; i++) {
      if (!lines[i].match(new RegExp(`^${key}:(\\s|$)`))) continue;
      const next = lines[i + 1];
      if (next && /^[ \t]/.test(next)) {
        console.error(`error: refusing to edit list-valued frontmatter key "${key}" in ${file}`);
        process.exit(1);
      }
      lines[i] = `${key}: ${value}`;
      found = true;
      break;
    }
    if (!found) lines.push(`${key}: ${value}`);
  }
  writeFileSync(file, m[1] + lines.join("\n") + m[3] + m[4]);
}

// Deletes a **single-line scalar** frontmatter key. No-op when the key is
// already absent. Refuses list/nested keys for the same reason editFrontmatter
// does — removing the key alone would orphan its indented children.
export function removeFrontmatterKey(file: string, key: string): void {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^(---\n)([\s\S]*?)(\n---\n)([\s\S]*)$/);
  if (!m) {
    console.error(`error: ${file} has no frontmatter block`);
    process.exit(1);
  }
  const lines = m[2].split("\n");
  const i = lines.findIndex((l) => new RegExp(`^${key}:(\\s|$)`).test(l));
  if (i === -1) return;
  if (lines[i + 1] && /^[ \t]/.test(lines[i + 1])) {
    console.error(`error: refusing to remove list-valued frontmatter key "${key}" in ${file}`);
    process.exit(1);
  }
  lines.splice(i, 1);
  writeFileSync(file, m[1] + lines.join("\n") + m[3] + m[4]);
}

// Pull-rebase → run mutator → commit → push, retrying once on
// non-fast-forward. `mutator` is run inside each attempt so a rebased
// index file is re-read between tries. Throws (and asks caller to
// retry) only after two consecutive lost races.
export function commitAndPush(opts: {
  message: string;
  fileToStage: string;
  mutator: () => void;
  raceMessage: string;
  raceExitCode: number;
  // Defaults target the canonical checkout on `main`. `refine` overrides
  // both: it commits in an agent's worktree (on a feature branch) and pushes
  // `HEAD:main` so the branch name is irrelevant to where the work lands.
  cwd?: string;
  pushRefspec?: string;
}): void {
  const cwd = opts.cwd;
  const pushRefspec = opts.pushRefspec ?? "main";
  // Clear any loadIndex()-regenerated artifacts so the pull below sees a clean
  // tree. Only needed before the first attempt — the retry path resets hard to
  // origin/main, which already discards them.
  restoreGeneratedFiles(cwd);
  for (let attempt = 0; attempt < 2; attempt++) {
    git(["pull", "--rebase", "--quiet", "origin", "main"], { cwd });
    opts.mutator();
    git(["add", opts.fileToStage], { cwd });
    git(["commit", "-q", "-m", opts.message], { cwd });
    try {
      git(["push", "--quiet", "origin", pushRefspec], { silent: true, cwd });
      return;
    } catch (e) {
      const stderr = String(((e as { stderr?: unknown }).stderr ?? "") || "");
      // git push prints "[rejected]" / "non-fast-forward" / "fetch first"
      // on the lost-race case. Anything else (auth, network, branch
      // protection, pre-receive hook failure) is a real error and must
      // be surfaced verbatim — not silently reset-and-retried.
      if (!/rejected|non-fast-forward|fetch first/i.test(stderr)) {
        console.error(stderr.trim() || "git push failed (no stderr)");
        process.exit(1);
      }
      git(["reset", "--hard", "origin/main"], { silent: true, cwd });
      if (attempt === 1) {
        console.error(opts.raceMessage);
        process.exit(opts.raceExitCode);
      }
    }
  }
}

// All mutations enter via `flip`. The order — `inGitTasks()` then
// `loadIndex()` — matters: if `$TASKS_DIR` is missing or not a git repo,
// the friendly error from `inGitTasks` fires before `loadIndex` would try
// to `execFileSync` the tasks-side build script in a non-repo directory.
// `mutate` receives the resolved file path so command implementations
// don't repeat the lookup.
function flip(
  id: string,
  message: string,
  raceMessage: string,
  raceExitCode: number,
  mutate: (file: string) => void,
): void {
  inGitTasks();
  const file = storyFilePath(loadIndex(), id);
  commitAndPush({
    message,
    fileToStage: file,
    raceMessage,
    raceExitCode,
    mutator: () => {
      mutate(file);
      editFrontmatter(file, { updated: today() });
    },
  });
}

function claim(id: string, assignee: string): void {
  flip(id, `claim: ${id}`, `lost claim race on ${id} — pick another story`, 3, (file) => {
    const fm = readFileSync(file, "utf8");
    if (!/^claim: null\s*$/m.test(fm)) {
      // Already claimed. If it's our own claim that already landed on main
      // (attempt 0's push succeeded server-side but the client reported a
      // transient error, so commitAndPush reset and retried — and the rebase
      // pulled our claim back), treat it as an idempotent success rather than
      // a conflict. Only a claim held by someone else is a real "already
      // claimed".
      const held = fm.match(/^assignee:\s*"?([^"\n]*)"?\s*$/m)?.[1] ?? null;
      if (held === assignee) {
        console.log(`claimed ${id} as ${assignee}`);
        process.exit(0);
      }
      console.error(`error: ${id} is already claimed`);
      process.exit(2);
    }
    const now = new Date().toISOString().replace(/\.\d+Z$/, "Z");
    editFrontmatter(file, {
      status: "claimed",
      claim: JSON.stringify(now),
      assignee: JSON.stringify(assignee),
    });
  });
  console.log(`claimed ${id} as ${assignee}`);
}

const RETRY_MSG = (id: string) => `failed to update ${id} after retry — pull manually and retry`;

function inProgress(id: string, pr: number): void {
  flip(id, `in-progress: ${id} #${pr}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "in-progress", pr: String(pr) }),
  );
  console.log(`marked ${id} in-progress #${pr}`);
}

function done(id: string, pr: number): void {
  flip(id, `done: ${id} #${pr}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "done", pr: String(pr) }),
  );
  console.log(`marked ${id} done #${pr}`);
}

function block(id: string, reason: string): void {
  flip(id, `block: ${id} — ${reason}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "blocked", "blocked-by": JSON.stringify(reason) }),
  );
  console.log(`blocked ${id}: ${reason}`);
}

// Set (or, with `priority === null`, clear) a story's ready-queue priority.
// Lower sorts first; absent = unprioritized (sorts last). Unlike the other
// mutations this leaves `status` untouched — it only reorders the queue. The
// caller validates the integer; build-index/validate enforce non-negative.
function setPriority(id: string, priority: number | null): void {
  // Short-circuit a no-op. Unlike the status mutations (which always change a
  // field), re-running priority with the unchanged value would leave nothing
  // to commit — `git commit` then errors "nothing to commit". Compare against
  // the indexed value and report cleanly instead of pushing an empty change.
  const entry = loadIndex().stories.find((s) => s.id === id);
  if (entry && entry.priority === priority) {
    // loadIndex() may have rebuilt — and so dirtied — the generated index files
    // in the canonical checkout. The status mutations let commitAndPush restore
    // them before its pull; this early return skips that, so clean up here to
    // avoid leaving the tasks checkout dirty.
    restoreGeneratedFiles(TASKS_DIR);
    console.log(
      priority === null ? `priority already clear on ${id}` : `${id} already priority ${priority}`,
    );
    return;
  }
  const message = priority === null ? `priority clear: ${id}` : `priority ${priority}: ${id}`;
  flip(id, message, RETRY_MSG(id), 4, (file) => {
    if (priority === null) removeFrontmatterKey(file, "priority");
    else editFrontmatter(file, { priority: String(priority) });
  });
  console.log(priority === null ? `cleared priority on ${id}` : `set ${id} priority ${priority}`);
}

// Single exit point for a refine agent: commit whatever it edited in the
// story file in place, push with the same rebase-retry as the other
// mutations, and print a machine-readable summary the orchestration layer
// forwards to btwhooks (POST /cleanup-pane without a PR).
//
// `dir` is the agent's tasks worktree (its cwd) — a checkout of the same
// repo on a feature branch. The CLI script itself resolves via the trails
// package.json, so the agent runs `cd <trails> && pnpm tasks refine <id>
// --dir <its-worktree>`; without `--dir` we operate on TASKS_DIR. We read
// the story's repo-relative path from the canonical index, then act on the
// copy inside `dir`.
//
// The agent leaves its edits in the worktree (citations, path:line fixes,
// priority, an optional done-note). We capture that content, then `git
// checkout` the file back to HEAD so `commitAndPush`'s leading `pull
// --rebase` runs against a clean tree; the captured content is re-applied
// inside each attempt (so a rebase between tries can't drop it), and the
// push is `HEAD:main`. With `--pr <N>` the story is also flipped to done —
// making this one command replace the old "edit + git push" / "pnpm tasks
// done" fork.
//
// Caveat: re-applying the full captured file clobbers any concurrent
// upstream edit to the SAME story file rather than 3-way merging it. One
// refine agent runs per story, so same-file races are effectively
// nonexistent; the scalar-field mutations above don't have this property
// because they re-read and edit specific keys.
function refine(id: string, pr: number | null, dir: string): void {
  inGitTasks();
  if (!existsSync(join(dir, ".git"))) {
    console.error(`error: ${dir} is not a git worktree (pass --dir <tasks worktree>)`);
    process.exit(1);
  }
  const entry = loadIndex().stories.find((s) => s.id === id);
  if (!entry) {
    console.error(`error: story "${id}" not found in index`);
    process.exit(1);
  }
  const file = join(dir, entry.file_path);
  if (!existsSync(file)) {
    console.error(`error: ${file} not found in worktree`);
    process.exit(1);
  }

  const edited = readFileSync(file, "utf8");
  git(["checkout", "--", file], { silent: true, cwd: dir });
  const changed = edited !== readFileSync(file, "utf8");

  if (!changed && pr === null) {
    console.log(`refine: ${id} no-change`);
    console.log(JSON.stringify({ id, outcome: "no-change", pushed: false, pr: null }));
    return;
  }

  commitAndPush({
    cwd: dir,
    pushRefspec: "HEAD:main",
    message: pr !== null ? `refine: ${id} #${pr}` : `refine: ${id}`,
    fileToStage: file,
    raceMessage: RETRY_MSG(id),
    raceExitCode: 4,
    mutator: () => {
      writeFileSync(file, edited);
      const fields: Record<string, string> = { updated: today() };
      if (pr !== null) {
        fields.status = "done";
        fields.pr = String(pr);
      }
      editFrontmatter(file, fields);
    },
  });

  const outcome = pr !== null ? "done" : "changed";
  console.log(`refine: ${id} ${outcome}${pr !== null ? ` #${pr}` : ""}`);
  console.log(JSON.stringify({ id, outcome, pushed: true, pr }));
}

// ──────────────────── presentation ────────────────────

function fmt(rows: StoryEntry[]): void {
  if (!rows.length) {
    console.log("(none)");
    return;
  }
  const cols = ["id", "rfc", "status", "cluster", "est_loc"] as const;
  const widths = cols.map((c) =>
    Math.max(c.length, ...rows.map((r) => String(r[c] ?? "—").length)),
  );
  const line = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(line([...cols]));
  for (const r of rows) console.log(line(cols.map((c) => String(r[c] ?? "—"))));
}

function statusCounts(index: Index): void {
  const byRfc = new Map<string, Record<string, number>>();
  for (const s of index.stories) {
    const row = byRfc.get(s.rfc) ?? Object.fromEntries(STORY_STATUSES.map((k) => [k, 0]));
    if (s.status) row[s.status] = (row[s.status] ?? 0) + 1;
    byRfc.set(s.rfc, row);
  }
  const totals = Object.fromEntries(STORY_STATUSES.map((k) => [k, 0]));
  for (const row of byRfc.values()) for (const k of STORY_STATUSES) totals[k] += row[k];
  const header = ["RFC", ...STORY_STATUSES];
  const rows = [...byRfc.entries()]
    .sort()
    .map(([rfc, row]) => [rfc, ...STORY_STATUSES.map((k) => String(row[k]))]);
  rows.push(["TOTAL", ...STORY_STATUSES.map((k) => String(totals[k]))]);
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i].length)));
  const line = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(line(header));
  for (const r of rows) console.log(line(r));
}

// ──────────────────── argv ────────────────────

// Reject `--foo` for a value-flag where no value followed (the parser
// fell back to `true`). `Number(true)` is `1`, which silently passes
// `if (!pr)` checks; coerce-and-validate at the call site instead.
export function numberFlag(flags: Record<string, string | boolean>, name: string): number | null {
  const v = flags[name];
  if (typeof v !== "string" || !/^\d+$/.test(v)) return null;
  return Number(v);
}

export function stringFlag(
  flags: Record<string, string | boolean>,
  name: string,
): string | undefined {
  const v = flags[name];
  return typeof v === "string" ? v : undefined;
}

// Known boolean flags. Everything else with a non-`--` following token
// is treated as `--key value`. Boolean flags never consume the next
// token, removing the `--json <id>` ambiguity.
const BOOLEAN_FLAGS = new Set(["json", "clear"]);

export function parseFlags(
  args: string[],
  booleanFlags: ReadonlySet<string> = BOOLEAN_FLAGS,
): {
  flags: Record<string, string | boolean>;
  rest: string[];
} {
  const flags: Record<string, string | boolean> = {};
  const rest: string[] = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      if (booleanFlags.has(key)) {
        flags[key] = true;
        continue;
      }
      const next = args[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      rest.push(a);
    }
  }
  return { flags, rest };
}

function main(): void {
  const [cmd, ...rest] = process.argv.slice(2);
  const { flags, rest: pos } = parseFlags(rest);
  // `flags[k] === true` means the user wrote `--k` with no following
  // value. For value-flags that's a usage error, not a boolean.
  const valueFlags = ["rfc", "cluster", "status", "max-loc", "pr", "assignee", "reason", "dir"];
  for (const k of valueFlags) if (flags[k] === true) usage();

  switch (cmd) {
    case "ready": {
      const rows = ready(loadIndex(), { rfc: stringFlag(flags, "rfc") });
      flags.json ? console.log(JSON.stringify(rows, null, 2)) : fmt(rows);
      break;
    }
    case "next-bundle": {
      const maxLocRaw = stringFlag(flags, "max-loc") ?? "250";
      if (!/^\d+$/.test(maxLocRaw) || Number(maxLocRaw) <= 0) usage();
      const maxLoc = Number(maxLocRaw);
      const rows = nextBundle(loadIndex(), {
        maxLoc,
        cluster: stringFlag(flags, "cluster"),
        rfc: stringFlag(flags, "rfc"),
      });
      const total = rows.reduce((a, s) => a + (s.est_loc ?? 0), 0);
      if (flags.json) {
        console.log(
          JSON.stringify({ stories: rows, bundle_total_loc: total, max_loc: maxLoc }, null, 2),
        );
      } else if (rows.length === 0) {
        console.log(`no ready stories within ${maxLoc} LOC`);
      } else {
        console.log(`bundle (sum ${total} / max ${maxLoc}):`);
        fmt(rows);
      }
      break;
    }
    case "list": {
      const rows = listFiltered(loadIndex(), {
        rfc: stringFlag(flags, "rfc"),
        status: stringFlag(flags, "status"),
        cluster: stringFlag(flags, "cluster"),
      });
      flags.json ? console.log(JSON.stringify(rows, null, 2)) : fmt(rows);
      break;
    }
    case "status":
      statusCounts(loadIndex());
      break;
    case "claim": {
      const id = pos[0];
      const assignee = stringFlag(flags, "assignee");
      if (!id) usage();
      claim(id, assignee ?? id);
      break;
    }
    case "in-progress": {
      const id = pos[0];
      const pr = numberFlag(flags, "pr");
      if (!id || pr === null) usage();
      inProgress(id, pr);
      break;
    }
    case "done": {
      const id = pos[0];
      const pr = numberFlag(flags, "pr");
      if (!id || pr === null) usage();
      done(id, pr);
      break;
    }
    case "block": {
      const id = pos[0];
      const reason = stringFlag(flags, "reason") ?? pos[1];
      if (!id || !reason) usage();
      block(id, reason);
      break;
    }
    case "refine": {
      const id = pos[0];
      if (!id) usage();
      // --pr is optional here: present ⇒ also flip the story to done.
      // --dir is the agent's tasks worktree; defaults to the canonical checkout.
      refine(id, numberFlag(flags, "pr"), stringFlag(flags, "dir") ?? TASKS_DIR);
      break;
    }
    case "priority": {
      const id = pos[0];
      if (!id) usage();
      if (flags.clear) {
        setPriority(id, null);
      } else {
        // Positional integer; lower = higher priority. Reject non-integers and
        // negatives so a typo can't write a value `validate.mjs` will reject.
        const n = pos[1];
        if (n === undefined || !/^\d+$/.test(n)) usage();
        setPriority(id, Number(n));
      }
      break;
    }
    default:
      usage();
  }
}

function usage(): never {
  console.error(`usage: pnpm tasks <command>

  ready [--json] [--rfc <slug>]
  next-bundle [--max-loc N] [--cluster <name>] [--rfc <slug>] [--json]
  list [--rfc <slug>] [--status <v>] [--cluster <n>] [--json]
  status

  claim <id> [--assignee <name>]
  in-progress <id> --pr <N>
  done <id> --pr <N>
  block <id> --reason "<text>"
  refine <id> [--pr <N>] [--dir <tasks worktree>]
  priority <id> <N> | priority <id> --clear    (lower N = higher priority)

Set $TASKS_DIR to override the default ~/github/blazetrailsdev/tasks.
($RFCS_DIR is honored as a transition fallback after the rfcs → tasks rename.)`);
  process.exit(2);
}

// CLI entry — only runs when this module is the script entrypoint, not
// when imported (e.g. by the smoke test). Matches the pattern used by
// scripts/fixtures-compare/compare.ts and scripts/api-compare/lint-deps.ts.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
