#!/usr/bin/env tsx
// trails-side CLI for the sibling blazetrailsdev/tasks repo.
//
// All state lives in $TASKS_DIR (default ~/github/blazetrailsdev/tasks).
// Mutations: `git pull --rebase` → frontmatter edit → `git commit` →
// **synchronous** `git push` with one retry on non-fast-forward. The
// retry pulls, re-applies the edit, and pushes again; if it fails a
// second time the caller is told to pick another story.
//
// Read paths consume $TASKS_DIR/index.json, regenerated by the tasks
// repo's pre-commit hook. If the file is missing or any story `.md` is
// newer than index.json, this script invokes the tasks-side
// build-index.mjs as a fallback.
//
// Implementation note: RFC 0001 originally specified SQLite for the
// index. JSON was sufficient for the current scale and avoids a binary
// schema migration cost. If we hit dep-graph queries the JSON+JS shape
// can't handle, switch in a follow-up.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// $TASKS_DIR is the canonical override; $RFCS_DIR is honored as a
// transition fallback after the rfcs → tasks repo rename.
// Treat empty/whitespace-only env vars as unset so `TASKS_DIR=` doesn't
// silently resolve to cwd via `git -C ""`.
const envDir = (v: string | undefined): string | undefined => {
  const t = v?.trim();
  return t ? t : undefined;
};
export const TASKS_DIR =
  envDir(process.env.TASKS_DIR) ??
  envDir(process.env.RFCS_DIR) ??
  join(homedir(), "github", "blazetrailsdev", "tasks");

export type StoryStatus = "draft" | "ready" | "claimed" | "in-progress" | "done" | "blocked";
export type RfcStatus = "draft" | "active" | "closed" | "postponed" | "superseded";
export const STORY_STATUSES: readonly StoryStatus[] = [
  "draft",
  "ready",
  "claimed",
  "in-progress",
  "done",
  "blocked",
];

export interface RfcEntry {
  id: string;
  title: string | null;
  status: RfcStatus | null;
  owner: string | null;
  packages: string[];
  clusters: string[];
  file_path: string;
}
export interface StoryEntry {
  id: string;
  rfc: string;
  title: string | null;
  status: StoryStatus | null;
  cluster: string | null;
  deps: string[];
  deps_rfc: string[];
  est_loc: number | null;
  pr: number | null;
  claim: string | null;
  assignee: string | null;
  blocked_by: string | null;
  file_path: string;
}
export interface Index {
  generated_at: string;
  rfcs: RfcEntry[];
  stories: StoryEntry[];
}

// ──────────────────── index loading ────────────────────

export function loadIndex(): Index {
  const indexPath = join(TASKS_DIR, "index.json");
  if (!existsSync(indexPath) || isIndexStale(indexPath)) {
    execFileSync("node", ["scripts/build-index.mjs"], { cwd: TASKS_DIR, stdio: "inherit" });
  }
  return JSON.parse(readFileSync(indexPath, "utf8")) as Index;
}

function isIndexStale(indexPath: string): boolean {
  const indexMtime = statSync(indexPath).mtimeMs;
  for (const rfcDir of readdirSync(TASKS_DIR)) {
    if (!/^\d{4}-/.test(rfcDir)) continue;
    // The RFC README's frontmatter feeds the index too (status, clusters,
    // packages, owner — and clusters drive `deps_rfc` resolution). A
    // README edit without a story touch must invalidate the cache.
    try {
      if (statSync(join(TASKS_DIR, rfcDir, "README.md")).mtimeMs > indexMtime) return true;
    } catch {
      /* missing README — validate step will catch */
    }
    const storiesDir = join(TASKS_DIR, rfcDir, "stories");
    let entries: string[];
    try {
      entries = readdirSync(storiesDir);
    } catch {
      continue;
    }
    for (const name of entries) {
      if (!name.endsWith(".md")) continue;
      if (statSync(join(storiesDir, name)).mtimeMs > indexMtime) return true;
    }
  }
  return false;
}

// ──────────────────── pure queries ────────────────────

export function ready(index: Index, opts: { rfc?: string } = {}): StoryEntry[] {
  const rfcStatus = new Map(index.rfcs.map((r) => [r.id, r.status]));
  const storyStatus = new Map(index.stories.map((s) => [s.id, s.status]));
  return index.stories.filter((s) => {
    if (s.status !== "ready") return false;
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (s.deps.some((d) => storyStatus.get(d) !== "done")) return false;
    if (s.deps_rfc.some((d) => rfcStatus.get(d) !== "closed")) return false;
    return true;
  });
}

// 0/1 knapsack: max total est_loc within budget. N ≤ a few dozen in
// practice; O(N·budget) is trivially fast.
export function bestBundle(items: StoryEntry[], budget: number): StoryEntry[] {
  const n = items.length;
  if (n === 0 || budget <= 0) return [];
  const dp: number[][] = Array.from({ length: n + 1 }, () => new Array(budget + 1).fill(0));
  for (let i = 1; i <= n; i++) {
    const cost = items[i - 1].est_loc ?? 0;
    for (let b = 0; b <= budget; b++) {
      dp[i][b] = dp[i - 1][b];
      if (cost > 0 && cost <= b) {
        dp[i][b] = Math.max(dp[i][b], dp[i - 1][b - cost] + cost);
      }
    }
  }
  const chosen: StoryEntry[] = [];
  let b = budget;
  for (let i = n; i >= 1; i--) {
    if (dp[i][b] !== dp[i - 1][b]) {
      chosen.push(items[i - 1]);
      b -= items[i - 1].est_loc ?? 0;
    }
  }
  return chosen.reverse();
}

export function nextBundle(
  index: Index,
  opts: { maxLoc: number; cluster?: string; rfc?: string },
): StoryEntry[] {
  const candidates = ready(index, { rfc: opts.rfc })
    .filter((s) => s.est_loc !== null)
    .filter((s) => (opts.cluster ? s.cluster === opts.cluster : true));
  // Use Map<string | null, ...> so `null` (unclustered) stays distinct
  // from any real cluster name, even one literally called "_none".
  const byCluster = new Map<string | null, StoryEntry[]>();
  for (const s of candidates) {
    const bucket = byCluster.get(s.cluster) ?? [];
    bucket.push(s);
    byCluster.set(s.cluster, bucket);
  }
  let best: StoryEntry[] = [];
  let bestTotal = 0;
  for (const group of byCluster.values()) {
    const subset = bestBundle(group, opts.maxLoc);
    const total = subset.reduce((a, s) => a + (s.est_loc ?? 0), 0);
    if (total > bestTotal) {
      best = subset;
      bestTotal = total;
    }
  }
  return best;
}

export function listFiltered(
  index: Index,
  opts: { rfc?: string; status?: string; cluster?: string } = {},
): StoryEntry[] {
  return index.stories.filter((s) => {
    if (opts.rfc && s.rfc !== opts.rfc) return false;
    if (opts.status && s.status !== opts.status) return false;
    if (opts.cluster && s.cluster !== opts.cluster) return false;
    return true;
  });
}

// ──────────────────── mutations ────────────────────

function inGitTasks(): void {
  if (!existsSync(join(TASKS_DIR, ".git"))) {
    console.error(
      `error: ${TASKS_DIR} is not a git repo. Clone blazetrailsdev/tasks there, or set $TASKS_DIR to an existing checkout.`,
    );
    process.exit(1);
  }
}

function git(args: string[], opts: { silent?: boolean } = {}): string {
  return execFileSync("git", ["-C", TASKS_DIR, ...args], {
    encoding: "utf8",
    stdio: opts.silent ? ["ignore", "pipe", "pipe"] : ["inherit", "pipe", "inherit"],
  }).trim();
}

function storyFilePath(index: Index, id: string): string {
  const entry = index.stories.find((s) => s.id === id);
  if (!entry) {
    console.error(`error: story "${id}" not found in index`);
    process.exit(1);
  }
  return join(TASKS_DIR, entry.file_path);
}

// Edits **single-line scalar** frontmatter fields only. Refuses to
// edit a key whose immediate next line is indented (i.e. a YAML list or
// nested map) — overwriting the key would orphan its children. The
// fields the CLI mutates today (status, claim, assignee, pr, blocked-by)
// are always scalars; refusing on lists is defensive.
export function editFrontmatter(file: string, edits: Record<string, string>): void {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^(---\n)([\s\S]*?)(\n---\n)([\s\S]*)$/);
  if (!m) {
    console.error(`error: ${file} has no frontmatter block`);
    process.exit(1);
  }
  const lines = m[2].split("\n");
  for (const [key, value] of Object.entries(edits)) {
    let found = false;
    for (let i = 0; i < lines.length; i++) {
      if (!lines[i].match(new RegExp(`^${key}:(\\s|$)`))) continue;
      const next = lines[i + 1];
      if (next && /^[ \t]/.test(next)) {
        console.error(`error: refusing to edit list-valued frontmatter key "${key}" in ${file}`);
        process.exit(1);
      }
      lines[i] = `${key}: ${value}`;
      found = true;
      break;
    }
    if (!found) lines.push(`${key}: ${value}`);
  }
  writeFileSync(file, m[1] + lines.join("\n") + m[3] + m[4]);
}

// Pull-rebase → run mutator → commit → push, retrying once on
// non-fast-forward. `mutator` is run inside each attempt so a rebased
// index file is re-read between tries. Throws (and asks caller to
// retry) only after two consecutive lost races.
export function commitAndPush(opts: {
  message: string;
  fileToStage: string;
  mutator: () => void;
  raceMessage: string;
  raceExitCode: number;
}): void {
  for (let attempt = 0; attempt < 2; attempt++) {
    git(["pull", "--rebase", "--quiet", "origin", "main"]);
    opts.mutator();
    git(["add", opts.fileToStage]);
    git(["commit", "-q", "-m", opts.message]);
    try {
      git(["push", "--quiet", "origin", "main"], { silent: true });
      return;
    } catch (e) {
      const stderr = String(((e as { stderr?: unknown }).stderr ?? "") || "");
      // git push prints "[rejected]" / "non-fast-forward" / "fetch first"
      // on the lost-race case. Anything else (auth, network, branch
      // protection, pre-receive hook failure) is a real error and must
      // be surfaced verbatim — not silently reset-and-retried.
      if (!/rejected|non-fast-forward|fetch first/i.test(stderr)) {
        console.error(stderr.trim() || "git push failed (no stderr)");
        process.exit(1);
      }
      git(["reset", "--hard", "origin/main"], { silent: true });
      if (attempt === 1) {
        console.error(opts.raceMessage);
        process.exit(opts.raceExitCode);
      }
    }
  }
}

// All mutations enter via `flip`. The order — `inGitTasks()` then
// `loadIndex()` — matters: if `$TASKS_DIR` is missing or not a git repo,
// the friendly error from `inGitTasks` fires before `loadIndex` would try
// to `execFileSync` the tasks-side build script in a non-repo directory.
// `mutate` receives the resolved file path so command implementations
// don't repeat the lookup.
function flip(
  id: string,
  message: string,
  raceMessage: string,
  raceExitCode: number,
  mutate: (file: string) => void,
): void {
  inGitTasks();
  const file = storyFilePath(loadIndex(), id);
  commitAndPush({
    message,
    fileToStage: file,
    raceMessage,
    raceExitCode,
    mutator: () => mutate(file),
  });
}

function claim(id: string, assignee: string): void {
  flip(id, `claim: ${id}`, `lost claim race on ${id} — pick another story`, 3, (file) => {
    const fm = readFileSync(file, "utf8");
    if (!/^claim: null\s*$/m.test(fm)) {
      console.error(`error: ${id} is already claimed`);
      process.exit(2);
    }
    const now = new Date().toISOString().replace(/\.\d+Z$/, "Z");
    editFrontmatter(file, {
      status: "claimed",
      claim: JSON.stringify(now),
      assignee: JSON.stringify(assignee),
    });
  });
  console.log(`claimed ${id} as ${assignee}`);
}

const RETRY_MSG = (id: string) => `failed to update ${id} after retry — pull manually and retry`;

function inProgress(id: string, pr: number): void {
  flip(id, `in-progress: ${id} #${pr}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "in-progress", pr: String(pr) }),
  );
  console.log(`marked ${id} in-progress #${pr}`);
}

function done(id: string, pr: number): void {
  flip(id, `done: ${id} #${pr}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "done", pr: String(pr) }),
  );
  console.log(`marked ${id} done #${pr}`);
}

function block(id: string, reason: string): void {
  flip(id, `block: ${id} — ${reason}`, RETRY_MSG(id), 4, (file) =>
    editFrontmatter(file, { status: "blocked", "blocked-by": JSON.stringify(reason) }),
  );
  console.log(`blocked ${id}: ${reason}`);
}

// ──────────────────── presentation ────────────────────

function fmt(rows: StoryEntry[]): void {
  if (!rows.length) {
    console.log("(none)");
    return;
  }
  const cols = ["id", "rfc", "status", "cluster", "est_loc"] as const;
  const widths = cols.map((c) =>
    Math.max(c.length, ...rows.map((r) => String(r[c] ?? "—").length)),
  );
  const line = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(line([...cols]));
  for (const r of rows) console.log(line(cols.map((c) => String(r[c] ?? "—"))));
}

function statusCounts(index: Index): void {
  const byRfc = new Map<string, Record<string, number>>();
  for (const s of index.stories) {
    const row = byRfc.get(s.rfc) ?? Object.fromEntries(STORY_STATUSES.map((k) => [k, 0]));
    if (s.status) row[s.status] = (row[s.status] ?? 0) + 1;
    byRfc.set(s.rfc, row);
  }
  const totals = Object.fromEntries(STORY_STATUSES.map((k) => [k, 0]));
  for (const row of byRfc.values()) for (const k of STORY_STATUSES) totals[k] += row[k];
  const header = ["RFC", ...STORY_STATUSES];
  const rows = [...byRfc.entries()]
    .sort()
    .map(([rfc, row]) => [rfc, ...STORY_STATUSES.map((k) => String(row[k]))]);
  rows.push(["TOTAL", ...STORY_STATUSES.map((k) => String(totals[k]))]);
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i].length)));
  const line = (cells: string[]) => cells.map((c, i) => c.padEnd(widths[i])).join("  ");
  console.log(line(header));
  for (const r of rows) console.log(line(r));
}

// ──────────────────── argv ────────────────────

// Reject `--foo` for a value-flag where no value followed (the parser
// fell back to `true`). `Number(true)` is `1`, which silently passes
// `if (!pr)` checks; coerce-and-validate at the call site instead.
export function numberFlag(flags: Record<string, string | boolean>, name: string): number | null {
  const v = flags[name];
  if (typeof v !== "string" || !/^\d+$/.test(v)) return null;
  return Number(v);
}

export function stringFlag(
  flags: Record<string, string | boolean>,
  name: string,
): string | undefined {
  const v = flags[name];
  return typeof v === "string" ? v : undefined;
}

// Known boolean flags. Everything else with a non-`--` following token
// is treated as `--key value`. Boolean flags never consume the next
// token, removing the `--json <id>` ambiguity.
const BOOLEAN_FLAGS = new Set(["json"]);

export function parseFlags(
  args: string[],
  booleanFlags: ReadonlySet<string> = BOOLEAN_FLAGS,
): {
  flags: Record<string, string | boolean>;
  rest: string[];
} {
  const flags: Record<string, string | boolean> = {};
  const rest: string[] = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      if (booleanFlags.has(key)) {
        flags[key] = true;
        continue;
      }
      const next = args[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      rest.push(a);
    }
  }
  return { flags, rest };
}

function main(): void {
  const [cmd, ...rest] = process.argv.slice(2);
  const { flags, rest: pos } = parseFlags(rest);
  // `flags[k] === true` means the user wrote `--k` with no following
  // value. For value-flags that's a usage error, not a boolean.
  const valueFlags = ["rfc", "cluster", "status", "max-loc", "pr", "assignee", "reason"];
  for (const k of valueFlags) if (flags[k] === true) usage();

  switch (cmd) {
    case "ready": {
      const rows = ready(loadIndex(), { rfc: stringFlag(flags, "rfc") });
      flags.json ? console.log(JSON.stringify(rows, null, 2)) : fmt(rows);
      break;
    }
    case "next-bundle": {
      const maxLocRaw = stringFlag(flags, "max-loc") ?? "250";
      if (!/^\d+$/.test(maxLocRaw) || Number(maxLocRaw) <= 0) usage();
      const maxLoc = Number(maxLocRaw);
      const rows = nextBundle(loadIndex(), {
        maxLoc,
        cluster: stringFlag(flags, "cluster"),
        rfc: stringFlag(flags, "rfc"),
      });
      const total = rows.reduce((a, s) => a + (s.est_loc ?? 0), 0);
      if (flags.json) {
        console.log(
          JSON.stringify({ stories: rows, bundle_total_loc: total, max_loc: maxLoc }, null, 2),
        );
      } else if (rows.length === 0) {
        console.log(`no ready stories within ${maxLoc} LOC`);
      } else {
        console.log(`bundle (sum ${total} / max ${maxLoc}):`);
        fmt(rows);
      }
      break;
    }
    case "list": {
      const rows = listFiltered(loadIndex(), {
        rfc: stringFlag(flags, "rfc"),
        status: stringFlag(flags, "status"),
        cluster: stringFlag(flags, "cluster"),
      });
      flags.json ? console.log(JSON.stringify(rows, null, 2)) : fmt(rows);
      break;
    }
    case "status":
      statusCounts(loadIndex());
      break;
    case "claim": {
      const id = pos[0];
      const assignee = stringFlag(flags, "assignee");
      if (!id) usage();
      claim(id, assignee ?? id);
      break;
    }
    case "in-progress": {
      const id = pos[0];
      const pr = numberFlag(flags, "pr");
      if (!id || pr === null) usage();
      inProgress(id, pr);
      break;
    }
    case "done": {
      const id = pos[0];
      const pr = numberFlag(flags, "pr");
      if (!id || pr === null) usage();
      done(id, pr);
      break;
    }
    case "block": {
      const id = pos[0];
      const reason = stringFlag(flags, "reason") ?? pos[1];
      if (!id || !reason) usage();
      block(id, reason);
      break;
    }
    default:
      usage();
  }
}

function usage(): never {
  console.error(`usage: pnpm tasks <command>

  ready [--json] [--rfc <slug>]
  next-bundle [--max-loc N] [--cluster <name>] [--rfc <slug>] [--json]
  list [--rfc <slug>] [--status <v>] [--cluster <n>] [--json]
  status

  claim <id> [--assignee <name>]
  in-progress <id> --pr <N>
  done <id> --pr <N>
  block <id> --reason "<text>"

Set $TASKS_DIR to override the default ~/github/blazetrailsdev/tasks.
($RFCS_DIR is honored as a transition fallback after the rfcs → tasks rename.)`);
  process.exit(2);
}

// CLI entry — only runs when this module is the script entrypoint, not
// when imported (e.g. by the smoke test). Matches the pattern used by
// scripts/fixtures-compare/compare.ts and scripts/api-compare/lint-deps.ts.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
