import { getFsAsync, getPathAsync } from "@blazetrails/activesupport";
import type { FsAdapter } from "@blazetrails/activesupport";
import ts from "typescript";

// A class is a model worth registering when its `extends` chain reaches the
// `Base` exported by `@blazetrails/activerecord`. We terminate the walk on a
// parent that is *that* import specifically — not any identifier named `Base`,
// so a class extending an unrelated `Base` from another package is not a model.
const AR_PACKAGE = "@blazetrails/activerecord";
const MANIFEST_NAME = "index.ts";

// Path-neutral so the header is correct wherever `--root` writes the manifest.
const HEADER =
  "// AUTO-GENERATED by @blazetrails/activerecord-cli. Do not edit by hand.\n" +
  "// Re-run `ar generate:manifest` (or `ar init`) to update.\n";

/** A model class discovered by the scan, plus where to import it from. */
export interface ModelEntry {
  className: string; // the exported class name (also the imported binding name)
  importPath: string; // ESM specifier relative to the manifest, e.g. `./user.js`
  isDefault: boolean; // exported as `export default class` vs a named export
}

interface ClassNode {
  name: string;
  parent: string | undefined; // the `extends` target's identifier name, if any
  isExported: boolean;
  isDefault: boolean; // `export default class`
  isAbstract: boolean;
}

/** A relative import binding: `local` → the original name in target `file`. */
interface RelativeImport {
  original: string; // the imported export's name, or "default"
  file: string; // resolved target filename within the scan dir, e.g. `user.ts`
}

/** Everything the inheritance walk needs about one scanned model file. */
interface FileInfo {
  file: string;
  classes: Map<string, ClassNode>; // ALL classes declared here (exported or not), by name
  arBase: Set<string>; // locals bound to `@blazetrails/activerecord`'s Base
  external: Set<string>; // locals bound to a package (non-relative) import
  relative: Map<string, RelativeImport>; // locals bound to a relative import
}

/** Source files we never treat as models: the manifest itself and tests. */
function isModelFile(file: string): boolean {
  return (
    file.endsWith(".ts") &&
    file !== MANIFEST_NAME &&
    !file.endsWith(".test.ts") &&
    !file.endsWith(".d.ts")
  );
}

function hasModifier(node: ts.ClassDeclaration, kind: ts.SyntaxKind): boolean {
  return (ts.getModifiers(node) ?? []).some((m) => m.kind === kind);
}

// `abstractClass` is the public getter/setter; `_abstractClass` is the backing
// field `Base` actually stores (base.ts) and several models set it directly
// (e.g. test-helpers/models/cat.ts). Accept either name.
const ABSTRACT_FLAGS = new Set(["abstractClass", "_abstractClass"]);

/** A class member that marks the class as abstract via `[_]abstractClass = true`. */
function memberMarksAbstract(m: ts.ClassElement): boolean {
  // `static [override] abstractClass = true;` (or `_abstractClass`)
  if (
    ts.isPropertyDeclaration(m) &&
    ts.isIdentifier(m.name) &&
    ABSTRACT_FLAGS.has(m.name.text) &&
    (m.modifiers ?? []).some((x) => x.kind === ts.SyntaxKind.StaticKeyword) &&
    m.initializer?.kind === ts.SyntaxKind.TrueKeyword
  ) {
    return true;
  }
  // `static { this.abstractClass = true; }` (or `this._abstractClass`) — the
  // dominant idiom in this repo's models, so detecting it is load-bearing.
  return (
    ts.isClassStaticBlockDeclaration(m) &&
    m.body.statements.some(
      (s) =>
        ts.isExpressionStatement(s) &&
        ts.isBinaryExpression(s.expression) &&
        s.expression.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        ts.isPropertyAccessExpression(s.expression.left) &&
        s.expression.left.expression.kind === ts.SyntaxKind.ThisKeyword &&
        ABSTRACT_FLAGS.has(s.expression.left.name.text) &&
        s.expression.right.kind === ts.SyntaxKind.TrueKeyword,
    )
  );
}

/**
 * Whether a class is an abstract base rather than a concrete model — the TS
 * `abstract` keyword, or the Rails-idiomatic `abstractClass = true` (as a
 * static field or a `static {}` block). These bridge the `extends` chain (so
 * their subclasses are found) but are never registered: they map to no table,
 * so registering one and reflecting its schema would fail.
 */
function isAbstractModel(node: ts.ClassDeclaration): boolean {
  if (hasModifier(node, ts.SyntaxKind.AbstractKeyword)) return true;
  return node.members.some(memberMarksAbstract);
}

/**
 * Resolve a relative import specifier to a scanned filename. Only same-dir
 * `./<name>.(js|ts)` is resolvable — the scan is a flat directory, so nested
 * (`./sub/x.js`) or parent (`../x.js`) targets aren't part of it and stop the
 * walk. ESM specifiers carry `.js`; the on-disk source is `.ts`.
 */
function resolveRelativeFile(specifier: string): string | undefined {
  const m = /^\.\/([^/]+)\.(?:js|ts)$/.exec(specifier);
  return m ? `${m[1]}.ts` : undefined;
}

/**
 * Classify a file's imports so the inheritance walk knows what an `extends X`
 * targets: ActiveRecord's `Base` (terminal), a relative import (followed into
 * its target file, alias-aware), or a package import (`external`, stops the
 * walk even if the name collides with a real local model/base). Same-file
 * declarations aren't imports and are resolved directly against the file.
 */
function collectImports(sf: ts.SourceFile): Pick<FileInfo, "arBase" | "external" | "relative"> {
  const arBase = new Set<string>();
  const external = new Set<string>();
  const relative = new Map<string, RelativeImport>();
  for (const stmt of sf.statements) {
    if (!ts.isImportDeclaration(stmt) || !ts.isStringLiteral(stmt.moduleSpecifier)) continue;
    const spec = stmt.moduleSpecifier.text;
    const isRelative = spec.startsWith("./") || spec.startsWith("../");
    const relFile = isRelative ? resolveRelativeFile(spec) : undefined;
    const clause = stmt.importClause;
    if (!clause) continue;
    const bind = (local: string, original: string): void => {
      if (spec === AR_PACKAGE && original === "Base") arBase.add(local);
      else if (!isRelative) external.add(local);
      else if (relFile) relative.set(local, { original, file: relFile });
      // unresolvable relative (nested/parent) → untracked → stops the walk
    };
    if (clause.name) bind(clause.name.text, "default"); // `import Foo from ...`
    const nb = clause.namedBindings;
    if (nb && ts.isNamedImports(nb)) {
      for (const el of nb.elements) bind(el.name.text, (el.propertyName ?? el.name).text);
    } else if (nb && ts.isNamespaceImport(nb) && !isRelative) {
      external.add(nb.name.text); // `import * as Foo from "pkg"`
    }
  }
  return { arBase, external, relative };
}

/** The name of a file's `export default class`, if any (for default imports). */
function defaultExportName(info: FileInfo): string | undefined {
  for (const node of info.classes.values()) if (node.isDefault) return node.name;
  return undefined;
}

/** The identifier name of a class's `extends` clause, if it extends one. */
function extendsName(node: ts.ClassDeclaration): string | undefined {
  for (const clause of node.heritageClauses ?? []) {
    if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
    const expr = clause.types[0]?.expression;
    if (expr && ts.isIdentifier(expr)) return expr.text;
  }
  return undefined;
}

/**
 * Parse every model file under `modelsDir` and return the exported classes
 * whose `extends` chain transitively reaches `Base`, sorted by class name so
 * the emitted manifest is byte-stable.
 */
export async function scanModels(modelsDir: string): Promise<ModelEntry[]> {
  const fs = await getFsAsync();
  const path = await getPathAsync();

  let names: string[];
  try {
    names = await fs.readdir!(modelsDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error(`models directory not found: ${modelsDir}`, { cause: err });
    }
    throw err;
  }
  const files = names.filter(isModelFile).sort();

  const byFile = new Map<string, FileInfo>();
  for (const file of files) {
    const text = await fs.readFile!(path.join(modelsDir, file), "utf8");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.ES2022, true);
    const classes = new Map<string, ClassNode>();
    for (const stmt of sf.statements) {
      if (!ts.isClassDeclaration(stmt) || !stmt.name) continue;
      classes.set(stmt.name.text, {
        name: stmt.name.text,
        parent: extendsName(stmt),
        isExported: hasModifier(stmt, ts.SyntaxKind.ExportKeyword),
        isDefault: hasModifier(stmt, ts.SyntaxKind.DefaultKeyword),
        isAbstract: isAbstractModel(stmt),
      });
    }
    byFile.set(file, { file, classes, ...collectImports(sf) });
  }

  // Two exported classes sharing a name can't both be imported into the
  // manifest and signal an ambiguous constant — reject. (Non-exported classes
  // are file-local and may repeat across files, so they're exempt.)
  const exportedFrom = new Map<string, string>();
  for (const info of byFile.values()) {
    for (const node of info.classes.values()) {
      if (!node.isExported) continue;
      const prior = exportedFrom.get(node.name);
      if (prior) {
        throw new Error(`duplicate exported class "${node.name}" in ${prior} and ${info.file}`);
      }
      exportedFrom.set(node.name, info.file);
    }
  }

  // Does the class `name` (declared in `info`) transitively reach ActiveRecord's
  // `Base`? Resolution is scoped to each file: the `extends` target is matched
  // against that file's same-file declarations (followed in place, so a private
  // base counts), AR-Base imports (terminal), or relative imports (followed
  // into the target file by the imported name, alias-aware). Anything else —
  // a package import or unknown identifier — stops the walk. `memo` caches the
  // single-inheritance result; `seen` guards cycles.
  const memo = new Map<string, boolean>();
  function reachesBase(info: FileInfo, name: string, seen: Set<string>): boolean {
    const key = `${info.file}#${name}`;
    const cached = memo.get(key);
    if (cached !== undefined) return cached;
    if (seen.has(key)) return false;
    seen.add(key);
    let result = false;
    const parent = info.classes.get(name)?.parent;
    if (parent !== undefined) {
      if (info.arBase.has(parent)) result = true;
      else if (info.classes.has(parent)) result = reachesBase(info, parent, seen);
      else {
        const imp = info.relative.get(parent);
        const target = imp && byFile.get(imp.file);
        if (imp && target) {
          const targetName = imp.original === "default" ? defaultExportName(target) : imp.original;
          if (targetName !== undefined) result = reachesBase(target, targetName, seen);
        }
      }
    }
    memo.set(key, result);
    return result;
  }

  const entries: ModelEntry[] = [];
  for (const info of byFile.values()) {
    for (const node of info.classes.values()) {
      if (!node.isExported || node.isAbstract) continue;
      if (!reachesBase(info, node.name, new Set())) continue;
      entries.push({
        className: node.name,
        // `info.file` is a bare `*.ts` filename (isModelFile guarantees it);
        // swap the extension for the ESM `.js` specifier the manifest imports.
        importPath: `./${info.file.replace(/\.ts$/, ".js")}`,
        isDefault: node.isDefault,
      });
    }
  }
  return entries.sort((a, b) =>
    a.className < b.className ? -1 : a.className > b.className ? 1 : 0,
  );
}

/** Render the manifest source for a set of model entries. */
export function renderManifest(entries: ModelEntry[]): string {
  const names = entries.map((e) => e.className);
  let out = HEADER;
  out += `import { registerModel } from "@blazetrails/activerecord";\n`;
  for (const e of entries) {
    const binding = e.isDefault ? e.className : `{ ${e.className} }`;
    out += `import ${binding} from "${e.importPath}";\n`;
  }
  out += `\nexport const models = [${names.join(", ")}] as const;\n`;
  out += `for (const m of models) registerModel(m);\n`;
  if (names.length > 0) out += `\nexport { ${names.join(", ")} };\n`;
  return out;
}

/** Scan `modelsDir` and produce the manifest source it should contain. */
export async function buildManifest(modelsDir: string): Promise<string> {
  return renderManifest(await scanModels(modelsDir));
}

export interface ManifestResult {
  path: string; // absolute path of the manifest file
  content: string; // the manifest source the scan produced
  changed: boolean; // on-disk content differs (in write mode: was rewritten)
}

async function readIfPresent(fs: FsAdapter, path: string): Promise<string | undefined> {
  try {
    return await fs.readFile!(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

/**
 * Generate `<modelsDir>/index.ts`. With `check: true` it never writes — it only
 * reports whether the manifest is stale (CI drift detection). Otherwise it
 * writes only when content differs, keeping reruns idempotent.
 */
export async function generateManifest(
  modelsDir: string,
  options: { check?: boolean } = {},
): Promise<ManifestResult> {
  const fs = await getFsAsync();
  const path = (await getPathAsync()).join(modelsDir, MANIFEST_NAME);
  const content = await buildManifest(modelsDir);
  const existing = await readIfPresent(fs, path);
  const changed = existing !== content;
  if (!options.check && changed) await fs.writeFile!(path, content);
  return { path, content, changed };
}
