import { Dir, File } from "@blazetrails/ruby-compat";

import ts from "typescript";

const AR_PACKAGE = "@blazetrails/activerecord";
const MANIFEST_NAME = "index.ts";

const HEADER =
  "// AUTO-GENERATED by @blazetrails/activerecord-cli. Do not edit by hand.\n" +
  "// Re-run `ar generate:manifest` (or `ar init`) to update.\n";

export interface ModelEntry {
  className: string;
  importPath: string;
  isDefault: boolean;
}

interface ClassNode {
  name: string;
  parent: string | undefined;
  isExported: boolean;
  isDefault: boolean;
  isAbstract: boolean;
}

interface RelativeImport {
  original: string;
  file: string;
}

interface FileInfo {
  file: string;
  classes: Map<string, ClassNode>;
  arBase: Set<string>;
  external: Set<string>;
  relative: Map<string, RelativeImport>;
}

function isModelFile(file: string): boolean {
  return (
    file.endsWith(".ts") &&
    file !== MANIFEST_NAME &&
    !file.endsWith(".test.ts") &&
    !file.endsWith(".d.ts")
  );
}

function hasModifier(node: ts.ClassDeclaration, kind: ts.SyntaxKind): boolean {
  return (ts.getModifiers(node) ?? []).some((m) => m.kind === kind);
}

const ABSTRACT_FLAGS = new Set(["abstractClass", "_abstractClass"]);

function memberMarksAbstract(m: ts.ClassElement): boolean {
  if (
    ts.isPropertyDeclaration(m) &&
    ts.isIdentifier(m.name) &&
    ABSTRACT_FLAGS.has(m.name.text) &&
    (m.modifiers ?? []).some((x) => x.kind === ts.SyntaxKind.StaticKeyword) &&
    m.initializer?.kind === ts.SyntaxKind.TrueKeyword
  ) {
    return true;
  }
  return (
    ts.isClassStaticBlockDeclaration(m) &&
    m.body.statements.some(
      (s) =>
        ts.isExpressionStatement(s) &&
        ts.isBinaryExpression(s.expression) &&
        s.expression.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        ts.isPropertyAccessExpression(s.expression.left) &&
        s.expression.left.expression.kind === ts.SyntaxKind.ThisKeyword &&
        ABSTRACT_FLAGS.has(s.expression.left.name.text) &&
        s.expression.right.kind === ts.SyntaxKind.TrueKeyword,
    )
  );
}

function isAbstractModel(node: ts.ClassDeclaration): boolean {
  if (hasModifier(node, ts.SyntaxKind.AbstractKeyword)) return true;
  return node.members.some(memberMarksAbstract);
}

function resolveRelativeFile(specifier: string): string | undefined {
  const m = /^\.\/([^/]+)\.(?:js|ts)$/.exec(specifier);
  return m ? `${m[1]}.ts` : undefined;
}

function collectImports(sf: ts.SourceFile): Pick<FileInfo, "arBase" | "external" | "relative"> {
  const arBase = new Set<string>();
  const external = new Set<string>();
  const relative = new Map<string, RelativeImport>();
  for (const stmt of sf.statements) {
    if (!ts.isImportDeclaration(stmt) || !ts.isStringLiteral(stmt.moduleSpecifier)) continue;
    const spec = stmt.moduleSpecifier.text;
    const isRelative = spec.startsWith("./") || spec.startsWith("../");
    const relFile = isRelative ? resolveRelativeFile(spec) : undefined;
    const clause = stmt.importClause;
    if (!clause) continue;
    const bind = (local: string, original: string): void => {
      if (spec === AR_PACKAGE && original === "Base") arBase.add(local);
      else if (!isRelative) external.add(local);
      else if (relFile) relative.set(local, { original, file: relFile });
    };
    if (clause.name) bind(clause.name.text, "default");
    const nb = clause.namedBindings;
    if (nb && ts.isNamedImports(nb)) {
      for (const el of nb.elements) bind(el.name.text, (el.propertyName ?? el.name).text);
    } else if (nb && ts.isNamespaceImport(nb) && !isRelative) {
      external.add(nb.name.text);
    }
  }
  return { arBase, external, relative };
}

function defaultExportName(info: FileInfo): string | undefined {
  for (const node of info.classes.values()) if (node.isDefault) return node.name;
  return undefined;
}

function extendsName(node: ts.ClassDeclaration): string | undefined {
  for (const clause of node.heritageClauses ?? []) {
    if (clause.token !== ts.SyntaxKind.ExtendsKeyword) continue;
    const expr = clause.types[0]?.expression;
    if (expr && ts.isIdentifier(expr)) return expr.text;
  }
  return undefined;
}

export async function scanModels(modelsDir: string): Promise<ModelEntry[]> {
  let names: string[];
  try {
    names = Dir.children(modelsDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error(`models directory not found: ${modelsDir}`, { cause: err });
    }
    throw err;
  }
  const files = names.filter(isModelFile).sort();

  const byFile = new Map<string, FileInfo>();
  for (const file of files) {
    const text = File.read(File.join(modelsDir, file));
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.ES2022, true);
    const classes = new Map<string, ClassNode>();
    for (const stmt of sf.statements) {
      if (!ts.isClassDeclaration(stmt) || !stmt.name) continue;
      classes.set(stmt.name.text, {
        name: stmt.name.text,
        parent: extendsName(stmt),
        isExported: hasModifier(stmt, ts.SyntaxKind.ExportKeyword),
        isDefault: hasModifier(stmt, ts.SyntaxKind.DefaultKeyword),
        isAbstract: isAbstractModel(stmt),
      });
    }
    byFile.set(file, { file, classes, ...collectImports(sf) });
  }

  const exportedFrom = new Map<string, string>();
  for (const info of byFile.values()) {
    for (const node of info.classes.values()) {
      if (!node.isExported) continue;
      const prior = exportedFrom.get(node.name);
      if (prior) {
        throw new Error(`duplicate exported class "${node.name}" in ${prior} and ${info.file}`);
      }
      exportedFrom.set(node.name, info.file);
    }
  }

  const memo = new Map<string, boolean>();
  function reachesBase(info: FileInfo, name: string, seen: Set<string>): boolean {
    const key = `${info.file}#${name}`;
    const cached = memo.get(key);
    if (cached !== undefined) return cached;
    if (seen.has(key)) return false;
    seen.add(key);
    let result = false;
    const parent = info.classes.get(name)?.parent;
    if (parent !== undefined) {
      if (info.arBase.has(parent)) result = true;
      else if (info.classes.has(parent)) result = reachesBase(info, parent, seen);
      else {
        const imp = info.relative.get(parent);
        const target = imp && byFile.get(imp.file);
        if (imp && target) {
          const targetName = imp.original === "default" ? defaultExportName(target) : imp.original;
          if (targetName !== undefined) result = reachesBase(target, targetName, seen);
        }
      }
    }
    memo.set(key, result);
    return result;
  }

  const entries: ModelEntry[] = [];
  for (const info of byFile.values()) {
    for (const node of info.classes.values()) {
      if (!node.isExported || node.isAbstract) continue;
      if (!reachesBase(info, node.name, new Set())) continue;
      entries.push({
        className: node.name,
        importPath: `./${info.file.replace(/\.ts$/, ".js")}`,
        isDefault: node.isDefault,
      });
    }
  }
  return entries.sort((a, b) =>
    a.className < b.className ? -1 : a.className > b.className ? 1 : 0,
  );
}

export function renderManifest(entries: ModelEntry[]): string {
  const names = entries.map((e) => e.className);
  let out = HEADER;
  out += `import { registerModel } from "@blazetrails/activerecord";\n`;
  for (const e of entries) {
    const binding = e.isDefault ? e.className : `{ ${e.className} }`;
    out += `import ${binding} from "${e.importPath}";\n`;
  }
  out += `\nexport const models = [${names.join(", ")}] as const;\n`;
  out += `for (const m of models) registerModel(m);\n`;
  if (names.length > 0) out += `\nexport { ${names.join(", ")} };\n`;
  return out;
}

export async function buildManifest(modelsDir: string): Promise<string> {
  return renderManifest(await scanModels(modelsDir));
}

export interface ManifestResult {
  path: string;
  content: string;
  changed: boolean;
}

function readIfPresent(path: string): string | undefined {
  try {
    return File.read(path);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

export async function generateManifest(
  modelsDir: string,
  options: { check?: boolean } = {},
): Promise<ManifestResult> {
  const path = File.expandPath(MANIFEST_NAME, modelsDir);
  const content = await buildManifest(modelsDir);
  const existing = readIfPresent(path);
  const changed = existing !== content;
  if (!options.check && changed) File.write(path, content);
  return { path, content, changed };
}
