import { mkdir, writeFile, access } from "fs/promises";
import { dirname, join } from "path";

// The scaffold `ar init` writes, mirroring the §4.7 layout in the
// standalone-activerecord-cli proposal. `db/migrate/` is a directory, so it is
// materialized via a `.gitkeep` that keeps the empty dir under git.
const CONFIG_DATABASE = `/**
 * Connection config — the analog of Rails' \`config/database.yml\`. Keyed by
 * environment; \`TRAILS_ENV\` selects the entry (default "development").
 * \`Base.establishConnection()\` with no arguments reads this file. We key on
 * \`TRAILS_ENV\`, not \`NODE_ENV\` — the JS ecosystem treats \`NODE_ENV\` as a
 * build-time hint, so reusing it to pick a database selects the wrong one.
 */
const config = {
  development: { adapter: "sqlite3", database: "db/development.sqlite3", pool: 5 },
  test: { adapter: "sqlite3", database: ":memory:", pool: 1 },
  production: { adapter: "sqlite3", database: "db/production.sqlite3", pool: 5 },
};

export default config;
`;

const MODELS_INDEX = `// models/index.ts — AUTO-GENERATED by @blazetrails/activerecord-cli.
// Do not edit by hand. Re-run \`ar generate model <name>\` to update.
// Each model is imported here (so it exists — no Zeitwerk autoload) and
// registered, powering \`className:\`/\`through:\` lookups by name.
import { registerModel } from "@blazetrails/activerecord";

export const models = [] as const;

for (const m of models) registerModel(m);
`;

const DB_GLUE = `import { Base } from "@blazetrails/activerecord";
import { models } from "./models/index.js";

let connected = false;

/**
 * Establish the connection and reflect each model's columns from the live DB
 * schema (idempotent within a process). \`Base.establishConnection()\` with no
 * arguments reads \`config/database.ts\` for the current \`TRAILS_ENV\`. Run
 * after the tables exist (i.e. after migrating) and before any read/write.
 */
export async function connect(): Promise<void> {
  if (connected) return;
  await Base.establishConnection();
  await Promise.all(models.map((m) => m.loadSchema()));
  connected = true;
}
`;

const DB_SEEDS = `/**
 * Idempotent seed data — the analog of Rails' \`db/seeds.rb\`, run by
 * \`ar db:seed\`. Assumes the connection is established and schemas loaded;
 * import your models from "../models/index.js" and create records here.
 */
export async function seed(): Promise<void> {
  // Add seed data here, e.g. \`await User.findOrCreateBy({ ... });\`.
}
`;

const GITKEEP = "";

/** Files (path relative to root → body) that `ar init` scaffolds. */
const SCAFFOLD: ReadonlyArray<readonly [string, string]> = [
  ["config/database.ts", CONFIG_DATABASE],
  ["db/migrate/.gitkeep", GITKEEP],
  ["db/seeds.ts", DB_SEEDS],
  ["models/index.ts", MODELS_INDEX],
  ["db.ts", DB_GLUE],
];

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export interface InitResult {
  /** Paths (relative to root) that were written. */
  created: string[];
  /** Paths (relative to root) skipped because a file already existed. */
  skipped: string[];
}

/**
 * Scaffold a standalone-activerecord project under `root`. Never overwrites an
 * existing file — those are `skipped`, so re-running `ar init` is safe.
 */
export async function init(root: string): Promise<InitResult> {
  const created: string[] = [];
  const skipped: string[] = [];
  for (const [rel, body] of SCAFFOLD) {
    const target = join(root, rel);
    if (await exists(target)) {
      skipped.push(rel);
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, body, "utf8");
    created.push(rel);
  }
  return { created, skipped };
}
