import { mkdir, writeFile } from "fs/promises";
import { dirname, join } from "path";

// The files `ar init` writes, mirroring the §4.7 layout in the
// standalone-activerecord-cli proposal. `db/migrate/` is a directory, kept
// under git via a `.gitkeep`.
const CONFIG_DATABASE = `/**
 * Connection config — Rails' \`config/database.yml\`. \`establishConnection()\`
 * reads it; \`TRAILS_ENV\` selects the entry (default "development"). We key on
 * \`TRAILS_ENV\`, not \`NODE_ENV\`, which the JS ecosystem treats as a build-time
 * hint — reusing it to pick a database selects the wrong one.
 */
const config = {
  development: { adapter: "sqlite3", database: "db/development.sqlite3", pool: 5 },
  test: { adapter: "sqlite3", database: ":memory:", pool: 1 },
  production: { adapter: "sqlite3", database: "db/production.sqlite3", pool: 5 },
};

export default config;
`;

const MODELS_INDEX = `// AUTO-GENERATED by @blazetrails/activerecord-cli. Do not edit by hand.
// Each model is imported here (so it exists — no Zeitwerk autoload) and
// registered, powering \`className:\`/\`through:\` lookups by name.
import { registerModel } from "@blazetrails/activerecord";

export const models = [] as const;
for (const m of models) registerModel(m);
`;

const DB_GLUE = `import { Base } from "@blazetrails/activerecord";
import { models } from "./models/index.js";

let connected = false;

/**
 * Establish the connection and reflect each model's columns (idempotent).
 * \`establishConnection()\` reads \`config/database.ts\` for the current
 * \`TRAILS_ENV\`. Run after migrating, before any read/write.
 */
export async function connect(): Promise<void> {
  if (connected) return;
  await Base.establishConnection();
  await Promise.all(models.map((m) => m.loadSchema()));
  connected = true;
}
`;

const DB_SEEDS = `/**
 * Idempotent seed data — the analog of Rails' \`db/seeds.rb\`, run by
 * \`ar db:seed\`. Import models from "../models/index.js" and create here.
 */
export async function seed(): Promise<void> {
  // Add seed data here, e.g. \`await User.findOrCreateBy({ ... });\`.
}
`;

/** Files (path relative to root → body) that `ar init` scaffolds. */
const SCAFFOLD: ReadonlyArray<readonly [string, string]> = [
  ["config/database.ts", CONFIG_DATABASE],
  ["db/migrate/.gitkeep", ""],
  ["db/seeds.ts", DB_SEEDS],
  ["models/index.ts", MODELS_INDEX],
  ["db.ts", DB_GLUE],
];

export interface InitResult {
  /** Paths (relative to root) that were written. */
  created: string[];
  /** Paths (relative to root) skipped because a file already existed. */
  skipped: string[];
}

/**
 * Scaffold a standalone-activerecord project under `root`. Never overwrites an
 * existing file — those are `skipped`, so re-running `ar init` is safe.
 */
export async function init(root: string): Promise<InitResult> {
  const created: string[] = [];
  const skipped: string[] = [];
  for (const [rel, body] of SCAFFOLD) {
    const target = join(root, rel);
    await mkdir(dirname(target), { recursive: true });
    try {
      // `wx` creates atomically, failing with EEXIST if the path already
      // exists — no check-then-write TOCTOU window. EEXIST means "skip";
      // any other error (EACCES/EPERM/ENOTDIR…) is real and re-thrown.
      await writeFile(target, body, { flag: "wx" });
      created.push(rel);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "EEXIST") throw err;
      skipped.push(rel);
    }
  }
  return { created, skipped };
}
