/**
 * Mirrors Rails activerecord/test/cases/adapters/postgresql/range_test.rb
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { describeIfPg, PostgresAdapter, PG_TEST_URL } from "./test-helper.js";

describeIfPg("PostgresAdapter", () => {
  let adapter: PostgresAdapter;
  beforeEach(async () => {
    adapter = new PostgresAdapter(PG_TEST_URL);
  });
  afterEach(async () => {
    await adapter.close();
  });

  describe("PostgresqlRangeTest", () => {
    it.skip("int4range column", async () => {});
    it.skip("int4range default", async () => {});
    it.skip("int4range type cast", async () => {});
    it.skip("int4range write", async () => {});
    it.skip("int4range where", async () => {});
    it.skip("int4range contains", async () => {});
    it.skip("int4range empty", async () => {});
    it.skip("int4range infinity", async () => {});
    it.skip("int8range column", async () => {});
    it.skip("int8range type cast", async () => {});
    it.skip("int8range write", async () => {});
    it.skip("numrange column", async () => {});
    it.skip("numrange type cast", async () => {});
    it.skip("numrange write", async () => {});
    it.skip("tsrange column", async () => {});
    it.skip("tsrange type cast", async () => {});
    it.skip("tsrange write", async () => {});
    it.skip("tstzrange column", async () => {});
    it.skip("tstzrange type cast", async () => {});
    it.skip("tstzrange write", async () => {});
    it.skip("daterange column", async () => {});
    it.skip("daterange type cast", async () => {});
    it.skip("daterange write", async () => {});
    it.skip("custom range column", async () => {});
    it.skip("custom range type cast", async () => {});
    it.skip("custom range write", async () => {});
    it.skip("range schema dump", async () => {});
    it.skip("range migration", async () => {});
    it.skip("multirange int4", async () => {});
    it.skip("multirange int8", async () => {});
    it.skip("multirange num", async () => {});
    it.skip("multirange ts", async () => {});
    it.skip("multirange tstz", async () => {});
    it.skip("multirange date", async () => {});
    it.skip("range intersection", async () => {});
    it.skip("range union", async () => {});
    it.skip("range difference", async () => {});
    it.skip("range adjacent", async () => {});
    it.skip("range overlaps", async () => {});
    it.skip("range strictly left of", async () => {});
    it.skip("range strictly right of", async () => {});
    it.skip("range does not extend left of", async () => {});
    it.skip("range does not extend right of", async () => {});
    it.skip("range upper bound", async () => {});
    it.skip("range lower bound", async () => {});
    it.skip("data type of range types", () => {});
    it.skip("int4range values", () => {});
    it.skip("int8range values", () => {});
    it.skip("daterange values", () => {});
    it.skip("numrange values", () => {});
    it.skip("tsrange values", () => {});
    it.skip("tstzrange values", () => {});
    it.skip("custom range values", () => {});
    it.skip("timezone awareness tzrange", () => {});
    it.skip("timezone awareness endless tzrange", () => {});
    it.skip("timezone awareness beginless tzrange", () => {});
    it.skip("timezone array awareness tzrange", () => {});
    it.skip("create tstzrange", () => {});
    it.skip("update tstzrange", () => {});
    it.skip("escaped tstzrange", () => {});
    it.skip("unbounded tstzrange", () => {});
    it.skip("create tsrange", () => {});
    it.skip("update tsrange", () => {});
    it.skip("escaped tsrange", () => {});
    it.skip("unbounded tsrange", () => {});
    it.skip("timezone awareness tsrange", () => {});
    it.skip("timezone awareness endless tsrange", () => {});
    it.skip("timezone awareness beginless tsrange", () => {});
    it.skip("timezone array awareness tsrange", () => {});
    it.skip("create tstzrange preserve usec", () => {});
    it.skip("update tstzrange preserve usec", () => {});
    it.skip("create tsrange preserve usec", () => {});
    it.skip("update tsrange preserve usec", () => {});
    it.skip("timezone awareness tsrange preserve usec", () => {});
    it.skip("create numrange", () => {});
    it.skip("update numrange", () => {});
    it.skip("create daterange", () => {});
    it.skip("update daterange", () => {});
    it.skip("create int4range", () => {});
    it.skip("update int4range", () => {});
    it.skip("create int8range", () => {});
    it.skip("update int8range", () => {});
    it.skip("exclude beginning for subtypes without succ method is not supported", () => {});
    it.skip("where by attribute with range", () => {});
    it.skip("where by attribute with range in array", () => {});
    it.skip("update all with ranges", () => {});
    it.skip("ranges correctly escape input", () => {});
    it.skip("ranges correctly unescape output", () => {});
    it.skip("infinity values", () => {});
    it.skip("endless range values", () => {});
    it.skip("empty string range values", () => {});
  });
});
